import assert from 'node:assert/strict'
import test from 'node:test'
import { canOpenVisualComposer, createStructuredConfiguration } from '../src/hybridProductDesigner'
import { applyComposerItem, applyComposerTemplate, clearComposition, composerFieldDisplayName, confirmComposition, createEmptyComposition, deleteSelectedComposerComponent, moveComposerHinge, selectComposerComponent, selectComposerField } from '../src/visualComposerState'
import { VISUAL_COMPOSER_TEMPLATES } from '../src/visualComposerTemplates'

let sequence = 0
const id = () => `session-component-${++sequence}`
const opening = () => applyComposerItem(applyComposerTemplate(createEmptyComposition(), 'DEMO-WINDOW-FIXED'), 'FIELD_OPENING', id)
const directedOpening = () => applyComposerItem(opening(), 'OPEN_RIGHT', id)
test('DEMO template IDs са стабилни и уникални, включително четириполев прозорец', () => { assert.deepEqual(VISUAL_COMPOSER_TEMPLATES.map(({ id }) => id), ['DEMO-WINDOW-FIXED', 'DEMO-WINDOW-SINGLE', 'DEMO-WINDOW-DOUBLE', 'DEMO-WINDOW-TRIPLE', 'DEMO-WINDOW-QUADRUPLE', 'DEMO-WINDOW-TOP-FIXED', 'DEMO-WINDOW-BOTTOM-FIXED']); assert.equal(new Set(VISUAL_COMPOSER_TEMPLATES.map(({ id }) => id)).size, 7) })
test('template създава semantic fields и dividers без профили или hardware', () => { const state = applyComposerTemplate(createEmptyComposition(), 'DEMO-WINDOW-DOUBLE'); assert.equal(state.fields.length, 2); assert.equal(state.components.filter(({ role }) => role === 'DIVIDER').length, 1); assert.equal(JSON.stringify(state).includes('profile'), false); assert.equal(state.fields.every(({ attachedHandleId, attachedHingeIds }) => !attachedHandleId && !attachedHingeIds.length), true) })
test('поле се избира детерминистично', () => assert.equal(selectComposerField(applyComposerTemplate(createEmptyComposition(), 'DEMO-WINDOW-DOUBLE'), 'field-2').selectedFieldId, 'field-2'))
test('фиксирано и отваряемо поле се прилагат с явно действие', () => { const state = opening(); assert.equal(state.fields[0]?.fieldType, 'OPENABLE'); assert.equal(applyComposerItem(state, 'FIELD_FIXED', id).fields[0]?.fieldType, 'FIXED') })
test('opening direction е забранена за фиксирано поле', () => { const state = applyComposerTemplate(createEmptyComposition(), 'DEMO-WINDOW-FIXED'), next = applyComposerItem(state, 'OPEN_LEFT', id); assert.deepEqual(next.fields, state.fields); assert.match(next.message, /фиксирано/) })
test('посока се прилага върху отваряемо поле', () => assert.equal(applyComposerItem(opening(), 'OPEN_RIGHT', id).fields[0]?.openingDirection, 'RIGHT'))
test('дръжка е забранена за фикс и е максимум една', () => { const fixed = applyComposerTemplate(createEmptyComposition(), 'DEMO-WINDOW-FIXED'); assert.deepEqual(applyComposerItem(fixed, 'HANDLE', id).components, fixed.components); const once = applyComposerItem(directedOpening(), 'HANDLE', id), twice = applyComposerItem(once, 'HANDLE', id); assert.equal(once.components.filter(({ role }) => role === 'HANDLE').length, 1); assert.deepEqual(twice.components, once.components) })
test('отделните панти са неограничена семантична колекция с уникални ID и позиции', () => { let state = directedOpening(); for (const ratio of [.15, .4, .7, .9]) state = applyComposerItem(state, 'HINGE', id, ratio); const hinges = state.components.filter(({ role }) => role === 'HINGE'); assert.equal(hinges.length, 4); assert.equal(new Set(hinges.map(({ id }) => id)).size, 4); assert.deepEqual(hinges.map(({ positionRatio }) => positionRatio), [.15, .4, .7, .9]); assert.equal(hinges.every(({ side }) => side === 'RIGHT'), true) })
test('компонент без избрано поле не променя модела', () => { const state = { ...applyComposerTemplate(createEmptyComposition(), 'DEMO-WINDOW-FIXED'), selectedFieldId: null }, next = applyComposerItem(state, 'HANDLE', id); assert.deepEqual(next.fields, state.fields); assert.deepEqual(next.components, state.components) })
test('фиксиране премахва несъвместим hardware само по явно действие', () => { let state = applyComposerItem(directedOpening(), 'HANDLE', id); state = applyComposerItem(state, 'HINGE', id); const fixed = applyComposerItem(state, 'FIELD_FIXED', id); assert.equal(fixed.fields[0]?.attachedHandleId, null); assert.equal(fixed.fields[0]?.attachedHingeIds.length, 0); assert.equal(fixed.components.length, 0) })
test('ръчно добавен компонент може да бъде изтрит', () => { const state = applyComposerItem(opening(), 'HANDLE', id), next = deleteSelectedComposerComponent(state); assert.equal(next.components.length, 0); assert.equal(next.fields[0]?.attachedHandleId, null) })
test('snapshot history позволява Undo и Redo без mutation', () => { const empty = createEmptyComposition(), template = applyComposerTemplate(empty, 'DEMO-WINDOW-FIXED'), edited = opening(); const past = [empty, template], future = [edited]; assert.equal(past.at(-1)?.templateId, template.templateId); assert.equal(future[0]?.fields[0]?.fieldType, 'OPENABLE'); assert.equal(empty.templateId, null) })
test('clear връща EMPTY composition', () => { const cleared = clearComposition(opening()); assert.equal(cleared.status, 'EMPTY'); assert.equal(cleared.fields.length, 0) })
test('composition остава налична при връщане в същата mounted session', () => { const sessionValue = opening(), reopenedValue = sessionValue; assert.equal(reopenedValue.templateId, sessionValue.templateId); assert.equal(reopenedValue.fields[0]?.id, sessionValue.fields[0]?.id) })
test('редакция след човешко потвърждение връща NEEDS_REVIEW', () => { const confirmed = confirmComposition(directedOpening(), true), edited = applyComposerItem(confirmed, 'OPEN_LEFT', id); assert.equal(confirmed.status, 'HUMAN_CONFIRMED'); assert.equal(confirmed.fields[0]?.humanReviewState, 'HUMAN_CONFIRMED'); assert.equal(edited.status, 'NEEDS_REVIEW'); assert.equal(edited.fields[0]?.humanReviewState, 'UNREVIEWED') })
test('door threshold блокира composer, потвърден window го разрешава', () => { assert.equal(canOpenVisualComposer({ ...createStructuredConfiguration('DOOR'), status: 'HUMAN_CONFIRMED' }), false); assert.equal(canOpenVisualComposer({ ...createStructuredConfiguration('WINDOW'), status: 'HUMAN_CONFIRMED' }), true) })
test('safety flags са заключени', () => { const state = opening(); assert.deepEqual({ sessionOnly: state.sessionOnly, simulationOnly: state.simulationOnly, machineReady: state.machineReady, internalEvaluationOnly: state.internalEvaluationOnly, productionApproved: state.productionApproved, sourceImmutable: state.sourceImmutable, exportAvailable: state.exportAvailable, dwgWriteAvailable: state.dwgWriteAvailable, machineConnectivityAvailable: state.machineConnectivityAvailable, geometryCreated: state.geometryCreated }, { sessionOnly: true, simulationOnly: true, machineReady: false, internalEvaluationOnly: true, productionApproved: false, sourceImmutable: true, exportAvailable: false, dwgWriteAvailable: false, machineConnectivityAvailable: false, geometryCreated: false }) })
test('моделът няма persistence, network, export, DWG или machine payload', () => { const serialized = JSON.stringify(opening()); for (const forbidden of ['localStorage', 'indexedDB', 'fetch', 'endpoint', 'telemetry', 'exportPayload', 'dwgWriter', 'machineInstructions', 'operations', 'quantities']) assert.equal(serialized.includes(forbidden), false) })
test('keyboard алтернативата използва същото semantic apply действие', () => { const selectedLibraryItem = 'HANDLE' as const, state = applyComposerItem(directedOpening(), selectedLibraryItem, id); assert.equal(state.components.some(({ role }) => role === 'HANDLE'), true) })
test('предупреждението за непроизводствен чертеж е фиксиран UI invariant', () => { const warning = 'Концептуална 2D композиция — не е производствен чертеж.'; assert.match(warning, /не е производствен чертеж/) })
test('всички шаблони започват без direction, handle и hinges', () => { for (const template of VISUAL_COMPOSER_TEMPLATES) { const state = applyComposerTemplate(createEmptyComposition(), template.id); assert.equal(state.status, 'NEEDS_REVIEW'); assert.equal(state.fields.every((field) => field.openingDirection === null && field.attachedHandleId === null && field.attachedHingeIds.length === 0), true) } })
test('двукрилният шаблон няма автоматичен opening символ', () => { const state = applyComposerTemplate(createEmptyComposition(), 'DEMO-WINDOW-DOUBLE'); assert.equal(state.fields.every((field) => field.openingDirection === null), true) })
test('OPENABLE без direction блокира confirmation', () => { const state = opening(), confirmed = confirmComposition(state, true); assert.notEqual(confirmed.status, 'HUMAN_CONFIRMED'); assert.match(confirmed.message, /посока/) })
test('direction е изрично действие и не добавя hardware', () => { const before = opening(), after = applyComposerItem(before, 'OPEN_LEFT', id); assert.equal(before.fields[0]?.openingDirection, null); assert.equal(after.fields[0]?.openingDirection, 'LEFT'); assert.equal(after.fields[0]?.attachedHandleId, null); assert.equal(after.fields[0]?.attachedHingeIds.length, 0) })
test('видимите имена не използват raw field ID', () => { const fields = applyComposerTemplate(createEmptyComposition(), 'DEMO-WINDOW-DOUBLE').fields; assert.equal(composerFieldDisplayName(fields, 'field-1'), 'Ляво поле'); assert.equal(composerFieldDisplayName(fields, 'field-2'), 'Дясно поле'); assert.equal(composerFieldDisplayName(fields, 'field-1').includes('field-'), false) })
test('пантата изисква изрично поддържана посока и не мутира невалидно поле', () => { const undirected = opening(), rejected = applyComposerItem(undirected, 'HINGE', id, .3); assert.deepEqual(rejected.components, undirected.components); assert.deepEqual(rejected.fields, undirected.fields); const fixed = applyComposerTemplate(createEmptyComposition(), 'DEMO-WINDOW-FIXED'); assert.deepEqual(applyComposerItem(fixed, 'HINGE', id).components, fixed.components) })
test('лява и дясна посока определят страната на ръчно добавената панта', () => { const left = applyComposerItem(applyComposerItem(opening(), 'OPEN_LEFT', id), 'HINGE', id, .25), right = applyComposerItem(directedOpening(), 'HINGE', id, .75); assert.equal(left.components.at(-1)?.side, 'LEFT'); assert.equal(right.components.at(-1)?.side, 'RIGHT') })
test('позицията на панта се ограничава и мести независимо', () => { let state = applyComposerItem(directedOpening(), 'HINGE', id, -.5); state = applyComposerItem(state, 'HINGE', id, 2); const hinges = state.components.filter(({ type }) => type === 'HINGE'); assert.deepEqual(hinges.map(({ positionRatio }) => positionRatio), [0, 1]); const moved = moveComposerHinge(state, hinges[0]!.id, .63); assert.deepEqual(moved.components.filter(({ type }) => type === 'HINGE').map(({ positionRatio }) => positionRatio), [.63, 1]) })
test('отделна избрана панта може да бъде изтрита без останалите', () => { let state = applyComposerItem(directedOpening(), 'HINGE', id, .2); state = applyComposerItem(state, 'HINGE', id, .8); const firstId = state.components.find(({ type }) => type === 'HINGE')!.id; state = selectComposerComponent(state, firstId); const deleted = deleteSelectedComposerComponent(state); assert.equal(deleted.components.filter(({ type }) => type === 'HINGE').length, 1); assert.equal(deleted.fields[0]?.attachedHingeIds.includes(firstId), false) })
