import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import { createFacadeFlowRealDataIntakeDraft, evaluateFacadeFlowRealDataIntake, REAL_DATA_INTAKE_FIELD_DEFINITIONS, setFacadeFlowRealDataIntakeField } from '../src/aiRealDataIntake'

function resolveRequired(id = 'real-1') {
  let record = createFacadeFlowRealDataIntakeDraft(id)
  for (const field of REAL_DATA_INTAKE_FIELD_DEFINITIONS.filter((item) => item.requirement === 'REQUIRED')) record = setFacadeFlowRealDataIntakeField(record, field.id, `${field.id}-value`, 'RESOLVED', [`evidence-${field.id}`])
  return record
}

void test('06C.3.8 empty real-data draft starts unresolved with no invented values', () => { const record = createFacadeFlowRealDataIntakeDraft('empty'); assert.equal(record.status, 'UNRESOLVED'); assert.equal(record.reviewStatus, 'NOT_REVIEWED'); assert.equal(record.stagingStatus, 'NOT_STARTED'); assert.equal(record.acceptedIntoActiveData, false); assert.equal(record.autoMappingAllowed, false); assert.equal(record.machineReady, false); for (const field of Object.values(record.fields)) { assert.equal(field.state, 'UNRESOLVED'); assert.equal(field.value, null); assert.deepEqual(field.evidenceRefs, []) } })
void test('06C.3.8 contract defines required source identity fields and conditional engineering fields separately', () => { const required = REAL_DATA_INTAKE_FIELD_DEFINITIONS.filter((item) => item.requirement === 'REQUIRED').map((item) => item.id); const conditional = REAL_DATA_INTAKE_FIELD_DEFINITIONS.filter((item) => item.requirement === 'CONDITIONAL').map((item) => item.id); assert.deepEqual(required, ['sourceKind', 'sourceReference', 'sourceRevision', 'sourceLocation', 'recordKind', 'externalReference']); for (const id of ['productType', 'profileSystem', 'profileCode', 'dimensions', 'opening', 'hardware', 'glassFill', 'color', 'projectPosition', 'ruleEvidenceLinks']) assert.ok(conditional.includes(id as never)) })
void test('06C.3.8 missing a required provenance field remains UNRESOLVED', () => { let record = resolveRequired(); record = setFacadeFlowRealDataIntakeField(record, 'sourceRevision', null, 'UNRESOLVED'); assert.equal(record.status, 'UNRESOLVED'); assert.equal(record.acceptedIntoActiveData, false) })
void test('06C.3.8 any field conflict has precedence over otherwise review-ready data', () => { let record = resolveRequired(); assert.equal(record.status, 'READY_FOR_REVIEW'); record = setFacadeFlowRealDataIntakeField(record, 'profileSystem', 'SYSTEM-A / SYSTEM-B', 'CONFLICT', ['source-a', 'source-b']); assert.equal(record.status, 'CONFLICT'); assert.equal(record.reviewStatus, 'NOT_REVIEWED'); assert.equal(record.stagingStatus, 'NOT_STARTED') })
void test('06C.3.8 resolving the strict required contract yields READY_FOR_REVIEW but never accepts or validates the record', () => { const record = resolveRequired(); assert.equal(record.status, 'READY_FOR_REVIEW'); assert.equal(record.reviewStatus, 'NOT_REVIEWED'); assert.equal(record.stagingStatus, 'NOT_STARTED'); assert.equal(record.acceptedIntoActiveData, false); assert.equal(record.autoMappingAllowed, false); assert.equal(record.rulesValidated, false); assert.equal(record.productionLocked, true); assert.equal(record.machineReady, false) })
void test('06C.3.8 absent conditional product data stays unresolved instead of being inferred from other values', () => { const record = resolveRequired(); for (const id of ['productType', 'profileSystem', 'profileCode', 'opening', 'hardware', 'glassFill', 'color'] as const) { assert.equal(record.fields[id].state, 'UNRESOLVED'); assert.equal(record.fields[id].value, null) } assert.equal(record.status, 'READY_FOR_REVIEW') })
void test('06C.3.8 changing a resolved field to conflict re-evaluates the record without preserving stale readiness', () => { let record = resolveRequired(); assert.equal(record.status, 'READY_FOR_REVIEW'); record = setFacadeFlowRealDataIntakeField(record, 'externalReference', 'W-01 / W-02', 'CONFLICT'); assert.equal(record.status, 'CONFLICT'); record = setFacadeFlowRealDataIntakeField(record, 'externalReference', 'W-01', 'RESOLVED', ['source-w01']); assert.equal(record.status, 'READY_FOR_REVIEW') })
void test('06C.3.8 UI documents the intake contract but adds no import, auto-mapping, persistence or machine-ready path', () => { const component = readFileSync('src/components/RealDataIntakeContractFoundation.tsx', 'utf8'); const model = readFileSync('src/aiRealDataIntake.ts', 'utf8'); const pipeline = readFileSync('src/components/UnifiedDemoPipeline.tsx', 'utf8'); const combined = [component, model, pipeline].join('\n'); assert.match(component, /РЕАЛНИ ЗАПИСИ: 0/); assert.match(component, /STAGING: НЕ Е ЗАПОЧНАТ/); assert.match(component, /AUTO-MAPPING: НЕ/); assert.match(component, /НЕУТОЧНЕН/); assert.match(component, /КОНФЛИКТ/); assert.match(component, /ГОТОВ ЗА ПРЕГЛЕД/); assert.match(pipeline, /RealDataIntakeContractFoundation/); assert.doesNotMatch(combined, /fetch\s*\(|WebSocket\s*\(|localStorage|sessionStorage/); assert.doesNotMatch(combined, /machineReady\s*:\s*true|rulesValidated\s*:\s*true|acceptedIntoActiveData\s*:\s*true|autoMappingAllowed\s*:\s*true/) })
