import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import { buildFacadeFlowRuleApplicabilityFoundation, canHumanConfirmFacadeFlowRuleApplicability, confirmFacadeFlowRuleApplicability, createFacadeFlowRuleApplicabilityDraft, facadeFlowRuleApplicabilityMissingFields, RULE_APPLICABILITY_PRODUCT_TARGETS, updateFacadeFlowRuleApplicability } from '../src/aiRuleApplicability'
import { applyFacadeFlowAiDemoScenario, completeFacadeFlowDemoHumanReview, createFacadeFlowAiSession, prepareFacadeFlowDemoReviewPacket, prepareFacadeFlowDemoRulesGate, setFacadeFlowDemoReviewAccepted } from '../src/aiWorkspaceState'
import { sampleCatalogueProfiles } from '../src/profileCatalogueData'
import type { FacadeFlowAiDemoScenario, FacadeFlowRuleApplicabilityRecord } from '../src/aiWorkspaceTypes'

function rulesSession(scenario: FacadeFlowAiDemoScenario) { let session = applyFacadeFlowAiDemoScenario(createFacadeFlowAiSession(`applicability-${scenario}`), scenario, sampleCatalogueProfiles); session = prepareFacadeFlowDemoReviewPacket(session, sampleCatalogueProfiles); session = setFacadeFlowDemoReviewAccepted(session, true); session = completeFacadeFlowDemoHumanReview(session); return prepareFacadeFlowDemoRulesGate(session) }
function completeApplicabilityDraft(): FacadeFlowRuleApplicabilityRecord { return updateFacadeFlowRuleApplicability(createFacadeFlowRuleApplicabilityDraft('app-1', 'PROFILE_COMPATIBILITY'), { productTargets: ['WINDOW'], systemScopeMode: 'EXACT_SYSTEM', systemScope: 'REAL SYSTEM ID', projectScopeMode: 'SINGLE_PRODUCT', projectScope: '', decision: 'APPLIES', sourceRecordIds: ['source-confirmed-1'] }) }

void test('06C.3.5 applicability foundation does not exist before the rules gate exists', () => { const session = applyFacadeFlowAiDemoScenario(createFacadeFlowAiSession('no-gate'), 'GUIDED_WINDOW', sampleCatalogueProfiles); assert.equal(buildFacadeFlowRuleApplicabilityFoundation(session), null) })
void test('06C.3.5 guided window exposes only current DEMO context while all real applicability decisions remain unresolved', () => { const foundation = buildFacadeFlowRuleApplicabilityFoundation(rulesSession('GUIDED_WINDOW'))!; assert.equal(foundation.currentProductTarget, 'WINDOW'); assert.equal(foundation.currentSystemLabel, 'DEMO SYSTEM'); assert.equal(foundation.currentProjectScopeMode, 'STRUCTURED_POSITION'); assert.equal(foundation.currentProjectScopeLabel, 'DEMO-W-01'); assert.equal(foundation.realApplicabilityDecisionCount, 0); assert.equal(foundation.humanConfirmedDecisionCount, 0); assert.equal(foundation.validated, false); assert.equal(foundation.machineReady, false); assert.ok(foundation.rows.length >= 8); for (const row of foundation.rows) { assert.equal(row.decision, 'UNRESOLVED'); assert.deepEqual(row.productTargets, []); assert.equal(row.systemScopeMode, 'UNRESOLVED'); assert.equal(row.projectScopeMode, 'UNRESOLVED'); assert.deepEqual(row.sourceRecordIds, []) } })
void test('06C.3.5 guided door is a separate current product target without creating cross-product rule applicability', () => { const foundation = buildFacadeFlowRuleApplicabilityFoundation(rulesSession('GUIDED_DOOR'))!; assert.equal(foundation.currentProductTarget, 'DOOR'); assert.equal(foundation.realApplicabilityDecisionCount, 0); assert.ok(foundation.rows.every((row) => row.productTargets.length === 0)) })
void test('06C.3.5 product vocabulary explicitly prepares window, door, sliding system, facade and technical detail targets', () => { assert.deepEqual(RULE_APPLICABILITY_PRODUCT_TARGETS, ['WINDOW', 'DOOR', 'SLIDING_SYSTEM', 'FACADE', 'TECHNICAL_DETAIL']); const foundation = buildFacadeFlowRuleApplicabilityFoundation(rulesSession('GUIDED_WINDOW'))!; assert.ok(foundation.supportedProductTargets.includes('SLIDING_SYSTEM')); assert.ok(foundation.supportedProductTargets.includes('FACADE')) })
void test('06C.3.5 incomplete applicability records cannot be human-confirmed and need a confirmed source', () => { const draft = createFacadeFlowRuleApplicabilityDraft('app-empty', 'GEOMETRY_LIMITS'); assert.ok(facadeFlowRuleApplicabilityMissingFields(draft).length >= 5); assert.equal(canHumanConfirmFacadeFlowRuleApplicability(draft, 'Technologist', []), false); const complete = completeApplicabilityDraft(); assert.equal(canHumanConfirmFacadeFlowRuleApplicability(complete, 'Technologist', []), false); assert.equal(canHumanConfirmFacadeFlowRuleApplicability(complete, 'Technologist', ['source-confirmed-1']), true) })
void test('06C.3.5 a human-confirmed applicability decision still does not validate an engineering rule or become machine-ready', () => { const confirmed = confirmFacadeFlowRuleApplicability(completeApplicabilityDraft(), 'Technologist', '2026-08-31T13:00:00+03:00', ['source-confirmed-1'], 'Applicability only'); assert.equal(confirmed.reviewStatus, 'HUMAN_CONFIRMED'); assert.equal(confirmed.decision, 'APPLIES'); assert.equal(confirmed.machineReady, false) })
void test('06C.3.5 changing product/system/project applicability invalidates the old human confirmation', () => { const confirmed = confirmFacadeFlowRuleApplicability(completeApplicabilityDraft(), 'Technologist', '2026-08-31T13:00:00+03:00', ['source-confirmed-1']); const changed = updateFacadeFlowRuleApplicability(confirmed, { systemScope: 'ANOTHER REAL SYSTEM' }); assert.equal(changed.reviewStatus, 'NEEDS_REVIEW'); assert.equal(changed.reviewer, ''); assert.equal(changed.reviewedAt, null); assert.equal(changed.machineReady, false) })
void test('06C.3.5 UI shows a zero-decision matrix and keeps rule validation, handoff and production locked', () => { const component = readFileSync('src/components/RuleApplicabilityFoundation.tsx', 'utf8'); const model = readFileSync('src/aiRuleApplicability.ts', 'utf8'); const combined = [component, model].join('\n'); assert.match(component, /РЕАЛНИ РЕШЕНИЯ:/); assert.match(component, /Плъзгаща система/); assert.match(component, /Фасада/); assert.match(component, /Точна система/); assert.match(component, /РЕАЛНА ПРИЛОЖИМОСТ: НЕ Е ОПРЕДЕЛЕНА/); assert.match(component, /HANDOFF: LOCKED/); assert.doesNotMatch(combined, /fetch\s*\(|WebSocket\s*\(|localStorage|sessionStorage/); assert.doesNotMatch(combined, /machineReady\s*:\s*true|validated\s*:\s*true|productionApproved\s*:\s*true/) })
