import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import { aggregateFacadeFlowRuleEvaluations } from '../src/aiRuleValidationAggregation'
import { buildFacadeFlowRuleEvaluationFoundation, completeFacadeFlowRuleEvaluation, createFacadeFlowRuleEvaluationDraft, updateFacadeFlowRuleEvaluation } from '../src/aiRuleEvaluation'
import { applyFacadeFlowAiDemoScenario, completeFacadeFlowDemoHumanReview, createFacadeFlowAiSession, prepareFacadeFlowDemoReviewPacket, prepareFacadeFlowDemoRulesGate, setFacadeFlowDemoReviewAccepted } from '../src/aiWorkspaceState'
import { sampleCatalogueProfiles } from '../src/profileCatalogueData'
import type { FacadeFlowRuleEvaluationRecord, FacadeFlowRuleGateRequirementId } from '../src/aiWorkspaceTypes'

function rulesSession() { let session = applyFacadeFlowAiDemoScenario(createFacadeFlowAiSession('aggregation-window'), 'GUIDED_WINDOW', sampleCatalogueProfiles); session = prepareFacadeFlowDemoReviewPacket(session, sampleCatalogueProfiles); session = setFacadeFlowDemoReviewAccepted(session, true); session = completeFacadeFlowDemoHumanReview(session); return prepareFacadeFlowDemoRulesGate(session) }
function evidence(id: string) { return [{ id: `evidence-${id}`, sourceName: 'Real checked evidence', sourceKind: 'MANUAL' as const, location: 'W-01', revision: 'R1' }] }
function reviewed(id: string, requirementId: FacadeFlowRuleGateRequirementId, result: 'PASS' | 'FAIL' | 'NOT_APPLICABLE'): FacadeFlowRuleEvaluationRecord {
  const decision = result === 'NOT_APPLICABLE' ? 'DOES_NOT_APPLY' as const : 'APPLIES' as const
  const draft = updateFacadeFlowRuleEvaluation(createFacadeFlowRuleEvaluationDraft(id, requirementId, `app-${id}`), { ruleId: `RULE-${id}`, ruleRevision: 'REV-A', applicabilityDecision: decision, sourceRecordIds: [`source-${id}`], evidence: evidence(id), observationSummary: result === 'NOT_APPLICABLE' ? '' : `Observed ${id}`, result })
  return completeFacadeFlowRuleEvaluation(draft, 'Technologist', '2026-08-31T15:00:00+03:00', [`source-${id}`], [`app-${id}`])
}

void test('06C.3.7 default 06C.3.6 foundation aggregates to INCOMPLETE with no fake decision', () => { const rows = buildFacadeFlowRuleEvaluationFoundation(rulesSession())!.rows; const aggregate = aggregateFacadeFlowRuleEvaluations(rows); assert.equal(aggregate.state, 'INCOMPLETE'); assert.equal(aggregate.humanReviewedCount, 0); assert.equal(aggregate.needsEvidenceCount, rows.length); assert.equal(aggregate.validationDecision, 'NOT_MADE'); assert.equal(aggregate.rulesValidated, false); assert.equal(aggregate.machineReady, false) })
void test('06C.3.7 an unreviewed PASS is never counted as PASS and keeps the gate incomplete', () => { const row = updateFacadeFlowRuleEvaluation(createFacadeFlowRuleEvaluationDraft('unreviewed', 'GEOMETRY_LIMITS'), { result: 'PASS' }); const aggregate = aggregateFacadeFlowRuleEvaluations([row]); assert.equal(aggregate.state, 'INCOMPLETE'); assert.equal(aggregate.passCount, 0); assert.equal(aggregate.humanReviewedCount, 0); assert.equal(aggregate.needsEvidenceCount, 1) })
void test('06C.3.7 a HUMAN REVIEWED FAIL blocks the entire aggregate even when other checks pass', () => { const aggregate = aggregateFacadeFlowRuleEvaluations([reviewed('pass', 'GEOMETRY_LIMITS', 'PASS'), reviewed('fail', 'PROFILE_COMPATIBILITY', 'FAIL')]); assert.equal(aggregate.state, 'BLOCKED_BY_FAIL'); assert.equal(aggregate.passCount, 1); assert.equal(aggregate.failCount, 1); assert.deepEqual(aggregate.blockerRequirementIds, ['PROFILE_COMPATIBILITY']); assert.equal(aggregate.handoffLocked, true); assert.equal(aggregate.productionLocked, true) })
void test('06C.3.7 reviewed PASS and NOT_APPLICABLE rows can form REVIEWED_COMPLETE but still do not validate rules', () => { const aggregate = aggregateFacadeFlowRuleEvaluations([reviewed('pass-a', 'GEOMETRY_LIMITS', 'PASS'), reviewed('na', 'THRESHOLD', 'NOT_APPLICABLE'), reviewed('pass-b', 'GLAZING_FILL', 'PASS')]); assert.equal(aggregate.state, 'REVIEWED_COMPLETE'); assert.equal(aggregate.humanReviewedCount, 3); assert.equal(aggregate.passCount, 2); assert.equal(aggregate.notApplicableCount, 1); assert.equal(aggregate.failCount, 0); assert.equal(aggregate.rulesValidated, false); assert.equal(aggregate.finalApprovalCreated, false); assert.equal(aggregate.machineReady, false) })
void test('06C.3.7 FAIL has precedence over incomplete rows so blockers cannot be hidden by missing evidence', () => { const unresolved = createFacadeFlowRuleEvaluationDraft('pending', 'HARDWARE_OPENING'); const aggregate = aggregateFacadeFlowRuleEvaluations([reviewed('fail-priority', 'GEOMETRY_LIMITS', 'FAIL'), unresolved]); assert.equal(aggregate.state, 'BLOCKED_BY_FAIL'); assert.equal(aggregate.failCount, 1); assert.equal(aggregate.needsEvidenceCount, 1) })
void test('06C.3.7 empty evaluation sets remain incomplete and never become a vacuous PASS', () => { const aggregate = aggregateFacadeFlowRuleEvaluations([]); assert.equal(aggregate.state, 'INCOMPLETE'); assert.equal(aggregate.totalEvaluationCount, 0); assert.equal(aggregate.validationDecision, 'NOT_MADE'); assert.equal(aggregate.rulesValidated, false) })
void test('06C.3.7 aggregation never creates final approval, handoff, production or machine readiness', () => { const aggregate = aggregateFacadeFlowRuleEvaluations([reviewed('all-pass', 'GEOMETRY_LIMITS', 'PASS')]); assert.equal(aggregate.state, 'REVIEWED_COMPLETE'); assert.equal(aggregate.finalApprovalCreated, false); assert.equal(aggregate.handoffLocked, true); assert.equal(aggregate.productionLocked, true); assert.equal(aggregate.machineReady, false) })
void test('06C.3.7 UI exposes aggregate states and explicitly keeps final validation and production locked', () => { const component = readFileSync('src/components/RuleValidationAggregationFoundation.tsx', 'utf8'); const model = readFileSync('src/aiRuleValidationAggregation.ts', 'utf8'); const combined = [component, model].join('\n'); assert.match(component, /НЕПЪЛЕН GATE/); assert.match(component, /БЛОКИРАН ОТ FAIL/); assert.match(component, /ПРЕГЛЕДАН НАБОР/); assert.match(component, /ФИНАЛНО РЕШЕНИЕ: НЕ Е СЪЗДАДЕНО/); assert.match(component, /Отключване за производство не съществува/); assert.doesNotMatch(combined, /fetch\s*\(|WebSocket\s*\(|localStorage|sessionStorage/); assert.doesNotMatch(combined, /machineReady\s*:\s*true|rulesValidated\s*:\s*true|productionLocked\s*:\s*false|handoffLocked\s*:\s*false/) })
