import assert from 'node:assert/strict'
import test from 'node:test'
import { readFileSync } from 'node:fs'
import { applyComposerItem, applyComposerTemplate, createEmptyComposition, moveComposerHandle, moveComposerHinge, selectComposerComponent, setComposerColor } from '../src/visualComposerState'
import { VISUAL_COMPOSER_TEMPLATES } from '../src/visualComposerTemplates'
import { beginHardwareDrag, hardwareDragChanged, moveHardwareComponent, positionRatioFromSvgY, previewHardwareDrag, scaledClientYToPositionRatio } from '../src/visualComposerPointerDrag'
import { createOpeningGeometry } from '../src/visualComposerOpeningGeometry'

let n = 0
const id = () => `hardware-${++n}`
const directed = (direction: 'OPEN_LEFT' | 'OPEN_RIGHT' = 'OPEN_RIGHT') => applyComposerItem(applyComposerTemplate(createEmptyComposition(), 'DEMO-WINDOW-SINGLE'), direction, id)
test('библиотечните секции използват общо достъпно accordion поведение', () => { const source = readFileSync('src/components/VisualTemplateComposer.tsx', 'utf8'); for (const title of ['Шаблони', 'Тип поле', 'Посока на отваряне', 'Обков', 'Външен вид']) assert.ok(source.includes(title)); assert.ok(source.includes('aria-expanded')); assert.ok(source.includes('aria-controls')) })
test('шестте миниатюри съдържат само полета и делители без opening или hardware', () => { assert.equal(VISUAL_COMPOSER_TEMPLATES.length, 6); for (const template of VISUAL_COMPOSER_TEMPLATES) { assert.equal(template.fields.every(({ openingDirection }) => openingDirection === null), true); assert.equal(JSON.stringify(template).includes('HANDLE'), false); assert.equal(JSON.stringify(template).includes('HINGE'), false) } })
test('невалидните hardware действия не мутират модела', () => { const state = applyComposerTemplate(createEmptyComposition(), 'DEMO-WINDOW-SINGLE'); assert.deepEqual(applyComposerItem(state, 'HANDLE', id).components, state.components); assert.deepEqual(applyComposerItem(state, 'HINGE', id).components, state.components) })
test('дръжката има stable ID, позиция и противоположна на пантите страна', () => { const right = applyComposerItem(directed('OPEN_RIGHT'), 'HANDLE', id, .42), left = applyComposerItem(directed('OPEN_LEFT'), 'HANDLE', id, .6); assert.equal(right.components.at(-1)?.side, 'LEFT'); assert.equal(left.components.at(-1)?.side, 'RIGHT'); assert.equal(right.components.at(-1)?.positionRatio, .42); assert.equal(right.fields[0]?.attachedHandleId, right.components.at(-1)?.id) })
test('смяна на посоката синхронизира страните без да променя hardware ID', () => { let state = applyComposerItem(directed('OPEN_RIGHT'), 'HANDLE', id, .4); state = applyComposerItem(state, 'HINGE', id, .2); const ids = state.components.map(({ id: value }) => value); state = applyComposerItem(state, 'OPEN_LEFT', id); assert.deepEqual(state.components.map(({ id: value }) => value), ids); assert.equal(state.components.find(({ type }) => type === 'HANDLE')?.side, 'RIGHT'); assert.equal(state.components.find(({ type }) => type === 'HINGE')?.side, 'LEFT') })
test('позицията на дръжката се ограничава в 0..1 и мести само избраната дръжка', () => { const state = applyComposerItem(directed(), 'HANDLE', id, .5), handle = state.components.at(-1)!; const low = moveComposerHandle(state, handle.id, -2), high = moveComposerHandle(low, handle.id, 4); assert.equal(low.components.at(-1)?.positionRatio, 0); assert.equal(high.components.at(-1)?.positionRatio, 1); assert.equal(high.components.at(-1)?.id, handle.id) })
test('максимум една дръжка се допуска на поле', () => { const once = applyComposerItem(directed(), 'HANDLE', id), twice = applyComposerItem(once, 'HANDLE', id); assert.equal(twice.components.filter(({ type }) => type === 'HANDLE').length, 1) })
test('множество панти остават независими', () => { let state = applyComposerItem(directed(), 'HINGE', id, .2); state = applyComposerItem(state, 'HINGE', id, .8); const [first, second] = state.components.filter(({ type }) => type === 'HINGE'); const moved = moveComposerHinge(state, first!.id, .4); assert.equal(moved.components.find(({ id: value }) => value === first!.id)?.positionRatio, .4); assert.equal(moved.components.find(({ id: value }) => value === second!.id)?.positionRatio, .8) })
test('редът за показване на панти не променя stable ID', () => { let state = applyComposerItem(directed(), 'HINGE', id, .8); state = applyComposerItem(state, 'HINGE', id, .2); const ids = state.components.filter(({ type }) => type === 'HINGE').map(({ id: value }) => value); const sorted = [...state.components].filter(({ type }) => type === 'HINGE').sort((a, b) => (a.positionRatio ?? 0) - (b.positionRatio ?? 0)); assert.deepEqual(new Set(sorted.map(({ id: value }) => value)), new Set(ids)) })
test('няма автоматичен hardware', () => { for (const template of VISUAL_COMPOSER_TEMPLATES) assert.equal(applyComposerTemplate(createEmptyComposition(), template.id).components.some(({ role }) => role === 'HANDLE' || role === 'HINGE'), false) })
test('вътрешният и външният цвят са независими и няма автоматичен избор', () => { const empty = createEmptyComposition(); assert.equal(empty.interiorColor, ''); assert.equal(empty.exteriorColor, ''); const inside = setComposerColor(empty, 'INTERIOR', 'WHITE'), outside = setComposerColor(inside, 'EXTERIOR', 'BLACK'); assert.equal(outside.interiorColor, 'WHITE'); assert.equal(outside.exteriorColor, 'BLACK') })
test('друг цвят пази кратко ръчно описание', () => { const state = setComposerColor(createEmptyComposition(), 'INTERIOR', 'CUSTOM', 'Матово сиво'); assert.equal(state.interiorColorCustom, 'Матово сиво') })
test('промяна на цвят след потвърждение връща NEEDS_REVIEW', () => { const state = { ...directed(), status: 'HUMAN_CONFIRMED' as const }, changed = setComposerColor(state, 'EXTERIOR', 'SILVER'); assert.equal(changed.status, 'NEEDS_REVIEW') })
test('selection пази техническия ID без да го използва като човешко име', () => { const state = applyComposerItem(directed(), 'HANDLE', id), component = state.components.at(-1)!; assert.equal(selectComposerComponent(state, component.id).selectedComponentId, component.id) })
test('safety и session-only флаговете остават заключени', () => { const state = createEmptyComposition(); assert.deepEqual({ sessionOnly: state.sessionOnly, simulationOnly: state.simulationOnly, machineReady: state.machineReady, internalEvaluationOnly: state.internalEvaluationOnly, productionApproved: state.productionApproved, sourceImmutable: state.sourceImmutable, geometryCreated: state.geometryCreated, exportAvailable: state.exportAvailable, dwgWriteAvailable: state.dwgWriteAvailable, machineConnectivityAvailable: state.machineConnectivityAvailable }, { sessionOnly: true, simulationOnly: true, machineReady: false, internalEvaluationOnly: true, productionApproved: false, sourceImmutable: true, geometryCreated: false, exportAvailable: false, dwgWriteAvailable: false, machineConnectivityAvailable: false }) })
test('моделът няма persistence, network, export, DWG или machine capability', () => { const value = JSON.stringify(createEmptyComposition()); for (const forbidden of ['localStorage', 'indexedDB', 'fetch', 'endpoint', 'telemetry', 'operations', 'exportPayload', 'dwgWriter', 'machineInstructions']) assert.equal(value.includes(forbidden), false) })
test('pointer Y се преобразува до positionRatio и се clamp-ва', () => { assert.equal(positionRatioFromSvgY(150, 100, 200), .25); assert.equal(positionRatioFromSvgY(-50, 100, 200), 0); assert.equal(positionRatioFromSvgY(500, 100, 200), 1) })
test('различен SVG scale дава същата source позиция', () => { assert.equal(scaledClientYToPositionRatio(250, 50, 400, 800, 100, 400), .75); assert.equal(scaledClientYToPositionRatio(150, 50, 200, 800, 100, 400), .75) })
test('pointer drag пази само вертикален semantic ratio', () => { const drag = previewHardwareDrag(beginHardwareDrag('hardware-a', 7, .2), .65); assert.deepEqual(drag, { componentId: 'hardware-a', pointerId: 7, startRatio: .2, previewRatio: .65 }); assert.equal('x' in drag, false) })
test('един завършен drag мести само конкретния hardware ID и изисква проверка', () => { let state = applyComposerItem(directed(), 'HANDLE', id, .5); state = applyComposerItem(state, 'HINGE', id, .2); const handle = state.components.find(({ type }) => type === 'HANDLE')!, hinge = state.components.find(({ type }) => type === 'HINGE')!; const moved = moveHardwareComponent(state, handle.id, .8); assert.equal(moved.components.find(({ id: value }) => value === handle.id)?.positionRatio, .8); assert.equal(moved.components.find(({ id: value }) => value === hinge.id)?.positionRatio, .2); assert.equal(moved.status, 'NEEDS_REVIEW') })
test('дръжка и панта използват общата safe move функция', () => { let state = applyComposerItem(directed(), 'HANDLE', id, .5); state = applyComposerItem(state, 'HINGE', id, .3); for (const component of state.components.filter(({ role }) => role === 'HANDLE' || role === 'HINGE')) assert.equal(moveHardwareComponent(state, component.id, .6).components.find(({ id: value }) => value === component.id)?.positionRatio, .6) })
test('drag без промяна не създава semantic completion', () => { assert.equal(hardwareDragChanged(beginHardwareDrag('same', 1, .5)), false); assert.equal(hardwareDragChanged(previewHardwareDrag(beginHardwareDrag('moved', 1, .5), .7)), true) })
test('Escape и pointer cancel могат да отхвърлят preview без state mutation', () => { const state = applyComposerItem(directed(), 'HANDLE', id, .4), snapshot = JSON.stringify(state), preview = previewHardwareDrag(beginHardwareDrag(state.components.at(-1)!.id, 4, .4), .9); assert.equal(preview.startRatio, .4); assert.equal(JSON.stringify(state), snapshot) })
test('hardware hit area е достъпна и pointer event спира field propagation', () => { const source = readFileSync('src/components/VisualTemplateComposer.tsx', 'utf8'); assert.ok(source.includes('composer-hardware-hit')); assert.ok(source.includes('aria-label={`${label}')); assert.ok(source.includes('event.stopPropagation()')); assert.ok(source.includes('setPointerCapture')); assert.ok(source.includes('releasePointerCapture')) })
test('keyboard range контролът остава наличен', () => { const source = readFileSync('src/components/VisualTemplateComposer.tsx', 'utf8'); assert.ok(source.includes('type="range"')); assert.ok(source.includes("event.shiftKey")); assert.ok(source.includes("'ArrowUp'")) })
test('ляво отваряне използва произволни field-local bounds', () => { const geometry = createOpeningGeometry('LEFT', 310, 45, 180, 260)!; assert.equal(geometry.sidePath, 'M 310 45 L 490 175 L 310 305'); assert.deepEqual(geometry.bounds, { x: 310, y: 45, width: 180, height: 260 }) })
test('дясно отваряне е реално огледално в същите bounds', () => { const geometry = createOpeningGeometry('RIGHT', 310, 45, 180, 260)!; assert.equal(geometry.sidePath, 'M 490 45 L 310 175 L 490 305') })
test('дясно отваряне е видимо във второ и трето поле', () => { assert.equal(createOpeningGeometry('RIGHT', 400, 30, 200, 300)?.sidePath, 'M 600 30 L 400 180 L 600 330'); assert.equal(createOpeningGeometry('RIGHT', 600, 30, 200, 300)?.sidePath, 'M 800 30 L 600 180 L 800 330') })
test('opening geometry не зависи от field-1 и остава в bounds', () => { const geometry = createOpeningGeometry('RIGHT', 725, 110, 75, 90)!; assert.equal(JSON.stringify(geometry).includes('field-1'), false); for (const coordinate of geometry.sidePath!.match(/-?\d+(?:\.\d+)?/g)!.map(Number)) assert.ok(coordinate >= 75 || coordinate === 110 || coordinate === 155 || coordinate === 200 || coordinate === 725 || coordinate === 800) })
test('falling и combined нотациите използват local bounds', () => { const falling = createOpeningGeometry('TILT', 20, 30, 100, 80)!, combinedLeft = createOpeningGeometry('TILT_LEFT', 20, 30, 100, 80)!, combinedRight = createOpeningGeometry('TILT_RIGHT', 20, 30, 100, 80)!; assert.equal(falling.tiltPath, 'M 20 110 L 70 30 L 120 110'); assert.equal(combinedLeft.sidePath, 'M 20 30 L 120 70 L 20 110'); assert.equal(combinedRight.sidePath, 'M 120 30 L 20 70 L 120 110') })
test('fixed поле няма opening descriptor', () => assert.equal(createOpeningGeometry('FIXED', 0, 0, 100, 100), null))
test('renderer рисува opening над fill, clip-ва го локално и оставя hardware отгоре', () => { const source = readFileSync('src/components/VisualTemplateComposer.tsx', 'utf8'), field = source.indexOf('className={`composer-field'), opening = source.indexOf('<OpeningMark clipId='), hardware = source.indexOf('<HardwareMark key='); assert.ok(field >= 0 && opening > field && hardware > opening); assert.ok(source.includes('clipPath={`url(#${clipId})`}')) })
test('semantic RIGHT и visual descriptor са синхронизирани без автоматичен hardware', () => { const state = applyComposerItem(applyComposerTemplate(createEmptyComposition(), 'DEMO-WINDOW-DOUBLE'), 'OPEN_RIGHT', id), field = state.fields[0]!, geometry = createOpeningGeometry(field.openingDirection, 100, 100, 200, 300); assert.equal(field.openingDirection, 'RIGHT'); assert.ok(geometry?.sidePath); assert.equal(state.components.some(({ role }) => role === 'HANDLE' || role === 'HINGE'), false) })
test('при RIGHT пантата е вдясно, а дръжката вляво', () => { let state = applyComposerItem(directed('OPEN_RIGHT'), 'HINGE', id, .2); state = applyComposerItem(state, 'HANDLE', id, .5); assert.equal(state.components.find(({ type }) => type === 'HINGE')?.side, 'RIGHT'); assert.equal(state.components.find(({ type }) => type === 'HANDLE')?.side, 'LEFT') })
