import assert from 'node:assert/strict'
import test from 'node:test'
import { readFileSync } from 'node:fs'
import { DOOR_TEMPLATES } from '../src/doorComposerTemplates'
import { addDoorHardware, applyDoorTemplate, canAddDoorHardware, canConceptuallyReviewDoor, canConfigureDoorOpening, conceptuallyReviewDoor, deleteDoorHardware, doorOpeningWorkflowStatus, emptyDoorComposition, moveDoorHardware, selectDoorHardware, setDoorColor, setDoorInfill, setDoorOpening, suggestDoorHingePosition, validateDoorComposition } from '../src/doorComposerState'
import { doorOpeningGeometry } from '../src/doorOpeningGeometry'
import { getDoorComposerEligibility } from '../src/doorComposerEligibility'
import { createStructuredConfiguration, getProductNameSuggestions, getProductSizeSuggestions, updateStructuredConfiguration } from '../src/hybridProductDesigner'
import { sampleCatalogueProfiles } from '../src/profileCatalogueData'
import { calculateDoorDrawingLayout, calculateDoorFieldBounds, calculateDoorThumbnailFieldBounds, calculateProportionalProductBounds, findDoorDropTarget } from '../src/doorComposerLayout'
import { positionRatioFromSvgY, scaledClientYToPositionRatio } from '../src/visualComposerPointerDrag'
import { createOpeningGeometry } from '../src/visualComposerOpeningGeometry'

let sequence = 0
const id = () => `door-hw-${++sequence}`
const one = () => applyDoorTemplate(emptyDoorComposition(), 'DEMO-DOOR-SINGLE-SOLID')

test('осем stable door templates', () => { assert.equal(DOOR_TEMPLATES.length, 8); assert.equal(new Set(DOOR_TEMPLATES.map(x => x.id)).size, 8) })
test('templates нямат opening hardware colors threshold', () => { for (const t of DOOR_TEMPLATES) { assert.ok(t.fields.every(f => !f.hingeSide && !f.swing && !f.hingeIds.length && !f.handleId)); assert.equal(t.category, 'DOOR') } })
test('roles и infill са explicit', () => assert.ok(DOOR_TEMPLATES.flatMap(x => x.fields).some(f => f.role === 'FIXED_GLAZING')))
test('четири opening комбинации', () => { for (const side of ['LEFT', 'RIGHT'] as const) for (const swing of ['INWARD', 'OUTWARD'] as const) assert.ok(doorOpeningGeometry(side, swing, 10, 20, 100, 200)) })
test('right geometry е mirror', () => assert.equal(doorOpeningGeometry('RIGHT', 'INWARD', 10, 20, 100, 200)?.path, 'M 110 20 L 10 120 L 110 220'))
test('outward е dashed', () => assert.equal(doorOpeningGeometry('LEFT', 'OUTWARD', 0, 0, 10, 20)?.dash, '7 5'))
test('fixed rejects hardware', () => { const s = applyDoorTemplate(emptyDoorComposition(), 'DEMO-DOOR-SIDE-FIXED'), f = s.fields.find(x => x.role === 'FIXED_GLAZING')!; assert.equal(addDoorHardware(s, f.id, 'HINGE', id), s) })
test('multiple hinges and correct edge', () => { let s = setDoorOpening(one(), 'leaf-1', 'RIGHT', 'INWARD'); s = addDoorHardware(s, 'leaf-1', 'HINGE', id, .2); s = addDoorHardware(s, 'leaf-1', 'HINGE', id, .8); assert.equal(s.hardware.length, 2); assert.ok(s.hardware.every(x => x.side === 'RIGHT')) })
test('handle opposite edge and max one', () => { let s = setDoorOpening(one(), 'leaf-1', 'LEFT', 'INWARD'); s = addDoorHardware(s, 'leaf-1', 'HANDLE', id); assert.equal(s.hardware[0]?.side, 'RIGHT'); assert.equal(addDoorHardware(s, 'leaf-1', 'HANDLE', id), s) })
test('combined ratio clamps', () => assert.equal(setDoorInfill(one(), 'leaf-1', 'GLASS_TOP_PANEL_BOTTOM', 2).fields[0]?.splitRatio, 1))
test('concept review needs both choices', () => { assert.equal(conceptuallyReviewDoor(one(), true).conceptuallyReviewed, false); assert.equal(conceptuallyReviewDoor(setDoorOpening(one(), 'leaf-1', 'LEFT', 'OUTWARD'), true).conceptuallyReviewed, true) })
test('edit resets conceptual review', () => { const s = conceptuallyReviewDoor(setDoorOpening(one(), 'leaf-1', 'LEFT', 'OUTWARD'), true); assert.equal(setDoorInfill(s, 'leaf-1', 'GLAZED').conceptuallyReviewed, false) })
test('threshold remains unresolved and never HUMAN_CONFIRMED', () => { const s = conceptuallyReviewDoor(setDoorOpening(one(), 'leaf-1', 'LEFT', 'OUTWARD'), true); assert.equal(s.thresholdStatus, 'UNRESOLVED'); assert.equal('HUMAN_CONFIRMED' === s.status, false) })
test('safety locked', () => { const s = emptyDoorComposition(); assert.equal(s.machineReady, false); assert.equal(s.productionApproved, false); assert.equal(s.exportAvailable, false); assert.equal(s.sessionOnly, true) })
test('no capability payload', () => { const v = JSON.stringify(emptyDoorComposition()); for (const x of ['localStorage', 'fetch', 'operations', 'dwgWriter', 'machineOutput']) assert.equal(v.includes(x), false) })
test('eligibility е централизирана и изисква потвърждение', () => { const profiles = sampleCatalogueProfiles.map(p => ({ ...p })); let c = createStructuredConfiguration('DOOR'); c = updateStructuredConfiguration(c, { productName: 'DEMO врата', overallWidth: '900', overallHeight: '2100', profileSystem: 'DEMO SYSTEM' }, profiles); c = updateStructuredConfiguration(c, { frameProfileId: 'profile-demo-frame-01', sashProfileId: 'profile-demo-sash-01' }, profiles); assert.equal(getDoorComposerEligibility(c, false, profiles).eligible, false); const result = getDoorComposerEligibility(c, true, profiles); assert.equal(result.eligible, true); assert.equal(result.thresholdStatus, 'UNRESOLVED') })
test('move clamp и stable hardware ID', () => { let s = setDoorOpening(one(), 'leaf-1', 'LEFT', 'INWARD'); s = addDoorHardware(s, 'leaf-1', 'HINGE', id, .2); const hardwareId = s.hardware[0]!.id; s = moveDoorHardware(s, hardwareId, 2); assert.equal(s.hardware[0]!.id, hardwareId); assert.equal(s.hardware[0]!.positionRatio, 1) })
test('delete синхронизира references', () => { let s = setDoorOpening(one(), 'leaf-1', 'RIGHT', 'OUTWARD'); s = addDoorHardware(s, 'leaf-1', 'HANDLE', id); const hardwareId = s.hardware[0]!.id; s = deleteDoorHardware(s, hardwareId); assert.equal(s.hardware.length, 0); assert.equal(s.fields[0]!.handleId, null) })
test('цветовете са независими и не са автоматични', () => { let s = one(); assert.equal(s.interiorColor, ''); assert.equal(s.exteriorColor, ''); s = setDoorColor(s, 'INTERIOR', 'ANTHRACITE'); assert.equal(s.interiorColor, 'ANTHRACITE'); assert.equal(s.exteriorColor, '') })
test('review gate проверява всяко крило', () => { let s = applyDoorTemplate(emptyDoorComposition(), 'DEMO-DOOR-DOUBLE-SOLID'); s = setDoorOpening(s, 'leaf-1', 'LEFT', 'INWARD'); assert.equal(canConceptuallyReviewDoor(s, true), false); assert.ok(validateDoorComposition(s).some(e => e.includes('Дясно поле'))); s = setDoorOpening(s, 'leaf-2', 'RIGHT', 'OUTWARD'); assert.equal(canConceptuallyReviewDoor(s, true), true) })
test('нулиране на opening премахва обкова', () => { let s = setDoorOpening(one(), 'leaf-1', 'LEFT', 'INWARD'); s = addDoorHardware(s, 'leaf-1', 'HINGE', id); s = setDoorOpening(s, 'leaf-1', null, null); assert.equal(s.hardware.length, 0); assert.equal(s.fields[0]!.hingeIds.length, 0) })
test('осемте door name suggestions съответстват точно на templates', () => assert.deepEqual(getProductNameSuggestions('DOOR'), DOOR_TEMPLATES.map(template => template.name)))
test('door preset няма автоматична стойност в новата конфигурация', () => { const value = createStructuredConfiguration('DOOR'); assert.equal(value.productName, ''); assert.equal(value.overallWidth, ''); assert.equal(value.overallHeight, ''); assert.equal(getProductSizeSuggestions('DOOR').length, 4) })
test('900/2000 пази render ratio 0.45 и единен scale', () => { const b = calculateProportionalProductBounds(900, 2000, { x: 0, y: 0, width: 600, height: 400 }, 10); assert.ok(Math.abs(b.width / b.height - .45) < 1e-10); assert.ok(Math.abs(b.width / 900 - b.height / 2000) < 1e-10) })
test('1000/2100 и 1600/2100 пазят пропорциите', () => { for (const [w, h] of [[1000, 2100], [1600, 2100]]) { const b = calculateDoorDrawingLayout(w, h).frame; assert.ok(Math.abs(b.width / b.height - w / h) < 1e-10) } })
test('ръчно 900/900 остава square', () => { const b = calculateDoorDrawingLayout(900, 900).frame; assert.ok(Math.abs(b.width - b.height) < 1e-10) })
test('fit центрира и спазва padding', () => { const b = calculateProportionalProductBounds(100, 200, { x: 20, y: 30, width: 300, height: 400 }, 20); assert.equal(b.y, 50); assert.equal(b.height, 360); assert.equal(b.x + b.width / 2, 170) })
test('всички template fields остават във proportional frame', () => { for (const template of DOOR_TEMPLATES) { const frame = calculateDoorDrawingLayout(900, 2000).frame; for (const field of template.fields) { const b = calculateDoorFieldBounds(frame, field); assert.ok(b.x >= frame.x && b.y >= frame.y); assert.ok(b.x + b.width <= frame.x + frame.width + 1e-9); assert.ok(b.y + b.height <= frame.y + frame.height + 1e-9) } } })
test('threshold и dimensions следват frame bounds', () => { const layout = calculateDoorDrawingLayout(900, 2000), f = layout.frame; assert.equal(layout.threshold.y1, f.y + f.height); assert.equal(layout.threshold.x1, f.x); assert.equal(layout.threshold.x2, f.x + f.width); assert.equal(layout.horizontalDimension.x2, f.x + f.width); assert.equal(layout.verticalDimension.y2, f.y + f.height) })
test('opening и hardware ratio използват scaled field bounds', () => { const frame = calculateDoorDrawingLayout(900, 2000).frame, field = calculateDoorFieldBounds(frame, one().fields[0]!); const opening = doorOpeningGeometry('LEFT', 'INWARD', field.x, field.y, field.width, field.height)!; assert.deepEqual(opening.bounds, field); assert.equal(positionRatioFromSvgY(field.y + field.height * .75, field.y, field.height), .75); assert.equal(scaledClientYToPositionRatio(250, 50, 400, 520, field.y, field.height), positionRatioFromSvgY(260, field.y, field.height)) })
test('осемте thumbnails са portrait и структурно различими', () => { for (const template of DOOR_TEMPLATES) for (const field of template.fields) { const b = calculateDoorThumbnailFieldBounds(field); assert.ok(b.height >= b.width || field.rect.height < field.rect.width) } const double = DOOR_TEMPLATES.find(t => t.id === 'DEMO-DOOR-DOUBLE-SOLID')!, side = DOOR_TEMPLATES.find(t => t.id === 'DEMO-DOOR-SIDE-FIXED')!, top = DOOR_TEMPLATES.find(t => t.id === 'DEMO-DOOR-TOP-FIXED')!; assert.equal(double.fields.filter(f => f.role === 'DOOR_LEAF').length, 2); assert.equal(side.fields.some(f => f.role === 'FIXED_GLAZING' && f.rect.x > 0), true); assert.equal(top.fields.some(f => f.role === 'FIXED_GLAZING' && f.rect.y === 0), true) })
test('window opening layout helper няма regression', () => { const descriptor = createOpeningGeometry('RIGHT', 10, 20, 100, 200); assert.equal(descriptor?.sidePath, 'M 110 20 L 10 120 L 110 220') })
test('opening workflow започва без auto-selection', () => { const s = one(); assert.equal(s.fields[0]!.hingeSide, null); assert.equal(s.fields[0]!.swing, null); assert.equal(doorOpeningWorkflowStatus(s), 'Изберете страна на пантите'); assert.equal(canConfigureDoorOpening(s), true) })
test('hinge side разрешава hardware без inward/outward', () => { let s = setDoorOpening(one(), 'leaf-1', 'LEFT', null); assert.equal(canAddDoorHardware(s), true); assert.equal(canConceptuallyReviewDoor(s, true), false); s = addDoorHardware(s, 'leaf-1', 'HINGE', id); assert.equal(s.hardware.length, 1); assert.equal(s.hardware[0]!.side, 'LEFT') })
test('inward/outward синхронизират SVG descriptor и reset-ват review', () => { let s = conceptuallyReviewDoor(setDoorOpening(one(), 'leaf-1', 'LEFT', 'INWARD'), true); assert.equal(s.conceptuallyReviewed, true); s = setDoorOpening(s, 'leaf-1', 'RIGHT', 'OUTWARD'); assert.equal(s.conceptuallyReviewed, false); assert.equal(doorOpeningGeometry(s.fields[0]!.hingeSide, s.fields[0]!.swing, 0, 0, 10, 20)?.dash, '7 5'); assert.equal(doorOpeningWorkflowStatus(s), 'Отварянето е зададено') })
test('fixed glazing блокира opening и hardware controls', () => { const s = applyDoorTemplate(emptyDoorComposition(), 'DEMO-DOOR-SIDE-FIXED'), fixed = s.fields.find(f => f.role === 'FIXED_GLAZING')!, selected = { ...s, selectedFieldId: fixed.id }; assert.equal(canConfigureDoorOpening(selected), false); assert.equal(canAddDoorHardware(selected), false); assert.equal(doorOpeningWorkflowStatus(selected), 'Фиксираното поле няма отваряне') })
test('лява и дясна секция използват същия pure semantic action', () => { const left = setDoorOpening(one(), 'leaf-1', 'LEFT', 'INWARD'), right = setDoorOpening(left, 'leaf-1', 'RIGHT', 'OUTWARD'); assert.equal(left.fields[0]!.hingeSide, 'LEFT'); assert.equal(right.fields[0]!.hingeSide, 'RIGHT'); assert.equal(right.fields[0]!.swing, 'OUTWARD') })
test('лявата секция съдържа реални accessible opening controls и keyboard-native radios', () => { const source = readFileSync('src/components/DoorVisualComposer.tsx', 'utf8'); for (const text of ['Страна на пантите', 'Посока на движение', 'type="radio"', 'SIDE:LEFT', 'SIDE:RIGHT', 'SWING:INWARD', 'SWING:OUTWARD']) assert.equal(source.includes(text), true) })
test('desktop grid пази три equal-height панела и независим вътрешен scroll в реалния viewport', () => { const css = readFileSync('src/visualComposerUx.css', 'utf8'); assert.equal(css.includes('clamp(220px, 23vw, 270px) minmax(0, 1fr) clamp(240px, 25vw, 300px)'), true); assert.match(css,/\.detail-drafting \.visual-composer-stage[^}]*min-width: 0[^}]*min-height: 0[^}]*overflow-x: hidden[^}]*overflow-y: auto/); assert.equal(css.includes('overflow-y: auto'), true); assert.match(css,/\.detail-drafting \.visual-composer[^}]*height: 100dvh[^}]*min-height: 0/) })
test('selected hardware пази target leaf при add select move delete', () => { let s = setDoorOpening(one(), 'leaf-1', 'LEFT', 'INWARD'); s = addDoorHardware(s, 'leaf-1', 'HINGE', id); const hardwareId = s.selectedHardwareId!; assert.equal(s.selectedFieldId, 'leaf-1'); s = selectDoorHardware(s, hardwareId); assert.equal(s.selectedFieldId, 'leaf-1'); s = moveDoorHardware(s, hardwareId, .7); assert.equal(s.selectedFieldId, 'leaf-1'); s = deleteDoorHardware(s, hardwareId); assert.equal(s.selectedFieldId, 'leaf-1') })
test('reusable hinge tool добавя 1 2 3 4 unique stable IDs без replacement', () => { let s = setDoorOpening(one(), 'leaf-1', 'LEFT', null); for (let count = 1; count <= 4; count++) { s = addDoorHardware(s, 'leaf-1', 'HINGE', id); assert.equal(s.hardware.length, count); assert.equal(s.selectedTool, 'HINGE') } assert.equal(new Set(s.hardware.map(h => h.id)).size, 4); assert.equal(new Set(s.hardware.map(h => h.positionRatio)).size, 4) })
test('DEMO hinge position избягва пълно припокриване', () => { let s = setDoorOpening(one(), 'leaf-1', 'RIGHT', null); assert.equal(suggestDoorHingePosition(s, 'leaf-1'), .5); s = addDoorHardware(s, 'leaf-1', 'HINGE', id); assert.notEqual(suggestDoorHingePosition(s, 'leaf-1'), .5) })
test('scaled drop target приема leaf и отхвърля fixed/outside', () => { const s = applyDoorTemplate(emptyDoorComposition(), 'DEMO-DOOR-SIDE-FIXED'), frame = calculateDoorDrawingLayout(900, 2000).frame, leaf = calculateDoorFieldBounds(frame, s.fields.find(f => f.role === 'DOOR_LEAF')!), fixed = calculateDoorFieldBounds(frame, s.fields.find(f => f.role === 'FIXED_GLAZING')!); assert.equal(findDoorDropTarget(s.fields, frame, leaf.x + leaf.width / 2, leaf.y + leaf.height / 2), 'leaf-1'); assert.equal(findDoorDropTarget(s.fields, frame, fixed.x + fixed.width / 2, fixed.y + fixed.height / 2), null); assert.equal(findDoorDropTarget(s.fields, frame, -1, -1), null) })
test('quick-add toolbar fit target и ResizeObserver wiring са налични', () => { const source = readFileSync('src/components/DoorVisualComposer.tsx', 'utf8'); for (const text of ['+ Добави панта', '+ Добави дръжка', 'visual-composer-toolbar', 'Побери в изгледа', 'ResizeObserver', 'Изгледът е побран', 'Целево крило', 'Пуснете инструмента върху валидно крило', 'Началната позиция е демонстрационна']) assert.equal(source.includes(text), true) })
test('center съдържа само SVG и компактен non-form footer', () => { const source = readFileSync('src/components/DoorVisualComposer.tsx', 'utf8'), start = source.indexOf('<section ref={stageRef}'), end = source.indexOf('</section>', start), center = source.slice(start, end); assert.equal(center.includes('<Drawing'), true); assert.equal(center.includes('door-canvas-footer'), true); assert.equal(center.includes('<form'), false); assert.equal(center.includes('conceptuallyReviewDoor'), false); assert.equal(center.includes('Обобщение на вратата'), false) })
test('center grid footer и трите scroll колони не clip-ват достъпното съдържание', () => { const css = readFileSync('src/visualComposerUx.css', 'utf8'); for (const rule of ['grid-template-rows: minmax(320px, 1fr) auto', 'padding-bottom: 36px', 'scrollbar-gutter: stable', '.door-canvas-footer', '.door-opening-legend', '.door-canvas-footer { max-height: none; }']) assert.equal(css.includes(rule), true) })
test('summary и conceptual review остават в right properties panel', () => { const source = readFileSync('src/components/DoorVisualComposer.tsx', 'utf8'), properties = source.slice(source.indexOf('function Properties')); assert.equal(properties.includes('className="visual-properties"'), true); assert.equal(properties.includes('Обобщение на вратата'), true); assert.equal(properties.includes('Проверих концептуалната композиция'), true); assert.equal(properties.includes('Потвърди след проверка'), true) })
