import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import { buildFacadeFlowRuleEvaluationFoundation, canHumanReviewFacadeFlowRuleEvaluation, completeFacadeFlowRuleEvaluation, createFacadeFlowRuleEvaluationDraft, facadeFlowRuleEvaluationMissingFields, RULE_EVALUATION_RESULTS, updateFacadeFlowRuleEvaluation } from '../src/aiRuleEvaluation'
import { applyFacadeFlowAiDemoScenario, completeFacadeFlowDemoHumanReview, createFacadeFlowAiSession, prepareFacadeFlowDemoReviewPacket, prepareFacadeFlowDemoRulesGate, setFacadeFlowDemoReviewAccepted } from '../src/aiWorkspaceState'
import { sampleCatalogueProfiles } from '../src/profileCatalogueData'
import type { FacadeFlowRuleEvaluationRecord } from '../src/aiWorkspaceTypes'

function rulesSession() { let session = applyFacadeFlowAiDemoScenario(createFacadeFlowAiSession('evaluation-window'), 'GUIDED_WINDOW', sampleCatalogueProfiles); session = prepareFacadeFlowDemoReviewPacket(session, sampleCatalogueProfiles); session = setFacadeFlowDemoReviewAccepted(session, true); session = completeFacadeFlowDemoHumanReview(session); return prepareFacadeFlowDemoRulesGate(session) }
function evidence() { return [{ id: 'measurement-1', sourceName: 'Real checked measurement', sourceKind: 'MANUAL' as const, location: 'W-01', revision: 'R1' }] }
function completePassDraft(): FacadeFlowRuleEvaluationRecord { return updateFacadeFlowRuleEvaluation(createFacadeFlowRuleEvaluationDraft('evaluation-1', 'GEOMETRY_LIMITS', 'app-confirmed-1'), { ruleId: 'RULE-REAL-001', ruleRevision: 'REV-A', applicabilityDecision: 'APPLIES', sourceRecordIds: ['source-confirmed-1'], evidence: evidence(), observationSummary: 'Observed value checked against the real rule revision.', result: 'PASS' }) }

void test('06C.3.6 evaluation foundation does not exist before the rules gate exists', () => { const session = applyFacadeFlowAiDemoScenario(createFacadeFlowAiSession('evaluation-no-gate'), 'GUIDED_WINDOW', sampleCatalogueProfiles); assert.equal(buildFacadeFlowRuleEvaluationFoundation(session), null) })
void test('06C.3.6 every rules-gate category starts at NEEDS_EVIDENCE with zero real evaluations', () => { const foundation = buildFacadeFlowRuleEvaluationFoundation(rulesSession())!; assert.equal(foundation.realEvaluationCount, 0); assert.equal(foundation.humanReviewedEvaluationCount, 0); assert.equal(foundation.passCount, 0); assert.equal(foundation.failCount, 0); assert.equal(foundation.notApplicableCount, 0); assert.equal(foundation.needsEvidenceCount, foundation.rows.length); assert.equal(foundation.rulesValidated, false); assert.equal(foundation.handoffLocked, true); assert.equal(foundation.machineReady, false); for (const row of foundation.rows) { assert.equal(row.result, 'NEEDS_EVIDENCE'); assert.equal(row.reviewStatus, 'NEEDS_REVIEW'); assert.equal(row.ruleId, ''); assert.equal(row.ruleRevision, ''); assert.deepEqual(row.sourceRecordIds, []); assert.deepEqual(row.evidence, []) } })
void test('06C.3.6 result vocabulary prepares NEEDS_EVIDENCE, PASS, FAIL and NOT_APPLICABLE without assigning any of them automatically', () => { assert.deepEqual(RULE_EVALUATION_RESULTS, ['NEEDS_EVIDENCE', 'PASS', 'FAIL', 'NOT_APPLICABLE']) })
void test('06C.3.6 incomplete or unconfirmed evaluation cannot become HUMAN_REVIEWED', () => { const draft = createFacadeFlowRuleEvaluationDraft('empty', 'PROFILE_COMPATIBILITY'); assert.ok(facadeFlowRuleEvaluationMissingFields(draft).length >= 6); assert.equal(canHumanReviewFacadeFlowRuleEvaluation(draft, 'Technologist', [], []), false); const complete = completePassDraft(); assert.equal(canHumanReviewFacadeFlowRuleEvaluation(complete, 'Technologist', [], ['app-confirmed-1']), false); assert.equal(canHumanReviewFacadeFlowRuleEvaluation(complete, 'Technologist', ['source-confirmed-1'], []), false) })
void test('06C.3.6 PASS may be HUMAN_REVIEWED only with confirmed applicability, confirmed sources and concrete evidence, but never becomes machine-ready', () => { const reviewed = completeFacadeFlowRuleEvaluation(completePassDraft(), 'Technologist', '2026-08-31T14:00:00+03:00', ['source-confirmed-1'], ['app-confirmed-1'], 'Evaluation only'); assert.equal(reviewed.result, 'PASS'); assert.equal(reviewed.reviewStatus, 'HUMAN_REVIEWED'); assert.equal(reviewed.machineReady, false) })
void test('06C.3.6 NOT_APPLICABLE is accepted only from a human-confirmed DOES_NOT_APPLY applicability decision', () => { const base = updateFacadeFlowRuleEvaluation(createFacadeFlowRuleEvaluationDraft('evaluation-na', 'THRESHOLD', 'app-na-1'), { ruleId: 'RULE-REAL-NA', ruleRevision: 'REV-A', applicabilityDecision: 'DOES_NOT_APPLY', sourceRecordIds: ['source-confirmed-1'], evidence: evidence(), result: 'NOT_APPLICABLE' }); assert.equal(canHumanReviewFacadeFlowRuleEvaluation(base, 'Technologist', ['source-confirmed-1'], ['app-na-1']), true); const wrongDecision = updateFacadeFlowRuleEvaluation(base, { applicabilityDecision: 'APPLIES' }); assert.equal(canHumanReviewFacadeFlowRuleEvaluation(wrongDecision, 'Technologist', ['source-confirmed-1'], ['app-na-1']), false) })
void test('06C.3.6 changing a reviewed rule revision or evidence invalidates the old result and returns NEEDS_EVIDENCE', () => { const reviewed = completeFacadeFlowRuleEvaluation(completePassDraft(), 'Technologist', '2026-08-31T14:00:00+03:00', ['source-confirmed-1'], ['app-confirmed-1']); const changed = updateFacadeFlowRuleEvaluation(reviewed, { ruleRevision: 'REV-B' }); assert.equal(changed.reviewStatus, 'NEEDS_REVIEW'); assert.equal(changed.result, 'NEEDS_EVIDENCE'); assert.equal(changed.evaluator, ''); assert.equal(changed.evaluatedAt, null); assert.ok(changed.invalidationReasons.includes('RULE_REVISION_CHANGED')); assert.equal(changed.machineReady, false) })
void test('06C.3.6 UI exposes zero evaluation results and keeps rule validation, handoff and production locked', () => { const component = readFileSync('src/components/RuleEvaluationFoundation.tsx', 'utf8'); const model = readFileSync('src/aiRuleEvaluation.ts', 'utf8'); const combined = [component, model].join('\n'); assert.match(component, /РЕАЛНИ ОЦЕНКИ:/); assert.match(component, /НУЖНО Е ДОКАЗАТЕЛСТВО/); assert.match(component, /PASS \/ FAIL/); assert.match(component, /НЕ Е ПРИЛОЖИМО/); assert.match(component, /HANDOFF: LOCKED/); assert.doesNotMatch(combined, /fetch\s*\(|WebSocket\s*\(|localStorage|sessionStorage/); assert.doesNotMatch(combined, /machineReady\s*:\s*true|rulesValidated\s*:\s*true|productionApproved\s*:\s*true/) })
