import assert from 'node:assert/strict'
import test from 'node:test'
import { createHybridProductDesignerSession, HYBRID_SELECTABLE_CATEGORIES, returnToHybridDesignerStart, selectHybridCreationRoute, selectHybridStandardCategory, type HybridProductCategory } from '../src/hybridProductDesigner'
import { DETAIL_DRAFT_INITIAL_VIEWPORT, panDetailDraftViewport, zoomDetailDraftViewport } from '../src/detailDraftViewport'

test('initial session няма избран route или category', () => { const session = createHybridProductDesignerSession('test'); assert.equal(session.creationRoute, null); assert.equal(session.productCategory, null); assert.equal(session.workflowStep, 'DESIGNER_START') })
test('всеки creation route променя само Phase 06A.2 session модела', () => { const initial = createHybridProductDesignerSession('test'); assert.equal(selectHybridCreationRoute(initial, 'STANDARD').workflowStep, 'STANDARD_CATEGORY'); assert.equal(selectHybridCreationRoute(initial, 'SKETCH_ASSISTED').workflowStep, 'SKETCH_ROUTE'); assert.equal(selectHybridCreationRoute(initial, 'NON_STANDARD').workflowStep, 'NON_STANDARD_VIEWPORT'); assert.equal(initial.workflowStep, 'DESIGNER_START') })
test('само WINDOW и DOOR са selectable standard categories', () => assert.deepEqual(HYBRID_SELECTABLE_CATEGORIES, ['WINDOW', 'DOOR']))
test('disabled categories не могат да създадат selection', () => { const standard = selectHybridCreationRoute(createHybridProductDesignerSession(), 'STANDARD'); for (const category of ['SLIDING', 'SHOPFRONT', 'FACADE_MODULE'] as HybridProductCategory[]) assert.equal(selectHybridStandardCategory(standard, category), standard) })
test('WINDOW и DOOR създават само празна category draft', () => { for (const category of HYBRID_SELECTABLE_CATEGORIES) { const selected = selectHybridStandardCategory(selectHybridCreationRoute(createHybridProductDesignerSession(), 'STANDARD'), category); assert.equal(selected.productCategory, category); assert.equal(selected.workflowStep, 'STANDARD_DRAFT'); assert.equal(selected.geometryEntityCount, 0) } })
test('смяна на route изчиства incompatible category', () => { const windowDraft = selectHybridStandardCategory(selectHybridCreationRoute(createHybridProductDesignerSession(), 'STANDARD'), 'WINDOW'), sketch = selectHybridCreationRoute(windowDraft, 'SKETCH_ASSISTED'); assert.equal(sketch.productCategory, null); assert.equal(sketch.sourceReferenceStatus, 'ROUTE_SELECTED') })
test('връщане към начало нулира route и category безопасно', () => { const selected = selectHybridStandardCategory(selectHybridCreationRoute(createHybridProductDesignerSession('stable-session'), 'STANDARD'), 'DOOR'), reset = returnToHybridDesignerStart(selected); assert.equal(reset.id, 'stable-session'); assert.equal(reset.creationRoute, null); assert.equal(reset.productCategory, null); assert.equal(reset.geometryEntityCount, 0) })
test('non-standard route остава с нула geometry entities', () => assert.equal(selectHybridCreationRoute(createHybridProductDesignerSession(), 'NON_STANDARD').geometryEntityCount, 0))
test('sketch-assisted route не съдържа imported geometry или dimensions', () => { const sketch = selectHybridCreationRoute(createHybridProductDesignerSession(), 'SKETCH_ASSISTED') as unknown as Record<string, unknown>; assert.equal('geometry' in sketch, false); assert.equal('dimensions' in sketch, false); assert.equal('importedProducts' in sketch, false); assert.equal('operations' in sketch, false) })
test('всички safety и future capability flags са заключени', () => { const session = createHybridProductDesignerSession(); assert.deepEqual({ sessionOnly: session.sessionOnly, simulationOnly: session.simulationOnly, machineReady: session.machineReady, internalEvaluationOnly: session.internalEvaluationOnly, productionApproved: session.productionApproved, sourceImmutable: session.sourceImmutable, geometryCreated: session.geometryCreated, exportAvailable: session.exportAvailable, dwgWriteAvailable: session.dwgWriteAvailable, machineConnectivityAvailable: session.machineConnectivityAvailable }, { sessionOnly: true, simulationOnly: true, machineReady: false, internalEvaluationOnly: true, productionApproved: false, sourceImmutable: true, geometryCreated: false, exportAvailable: false, dwgWriteAvailable: false, machineConnectivityAvailable: false }); assert.deepEqual(Object.values(session.futureCapabilities), [false, false, false, false, false, false]) })
test('model няма export, persistence, network, writer или machine payload', () => { const serialized = JSON.stringify(createHybridProductDesignerSession()); for (const forbidden of ['localStorage', 'indexedDB', 'cookie', 'fetch', 'networkEndpoint', 'dwgWriter', 'dxfWriter', 'machineFormat', 'cuttingFormula', 'profileDeduction', 'tolerance', 'jointFormula', 'operations']) assert.equal(serialized.includes(forbidden), false) })
test('Phase 06A.1 viewport helpers остават приложими без geometry mutation', () => { const panned = panDetailDraftViewport(DETAIL_DRAFT_INITIAL_VIEWPORT, 10, 15), zoomed = zoomDetailDraftViewport(panned, 2, 50, 50); assert.deepEqual(panned, { scale: 1, offsetX: 10, offsetY: 15 }); assert.equal(zoomed.scale, 2) })
