import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { applyComposerItem, applyComposerTemplate, createEmptyComposition, selectComposerField, setComposerColor } from '../src/visualComposerState'
import { addDoorHardware, applyDoorTemplate, emptyDoorComposition, selectDoorField, setDoorColor, setDoorInfill, setDoorOpening } from '../src/doorComposerState'
import { beginCameraDrag, cameraKey, clampConceptualZoom, CONCEPTUAL_3D_INITIAL_VIEW, fitConceptualView, presetView, projectConceptualPoint, updateCameraDrag } from '../src/conceptual3dCamera'
import { DEMO_DEPTHS, fitSceneToViewport, hitTestProjected, previewColor, projectScene, sceneFitsViewport, shadeConceptualColor } from '../src/conceptual3dScene'
import { buildWindowConceptualScene } from '../src/conceptual3dWindowScene'
import { buildDoorConceptualScene } from '../src/conceptual3dDoorScene'
import { visibleConceptualColor } from '../src/conceptual3dRenderer'
import { changeStructuredCategory, createStructuredConfiguration, getProductNameSuggestions, getProductSizeSuggestions, hasUnusualDemonstrationalDoorProportion, selectHybridCreationRoute, selectHybridStandardCategory, createHybridProductDesignerSession } from '../src/hybridProductDesigner'
import { sampleCatalogueProfiles } from '../src/profileCatalogueData'
import { defaultProduct } from '../src/productData'
import { getProductTemplate, productTemplates, PRODUCT_CATEGORY_BY_TEMPLATE } from '../src/productTemplates'
import { applyLegacyDemoDimensions, hasUnusualLegacyDoorProportion, hasValidLegacyProductDimensions, selectLegacyProductTemplate } from '../src/legacyProductTransition'
import { calculateProductComponents } from '../src/productCalculations'
import { defaultProfile } from '../src/sampleData'
import { containsVisualBounds, fitVisualBounds, isValidDrawableSize } from '../src/composerViewport'

const windowState = () => applyComposerTemplate(createEmptyComposition(), 'DEMO-WINDOW-DOUBLE')
const doorState = () => applyDoorTemplate(emptyDoorComposition(), 'DEMO-DOOR-SINGLE-GLAZED')
test('focused composer viewport contract използва 100dvh и три независими scroll колони', () => { const css=readFileSync('src/visualComposerUx.css','utf8');assert.match(css,/\.detail-drafting \.visual-composer[^}]*height: 100dvh[^}]*min-height: 0[^}]*overflow: hidden/);assert.match(css,/\.door-composer \.visual-library, \.door-composer \.visual-properties[^}]*overflow-y: auto/);assert.match(css,/\.detail-drafting \.visual-composer-stage[^}]*min-height: 0[^}]*overflow-x: hidden[^}]*overflow-y: auto/) })
test('drawable fit е uniform, центриран и проверява четирите страни', () => { const fit=fitVisualBounds({x:0,y:0,width:800,height:520},640,440,{top:12,right:12,bottom:12,left:12})!;assert.equal(fit.rect.x+(fit.rect.width/2),320);assert.equal(fit.rect.y+(fit.rect.height/2),220);assert.equal(containsVisualBounds(640,440,fit.rect),true);assert.equal(containsVisualBounds(640,440,{...fit.rect,y:-1}),false) })
test('нулевото measurement не приключва fit, а първият валиден размер го разрешава', () => { assert.equal(isValidDrawableSize(0,440),false);assert.equal(fitVisualBounds({x:0,y:0,width:800,height:520},0,440),null);assert.equal(isValidDrawableSize(640,440),true);assert.ok(fitVisualBounds({x:0,y:0,width:800,height:520},640,440)) })
test('трите desktop колони имат независим normal scroll contract', () => { const css=readFileSync('src/visualComposerUx.css','utf8');assert.match(css,/\.detail-drafting \.visual-composer-stage[^}]*overflow-x: hidden[^}]*overflow-y: auto[^}]*scrollbar-gutter: stable/);assert.match(css,/\.door-composer \.visual-library, \.door-composer \.visual-properties[^}]*overflow-y: auto/);assert.doesNotMatch(css,/::-webkit-scrollbar|scrollbar-width:\s*none/) })
test('централната зона е keyboard достъпна и fit измерва client, не scroll размер', () => { const wizard=readFileSync('src/components/StructuredConfigurationWizard.tsx','utf8'),preview=readFileSync('src/components/Conceptual3DPreview.tsx','utf8');assert.match(wizard,/Централна работна зона — превъртаемо съдържание/);assert.match(wizard,/tabIndex=0/);assert.match(preview,/clientWidth/);assert.match(preview,/clientHeight/);assert.doesNotMatch(preview,/scrollHeight|scrollWidth/) })
test('center scroll остава layout-only, а canvas wheel остава camera-only', () => { const preview=readFileSync('src/components/Conceptual3DPreview.tsx','utf8'),wizard=readFileSync('src/components/StructuredConfigurationWizard.tsx','utf8');assert.match(preview,/onWheel={wheel}/);assert.match(preview,/event\.preventDefault\(\)/);assert.doesNotMatch(wizard,/setView|commit\(|setPast|setFuture/);assert.match(preview,/observer\.disconnect/);assert.match(wizard,/cancelAnimationFrame/) })
test('narrow layout връща normal page flow без вложен center scroll', () => { const css=readFileSync('src/visualComposerUx.css','utf8');assert.match(css,/@media \(max-width: 760px\)[^}]*\.detail-drafting \.visual-composer[^}]*position: relative/);assert.match(css,/\.detail-drafting \.visual-composer-stage \{ overflow: visible; scrollbar-gutter: auto/) })
test('scene nodes имат stable conceptual identity и locked geometry flags', () => { const a = buildWindowConceptualScene(windowState()), b = buildWindowConceptualScene(windowState()); assert.deepEqual(a.nodes.map(n => n.nodeId), b.nodes.map(n => n.nodeId)); assert.ok(a.nodes.every(n => n.conceptualPreviewOnly && !n.productionGeometry)); assert.equal(a.geometryCreated, false); assert.equal(a.productionGeometry, false); assert.equal(a.conceptualPreviewOnly, true) })
test('window scene съдържа frame fields glass и semantic IDs', () => { const state = windowState(), scene = buildWindowConceptualScene(state); assert.ok(scene.nodes.some(n => n.kind === 'FRAME')); for (const field of state.fields) assert.ok(scene.nodes.some(n => n.semanticSourceId === field.id)); assert.equal(scene.category, 'WINDOW') })
test('door scene съдържа frame sash glass и unresolved threshold warning', () => { const state = doorState(), scene = buildDoorConceptualScene(state); assert.ok(scene.nodes.some(n => n.kind === 'SASH')); assert.ok(scene.nodes.some(n => n.kind === 'GLASS')); assert.equal(scene.nodes.filter(n => n.kind === 'THRESHOLD_WARNING').length, 1); assert.equal(scene.thresholdUnresolved, true); assert.equal(scene.nodes.some(n => n.semanticSourceId === 'door-threshold' && n.kind === 'FRAME'), false) })
test('product dimensions управляват 3D aspect ratio без производствени дълбочини', () => { const tall=buildDoorConceptualScene(doorState(),900,2000),wide=buildWindowConceptualScene(windowState(),1400,1200); assert.equal(tall.bounds.width/tall.bounds.height,.45); assert.ok(wide.bounds.width>wide.bounds.height); assert.equal(tall.bounds.depth,.18) })
test('front/back materials следват external/internal DEMO colors', () => { let state = setComposerColor(windowState(), 'EXTERIOR', 'BLACK'); state = setComposerColor(state, 'INTERIOR', 'WHITE'); const frame = buildWindowConceptualScene(state).nodes.find(n => n.kind === 'FRAME')!; assert.equal(frame.material.front, '#20272a'); assert.equal(frame.material.back, '#f4f4ef') })
test('Front показва outside material, Back показва inside material', () => { let state=setComposerColor(windowState(),'EXTERIOR','BLACK');state=setComposerColor(state,'INTERIOR','WHITE');const material=buildWindowConceptualScene(state).nodes.find(node=>node.kind==='FRAME')!.material;assert.equal(visibleConceptualColor(material,presetView('FRONT')),'#20272a');assert.equal(visibleConceptualColor(material,presetView('BACK')),'#f4f4ef') })
test('Кафяво и Антрацит разрешават различни Canvas fill стойности', () => { assert.equal(previewColor('BROWN'),'#79533c');assert.equal(previewColor('ANTHRACITE'),'#465156');assert.notEqual(previewColor('BROWN'),previewColor('ANTHRACITE')) })
test('pure shading запазва base hue вместо общо сиво', () => { const brown=shadeConceptualColor(previewColor('BROWN'),.8),anthracite=shadeConceptualColor(previewColor('ANTHRACITE'),.8);assert.notEqual(brown,'#72878b');assert.notEqual(brown,anthracite);assert.equal(brown,shadeConceptualColor('#79533c',.8)) })
test('glass material остава различен от frame и sash', () => { const scene=buildDoorConceptualScene(doorState()),glass=scene.nodes.find(node=>node.kind==='GLASS')!,frame=scene.nodes.find(node=>node.kind==='FRAME')!;assert.notEqual(glass.material.front,frame.material.front);assert.ok(glass.material.opacity<1);assert.equal(frame.material.opacity,1) })
test('solid panel следва текущата видима страна с отличим conceptual shade', () => { let state=applyDoorTemplate(emptyDoorComposition(),'DEMO-DOOR-SINGLE-SOLID');state=setDoorColor(state,'EXTERIOR','ANTHRACITE');state=setDoorColor(state,'INTERIOR','BROWN');const panel=buildDoorConceptualScene(state).nodes.find(node=>node.kind==='SOLID_PANEL')!;assert.equal(visibleConceptualColor(panel.material,presetView('FRONT')),shadeConceptualColor('#465156',1.08));assert.equal(visibleConceptualColor(panel.material,presetView('BACK')),shadeConceptualColor('#79533c',1.08)) })
test('hardware material е контрастен и не наследява profile color', () => { let state=doorState(),id=state.fields[0]!.id;state=setDoorColor(state,'EXTERIOR','WHITE');state=setDoorOpening(state,id,'LEFT','INWARD');state=addDoorHardware(state,id,'HINGE',()=> 'contrast-hinge',.5);const hardware=buildDoorConceptualScene(state).nodes.find(node=>node.semanticSourceId==='contrast-hinge')!,frame=buildDoorConceptualScene(state).nodes.find(node=>node.kind==='FRAME')!;assert.equal(hardware.material.front,'#26383c');assert.notEqual(hardware.material.front,frame.material.front) })
test('isometric face shades са deterministic и произлизат от semantic base', () => { const base=previewColor('ANTHRACITE'),values=[0,1,2,3,4,5].map(index=>shadeConceptualColor(base,.72+index*.056));assert.deepEqual(values,[0,1,2,3,4,5].map(index=>shadeConceptualColor(base,.72+index*.056)));assert.equal(new Set(values).size,6) })
test('window и door споделят една material resolution policy', () => { let window=setComposerColor(windowState(),'EXTERIOR','BROWN'),door=setDoorColor(doorState(),'EXTERIOR','BROWN');assert.equal(buildWindowConceptualScene(window).nodes.find(node=>node.kind==='FRAME')?.material.front,buildDoorConceptualScene(door).nodes.find(node=>node.kind==='FRAME')?.material.front) })
test('неизбран и CUSTOM цвят използват neutral fallback без parsing', () => { assert.equal(previewColor(''), '#8a989b');assert.equal(previewColor('CUSTOM'),'#8a989b');assert.equal(previewColor('RAL 9005'),'#8a989b') })
test('scene пази overall dimensions за view-only dimension annotations', () => { const scene=buildDoorConceptualScene(doorState(),900,2000);assert.equal(scene.overallWidth,900);assert.equal(scene.overallHeight,2000);assert.match(readFileSync('src/conceptual3dRenderer.ts','utf8'),/scene\.overallWidth.*scene\.overallHeight/s) })
test('door glass panel и combined split са различими', () => { let state = doorState(); const id = state.fields[0]!.id; state = setDoorInfill(state, id, 'GLASS_TOP_PANEL_BOTTOM', .6); const nodes = buildDoorConceptualScene(state).nodes.filter(n => n.semanticSourceId === id); assert.ok(nodes.some(n => n.kind === 'GLASS')); assert.ok(nodes.some(n => n.kind === 'SOLID_PANEL')) })
test('combined door leaf има точно един opening label върху цялото крило', () => { let state=doorState(),id=state.fields[0]!.id;state=setDoorInfill(state,id,'GLASS_TOP_PANEL_BOTTOM',.55);state=setDoorOpening(state,id,'LEFT','INWARD');const labels=buildDoorConceptualScene(state).nodes.filter(node=>node.semanticSourceId===id&&node.openingLabel);assert.equal(labels.length,1);assert.equal(labels[0]?.kind,'SASH') })
test('две door leaves имат по един opening label', () => { let state=applyDoorTemplate(emptyDoorComposition(),'DEMO-DOOR-DOUBLE-GLAZED');for(const field of state.fields.filter(value=>value.role==='DOOR_LEAF'))state=setDoorOpening(state,field.id,field.id.endsWith('1')?'LEFT':'RIGHT','OUTWARD');const labels=buildDoorConceptualScene(state).nodes.filter(node=>node.openingLabel);assert.equal(labels.length,2);assert.equal(new Set(labels.map(node=>node.semanticSourceId)).size,2) })
test('fixed glazing няма opening label', () => { const state=applyDoorTemplate(emptyDoorComposition(),'DEMO-DOOR-SIDE-FIXED'),fixedIds=new Set(state.fields.filter(field=>field.role==='FIXED_GLAZING').map(field=>field.id));assert.equal(buildDoorConceptualScene(state).nodes.some(node=>fixedIds.has(node.semanticSourceId)&&node.openingLabel),false) })
test('multiple hinges и handle запазват semantic hardware IDs', () => { let state = doorState(), id = state.fields[0]!.id; state = setDoorOpening(state, id, 'LEFT', 'INWARD'); state = addDoorHardware(state, id, 'HINGE', () => 'hinge-a', .2); state = addDoorHardware(state, id, 'HINGE', () => 'hinge-b', .8); state = addDoorHardware(state, id, 'HANDLE', () => 'handle-a', .5); const scene = buildDoorConceptualScene(state); assert.deepEqual(scene.nodes.filter(n => n.kind === 'HINGE_MARKER').map(n => n.semanticSourceId), ['hinge-a', 'hinge-b']); assert.equal(scene.nodes.find(n => n.kind === 'HANDLE_MARKER')?.semanticSourceId, 'handle-a') })
test('window hardware and opening update scene directly from semantic state', () => { let state = selectComposerField(windowState(), 'field-1'); state = applyComposerItem(state, 'OPEN_LEFT', () => 'unused'); state = applyComposerItem(state, 'HINGE', () => 'window-hinge', .3); const scene = buildWindowConceptualScene(state); assert.equal(scene.nodes.find(n => n.semanticSourceId === 'field-1' && n.kind === 'SASH')?.openingLabel, 'Ляво'); assert.ok(scene.nodes.some(n => n.semanticSourceId === 'window-hinge')) })
test('DEMO depths са unitless normalized constants', () => { assert.ok(Object.values(DEMO_DEPTHS).every(value => value > 0 && value < 1)) })
test('projection е deterministic и реагира на yaw/pitch', () => { const point = { x: .2, y: .3, z: .1 }, front = projectConceptualPoint(point, presetView('FRONT'), 600, 400), side = projectConceptualPoint(point, presetView('RIGHT'), 600, 400); assert.deepEqual(front, projectConceptualPoint(point, presetView('FRONT'), 600, 400)); assert.notEqual(front.x, side.x) })
test('zoom clamp остава в safe range', () => { assert.equal(clampConceptualZoom(0), .35); assert.equal(clampConceptualZoom(10), 2.4) })
test('view presets и reset са deterministic', () => { assert.equal(presetView('FRONT').yaw, 0); assert.equal(presetView('BACK').yaw, Math.PI); assert.deepEqual(cameraKey({ ...CONCEPTUAL_3D_INITIAL_VIEW, yaw: 2 }, '0'), CONCEPTUAL_3D_INITIAL_VIEW) })
test('fit пази ориентацията и променя само view zoom/preset', () => { const value = { yaw: 1, pitch: .2, zoom: 2, preset: 'CUSTOM' as const }, fitted = fitConceptualView(value); assert.equal(fitted.yaw, 1); assert.equal(fitted.pitch, .2); assert.equal(fitted.zoom, .82) })
test('viewport fit използва width height и padding без X/Y разтягане', () => { const scene=buildDoorConceptualScene(doorState(),900,2000),view=fitSceneToViewport(scene,presetView('ISOMETRIC'),800,500,40);assert.equal(scene.bounds.width/scene.bounds.height,.45);assert.equal(sceneFitsViewport(scene,view,800,500,39),true);const narrower=fitSceneToViewport(scene,presetView('ISOMETRIC'),420,700,40);assert.notEqual(view.zoom,narrower.zoom) })
test('pointer lifecycle update и Escape restoration използват initial view', () => { const start = beginCameraDrag(7, 10, 20, CONCEPTUAL_3D_INITIAL_VIEW), moved = updateCameraDrag(start, 40, 50); assert.notEqual(moved.preview.yaw, start.initial.yaw); assert.deepEqual(moved.initial, CONCEPTUAL_3D_INITIAL_VIEW) })
test('pitch е clamp-нат при pointer drag', () => { const moved = updateCameraDrag(beginCameraDrag(1, 0, 0, CONCEPTUAL_3D_INITIAL_VIEW), 0, 10000); assert.ok(moved.preview.pitch <= 1.15) })
test('keyboard camera поддържа arrows zoom fit reset', () => { const view = CONCEPTUAL_3D_INITIAL_VIEW; assert.notEqual(cameraKey(view, 'ArrowLeft').yaw, view.yaw); assert.ok(cameraKey(view, '+').zoom > view.zoom); assert.equal(cameraKey(view, 'f').zoom, .82); assert.equal(cameraKey(view, '0').preset, 'ISOMETRIC') })
test('hit testing връща selectable semantic source', () => { const scene = buildDoorConceptualScene(doorState()), projected = projectScene(scene, presetView('FRONT'), 600, 500), target = projected.find(n => n.node.selectable)!; const center = target.polygon.reduce((p, n) => ({ x: p.x + n.x / 4, y: p.y + n.y / 4 }), { x: 0, y: 0 }); assert.ok(hitTestProjected(projected, center.x, center.y)?.semanticSourceId) })
test('camera state е отделен от semantic/review state', () => { const state = doorState(), snapshot = JSON.stringify(state); cameraKey(CONCEPTUAL_3D_INITIAL_VIEW, 'ArrowRight'); assert.equal(JSON.stringify(state), snapshot) })
test('всички camera presets пазят hardware IDs selection review и history-neutral semantic snapshot', () => { let state=doorState(),id=state.fields[0]!.id;state=setDoorOpening(state,id,'RIGHT','INWARD');state=addDoorHardware(state,id,'HINGE',()=> 'stable-hinge',.5);state=selectDoorField(state,id);const snapshot=JSON.stringify(state);for(const preset of ['FRONT','BACK','LEFT','RIGHT','ISOMETRIC'] as const)presetView(preset);assert.equal(JSON.stringify(state),snapshot);assert.ok(state.hardware.some(item=>item.id==='stable-hinge'));assert.equal(state.selectedFieldId,id) })
test('selection-only semantic action не reset-ва door review', () => { const state = { ...doorState(), conceptuallyReviewed: true as const }, next = selectDoorField(state, state.fields[0]!.id); assert.equal(next.conceptuallyReviewed, true) })
test('2D/3D switch е достъпен и 3D е disabled без template', () => { const windowSource = readFileSync('src/components/VisualTemplateComposer.tsx', 'utf8'), doorSource = readFileSync('src/components/DoorVisualComposer.tsx', 'utf8'); for (const source of [windowSource, doorSource]) { assert.match(source, /role="tablist"/); assert.match(source, /disabled={!state\.templateId}/); assert.match(source, /Conceptual3DPreview/) } })
test('renderer е HiDPI и ResizeObserver-aware без perpetual loop', () => { const source = readFileSync('src/components/Conceptual3DPreview.tsx', 'utf8'); assert.match(source, /devicePixelRatio/); assert.match(source, /ResizeObserver/); assert.match(source, /observer\.disconnect/); assert.match(source, /requestAnimationFrame/); assert.doesNotMatch(source, /requestAnimationFrame\([^)]*requestAnimationFrame/) })
test('canvas има pointer capture wheel keyboard и Escape', () => { const source = readFileSync('src/components/Conceptual3DPreview.tsx', 'utf8'); for (const token of ['setPointerCapture', 'releasePointerCapture', 'onPointerCancel', 'onWheel', "event.key === 'Escape'", 'tabIndex={0}']) assert.ok(source.includes(token)) })
test('accessibility fallback и Bulgarian instructions са налични', () => { const source = readFileSync('src/components/Conceptual3DPreview.tsx', 'utf8'); assert.match(source, /Достъпен списък на елементите/); assert.match(source, /Интерактивна концептуална 3D визуализация/); assert.match(source, /Мишка или докосване/) })
test('scene descriptor няма production/export/network capability', () => { const payload = JSON.stringify(buildDoorConceptualScene(doorState())); for (const forbidden of ['fetch', 'localStorage', 'operations', 'machineOutput', 'productionDepth', 'profileCrossSection']) assert.equal(payload.includes(forbidden), false) })
test('threshold е warning baseline без 3D profile node', () => { const threshold=buildDoorConceptualScene(doorState()).nodes.filter(node=>node.semanticSourceId==='door-threshold');assert.equal(threshold.length,1);assert.equal(threshold[0]?.kind,'THRESHOLD_WARNING') })
test('един hardware ID създава точно един selectable scene node', () => { let state=doorState(),id=state.fields[0]!.id;state=setDoorOpening(state,id,'LEFT','INWARD');state=addDoorHardware(state,id,'HINGE',()=> 'unique-hardware',.5);assert.equal(buildDoorConceptualScene(state).nodes.filter(node=>node.semanticSourceId==='unique-hardware'&&node.selectable).length,1) })
test('safety information е в normal flow и не покрива canvas', () => { const component=readFileSync('src/components/Conceptual3DPreview.tsx','utf8'),css=readFileSync('src/conceptual3d.css','utf8');assert.match(component,/conceptual-3d-safety-line/);assert.doesNotMatch(component,/conceptual-3d-overlay/);assert.doesNotMatch(css,/conceptual-3d-overlay|position:absolute/) })
test('safety flags на source compositions и scenes остават заключени', () => { for (const state of [windowState(), doorState(), buildWindowConceptualScene(windowState()), buildDoorConceptualScene(doorState())]) { assert.equal(state.sessionOnly, true); assert.equal(state.simulationOnly, true); assert.equal(state.machineReady, false); assert.equal(state.internalEvaluationOnly, true); assert.equal(state.productionApproved, false); assert.equal(state.geometryCreated, false); assert.equal(state.exportAvailable, false); assert.equal(state.dwgWriteAvailable, false); assert.equal(state.machineConnectivityAvailable, false) } })
test('WINDOW и DOOR suggestions остават category-specific без leakage', () => { assert.ok(getProductNameSuggestions('WINDOW').every(name => /прозорец/i.test(name))); assert.ok(getProductNameSuggestions('DOOR').every(name => /врата/i.test(name))); assert.equal(getProductSizeSuggestions('DOOR').some(item => item.id === '1400x1200'), false) })
test('clean WINDOW към DOOR transition премахва несъвместимия draft', () => { const configured = { ...createStructuredConfiguration('WINDOW'), productName: 'Стар прозорец', overallWidth: '1400', overallHeight: '1200', profileSystem: 'DEMO SYSTEM', frameProfileId: 'profile-demo-frame-01' }, next = changeStructuredCategory(configured, 'DOOR', sampleCatalogueProfiles); assert.equal(next.productCategory, 'DOOR'); assert.equal(next.productName, ''); assert.equal(next.overallWidth, ''); assert.equal(next.overallHeight, ''); assert.equal(next.profileSystem, ''); assert.equal(next.frameProfileId, ''); assert.equal(next.status, 'EMPTY') })
test('clean DOOR към WINDOW transition премахва несъвместимия draft', () => { const configured = { ...createStructuredConfiguration('DOOR'), productName: 'Стара врата', overallWidth: '900', overallHeight: '2000' }, next = changeStructuredCategory(configured, 'WINDOW', sampleCatalogueProfiles); assert.equal(next.productCategory, 'WINDOW'); assert.equal(next.productName, ''); assert.equal(next.overallWidth, ''); assert.equal(next.overallHeight, ''); assert.equal(next.thresholdStatus, 'NOT_APPLICABLE') })
test('повторен избор на същата категория пази съвместимия session state', () => { const configured = { ...createStructuredConfiguration('DOOR'), productName: 'Моя врата', overallWidth: '900', overallHeight: '2000' }; assert.equal(changeStructuredCategory(configured, 'DOOR', sampleCatalogueProfiles), configured) })
test('category route state остава explicit и не се извлича от име', () => { const standard = selectHybridCreationRoute(createHybridProductDesignerSession('category-test'), 'STANDARD'), door = selectHybridStandardCategory(standard, 'DOOR', sampleCatalogueProfiles); assert.equal(door.productCategory, 'DOOR'); assert.equal(door.configuration?.productCategory, 'DOOR'); assert.equal(door.configuration?.productName, '') })
test('main workspace отделя самостоятелния профил от category product context', () => { const app = readFileSync('src/App.tsx', 'utf8'), panel = readFileSync('src/components/ProfilePanel.tsx', 'utf8'); assert.match(app, /Продължи с изделието/); assert.match(panel, /Самостоятелен профил — това още не е изделието/); assert.match(app, /productComposerActive/) })
test('main actions четат explicit legacy category', () => { const app = readFileSync('src/App.tsx', 'utf8'); assert.match(app, /product\.productCategory === 'DOOR'.*Начертай нестандартна врата/s); assert.match(app, /product\.productCategory === 'WINDOW'.*Начертай нестандартен прозорец/s); assert.match(app, /hybridSession\.productCategory.*Продължи с изделието/s) })
test('примерният размер изисква отделно човешко действие', () => { const wizard = readFileSync('src/components/StructuredConfigurationWizard.tsx', 'utf8'); assert.match(wizard, /Приложи примерни размери/); assert.match(wizard, /onClick={applySize}/); assert.doesNotMatch(wizard, /onChange=\{\(event\) => selectSize/) })
test('необичайната door пропорция е само conceptual warning', () => { assert.equal(hasUnusualDemonstrationalDoorProportion(1400,1200),true); assert.equal(hasUnusualDemonstrationalDoorProportion(900,2000),false); assert.equal(hasUnusualDemonstrationalDoorProportion('',2000),false); assert.match(readFileSync('src/components/DoorVisualComposer.tsx','utf8'),/Необичайна пропорция за врата/) })
test('всички REF templates имат explicit stable product category', () => { assert.equal(Object.keys(PRODUCT_CATEGORY_BY_TEMPLATE).length,17); for(const template of productTemplates) assert.equal(template.productCategory,PRODUCT_CATEGORY_BY_TEMPLATE[template.id as keyof typeof PRODUCT_CATEGORY_BY_TEMPLATE]) })
test('legacy window default към door изчиства стария DEMO размер', () => { const result=selectLegacyProductTemplate(defaultProduct,getProductTemplate('REF-15')); assert.equal(result.categoryChanged,true);assert.equal(result.product.productCategory,'DOOR');assert.equal(result.product.width,0);assert.equal(result.product.height,0);assert.equal(result.product.dimensionSource,'EMPTY') })
test('legacy template transaction затваря preview и clear-ва selected component', () => { const result=selectLegacyProductTemplate(defaultProduct,getProductTemplate('REF-15'));assert.equal(result.closePreview,true);assert.equal(result.clearSelectedComponent,true) })
test('door draft без размери няма derived component list', () => { const product=selectLegacyProductTemplate(defaultProduct,getProductTemplate('REF-15')).product;assert.equal(hasValidLegacyProductDimensions(product),false);assert.deepEqual(calculateProductComponents(product,'DEMO'),[]) })
test('door DEMO размерите се прилагат само чрез explicit pure action', () => { const empty=selectLegacyProductTemplate(defaultProduct,getProductTemplate('REF-15')).product;assert.equal(empty.dimensionSource,'EMPTY');const applied=applyLegacyDemoDimensions(empty,getProductTemplate('REF-15'));assert.equal(applied.dimensionSource,'DOOR_DEMO_PRESET');assert.equal(applied.width,900);assert.equal(applied.height,2100) })
test('window DEMO preset не се пренася към door template', () => { const windowPreset=applyLegacyDemoDimensions(defaultProduct,getProductTemplate('REF-01')),door=selectLegacyProductTemplate(windowPreset,getProductTemplate('REF-14')).product;assert.equal(windowPreset.dimensionSource,'WINDOW_DEMO_PRESET');assert.equal(door.dimensionSource,'EMPTY');assert.equal(door.width,0) })
test('ръчен широк door размер остава USER_ENTERED и показва warning без auto-fix', () => { const empty=selectLegacyProductTemplate(defaultProduct,getProductTemplate('REF-15')).product,manual={...empty,width:1400,height:1200,dimensionSource:'USER_ENTERED' as const};assert.equal(manual.width,1400);assert.equal(manual.height,1200);assert.equal(hasUnusualLegacyDoorProportion(manual),true) })
test('door и window preview titles са category-aware', () => { const source=readFileSync('src/components/ProductPreview.tsx','utf8');assert.match(source,/Визуализация на вратата/);assert.match(source,/Визуализация на прозореца/);assert.match(source,/product\.productCategory/) })
test('legacy product UI има placeholder и explicit DEMO action', () => { const source=readFileSync('src/components/ProductSection.tsx','utf8');assert.match(source,/Размери:<\/b>.*Не са зададени/s);assert.match(source,/Приложи примерни размери/);assert.match(source,/Няма визуализация/);assert.match(source,/disabled={!validDimensions}/) })
test('profile dimensions са независими от product overall dimensions', () => { const profile={...defaultProfile,length:777,width:61,height:41},product={...defaultProduct,width:1555,height:1333,dimensionSource:'USER_ENTERED' as const};selectLegacyProductTemplate(product,getProductTemplate('REF-02'));assert.deepEqual(profile,{...defaultProfile,length:777,width:61,height:41});assert.equal(product.width,1555);assert.equal(product.height,1333) })
test('same-category template transition пази ръчно въведените размери', () => { const manual={...defaultProduct,width:1400,height:1200,dimensionSource:'USER_ENTERED' as const},next=selectLegacyProductTemplate(manual,getProductTemplate('REF-04')).product;assert.equal(next.width,1400);assert.equal(next.height,1200);assert.equal(next.dimensionSource,'USER_ENTERED') })
test('combined template използва неутрална explicit category', () => { for(const id of ['REF-12','REF-13'])assert.equal(getProductTemplate(id).productCategory,'COMBINED') })
