import assert from 'node:assert/strict'
import test from 'node:test'
import { changeStructuredCategory, compatibleProfiles, confirmStructuredConfiguration, createHybridProductDesignerSession, createStructuredConfiguration, deriveActiveProfileSystems, maximumAccessibleConfigurationStep, moveStructuredConfigurationStep, PRODUCT_NAME_SUGGESTIONS, PRODUCT_SIZE_PRESETS, reconcileStructuredConfiguration, selectHybridCreationRoute, selectHybridStandardCategory, updateStructuredConfiguration, validateStructuredConfiguration } from '../src/hybridProductDesigner'
import { sampleCatalogueProfiles } from '../src/profileCatalogueData'
import type { CatalogueProfile } from '../src/profileCatalogueTypes'

const profiles = sampleCatalogueProfiles.map((profile) => ({ ...profile }))
const configuredWindow = () => { let value = createStructuredConfiguration('WINDOW'); value = updateStructuredConfiguration(value, { productName: 'Тестов прозорец', overallWidth: '1400', overallHeight: '1200', profileSystem: 'DEMO SYSTEM' }, profiles); value = updateStructuredConfiguration(value, { frameProfileId: 'profile-demo-frame-01' }, profiles); return value }

test('1. празната конфигурация започва и остава със статус EMPTY при catalog reconciliation', () => { const value = createStructuredConfiguration('WINDOW'); assert.equal(value.status, 'EMPTY'); assert.equal(reconcileStructuredConfiguration(value, profiles).status, 'EMPTY') })
test('2. прозорец и врата се инициализират без геометрия', () => { for (const category of ['WINDOW', 'DOOR'] as const) { const session = selectHybridStandardCategory(selectHybridCreationRoute(createHybridProductDesignerSession(), 'STANDARD'), category, profiles); assert.equal(session.configuration?.productCategory, category); assert.equal(session.geometryEntityCount, 0); assert.equal(session.geometryCreated, false) } })
test('3. валидни положителни размери се приемат', () => assert.equal(validateStructuredConfiguration(configuredWindow(), profiles).some((error) => error.includes('ширина') || error.includes('височина')), false))
test('4. невалидните числови размери се отхвърлят', () => { for (const value of ['', '0', '-1', 'NaN', 'Infinity']) { const configuration = updateStructuredConfiguration(createStructuredConfiguration('WINDOW'), { overallWidth: value, overallHeight: value }, profiles); assert.ok(validateStructuredConfiguration(configuration, profiles).length >= 2) } })
test('5. системите се извеждат само от неархивирани профили', () => { const augmented: CatalogueProfile[] = [...profiles, { ...profiles[0]!, id: 'archived', system: 'ARCHIVED SYSTEM', status: 'ARCHIVED' }]; assert.deepEqual(deriveActiveProfileSystems(augmented), ['DEMO SYSTEM']) })
test('6. профилите се филтрират по система и роля', () => { assert.deepEqual(compatibleProfiles(profiles, 'DEMO SYSTEM', 'SASH').map(({ id }) => id), ['profile-demo-sash-01']); assert.equal(compatibleProfiles(profiles, 'OTHER', 'SASH').length, 0) })
test('7. архивирани и несъвместими профили не могат да останат валидни', () => { const value = { ...configuredWindow(), frameProfileId: 'profile-demo-sash-01' }; assert.ok(validateStructuredConfiguration(value, profiles).some((error) => error.includes('каса'))) })
test('8. смяната на система изчиства несъвместимите профили', () => { const other = profiles.map((profile) => ({ ...profile, id: `other-${profile.id}`, system: 'OTHER' })); const changed = updateStructuredConfiguration(configuredWindow(), { profileSystem: 'OTHER' }, [...profiles, ...other]); assert.equal(changed.frameProfileId, '') })
test('9. няма тих автоматичен избор на профил', () => { const changed = updateStructuredConfiguration(createStructuredConfiguration('WINDOW'), { profileSystem: 'DEMO SYSTEM' }, profiles); assert.equal(changed.frameProfileId, ''); assert.equal(changed.sashProfileId, '') })
test('10. редакция след потвърждение връща NEEDS_REVIEW', () => { let value = updateStructuredConfiguration({ ...configuredWindow(), wizardStep: 5 }, { humanReviewChecked: true }, profiles); value = confirmStructuredConfiguration(value, profiles); assert.equal(value.status, 'HUMAN_CONFIRMED'); assert.equal(updateStructuredConfiguration(value, { productName: 'Промяна' }, profiles).status, 'NEEDS_REVIEW') })
test('11. прозорецът изисква размери, система, каса и checkbox', () => { assert.notEqual(confirmStructuredConfiguration(configuredWindow(), profiles).status, 'HUMAN_CONFIRMED'); const checked = updateStructuredConfiguration({ ...configuredWindow(), wizardStep: 5 }, { humanReviewChecked: true }, profiles); assert.equal(confirmStructuredConfiguration(checked, profiles).status, 'HUMAN_CONFIRMED') })
test('12. зададените optional IDs трябва да са съвместими', () => { const value = { ...configuredWindow(), sashProfileId: 'profile-demo-mullion-01' }; assert.ok(validateStructuredConfiguration(value, profiles).some((error) => error.includes('крило'))) })
test('13. прагът за врата е неразрешен', () => assert.equal(createStructuredConfiguration('DOOR').thresholdStatus, 'UNRESOLVED'))
test('14. потвърждението на врата остава блокирано', () => { let door = changeStructuredCategory(configuredWindow(), 'DOOR', profiles); door = updateStructuredConfiguration(door, { humanReviewChecked: true }, profiles); assert.notEqual(confirmStructuredConfiguration(door, profiles).status, 'HUMAN_CONFIRMED') })
test('15. прагът за прозорец не е приложим', () => assert.equal(createStructuredConfiguration('WINDOW').thresholdStatus, 'NOT_APPLICABLE'))
test('16. отварянето на каталога не мутира семантичната конфигурация', () => { const value = configuredWindow(), snapshot = JSON.stringify(value); assert.equal(JSON.stringify(value), snapshot) })
test('17. каталожна промяна изчиства само невалидните selections', () => { let value = updateStructuredConfiguration(configuredWindow(), { sashProfileId: 'profile-demo-sash-01', mullionProfileId: 'profile-demo-mullion-01' }, profiles); const archived = profiles.map((profile) => profile.id === value.sashProfileId ? { ...profile, status: 'ARCHIVED' as const } : profile); value = reconcileStructuredConfiguration(value, archived); assert.equal(value.frameProfileId, 'profile-demo-frame-01'); assert.equal(value.sashProfileId, ''); assert.equal(value.mullionProfileId, 'profile-demo-mullion-01') })
test('18. затварянето и новото отваряне създават нова празна session state', () => { const first = selectHybridStandardCategory(selectHybridCreationRoute(createHybridProductDesignerSession('first'), 'STANDARD'), 'WINDOW', profiles); const reopened = createHybridProductDesignerSession('second'); assert.ok(first.configuration); assert.equal(reopened.configuration, null); assert.notEqual(first.id, reopened.id) })
test('19. всички safety flags остават заключени', () => { const session = createHybridProductDesignerSession(); assert.deepEqual({ sessionOnly: session.sessionOnly, simulationOnly: session.simulationOnly, machineReady: session.machineReady, internalEvaluationOnly: session.internalEvaluationOnly, productionApproved: session.productionApproved, sourceImmutable: session.sourceImmutable, geometryCreated: session.geometryCreated, exportAvailable: session.exportAvailable, dwgWriteAvailable: session.dwgWriteAvailable, machineConnectivityAvailable: session.machineConnectivityAvailable }, { sessionOnly: true, simulationOnly: true, machineReady: false, internalEvaluationOnly: true, productionApproved: false, sourceImmutable: true, geometryCreated: false, exportAvailable: false, dwgWriteAvailable: false, machineConnectivityAvailable: false }) })
test('20. моделът не съдържа geometry, export, persistence, DWG-write или machine capability', () => { const value = JSON.stringify(configuredWindow()); for (const forbidden of ['localStorage', 'indexedDB', 'geometryEntities', 'dwgWriter', 'machineFormat', 'operations', 'quantities']) assert.equal(value.includes(forbidden), false); assert.equal(configuredWindow().geometryCreated, false); assert.equal(configuredWindow().exportAvailable, false); assert.equal(configuredWindow().machineReady, false) })
test('21. wizard започва от стъпка 1 без автоматично избрана система или профили', () => { const value = createStructuredConfiguration('WINDOW'); assert.equal(value.wizardStep, 1); assert.equal(value.profileSystem, ''); assert.equal(value.frameProfileId, ''); assert.equal(value.sashProfileId, ''); assert.equal(value.mullionProfileId, '') })
test('22. невалидните размери блокират стъпка 3', () => { const value = moveStructuredConfigurationStep(createStructuredConfiguration('WINDOW'), 3, profiles); assert.equal(value.wizardStep, 1); assert.equal(maximumAccessibleConfigurationStep(value, profiles), 2) })
test('23. липсваща система блокира стъпка 4', () => { const dimensions = updateStructuredConfiguration(createStructuredConfiguration('WINDOW'), { productName: 'Тестов прозорец', overallWidth: '1000', overallHeight: '1000' }, profiles); assert.equal(maximumAccessibleConfigurationStep(dimensions, profiles), 3); assert.equal(moveStructuredConfigurationStep(dimensions, 4, profiles).wizardStep, 1) })
test('24. липсваща каса блокира стъпка 5', () => { let value = updateStructuredConfiguration(createStructuredConfiguration('WINDOW'), { productName: 'Тестов прозорец', overallWidth: '1000', overallHeight: '1000' }, profiles); value = updateStructuredConfiguration(value, { profileSystem: 'DEMO SYSTEM' }, profiles); assert.equal(maximumAccessibleConfigurationStep(value, profiles), 4); assert.notEqual(moveStructuredConfigurationStep(value, 5, profiles).wizardStep, 5) })
test('25. Назад пази съвместимите стойности', () => { const value = { ...configuredWindow(), wizardStep: 5 as const }, back = moveStructuredConfigurationStep(value, 2, profiles); assert.equal(back.wizardStep, 2); assert.equal(back.overallWidth, '1400'); assert.equal(back.profileSystem, 'DEMO SYSTEM'); assert.equal(back.frameProfileId, 'profile-demo-frame-01') })
test('26. завършените стъпки могат да бъдат отворени отново', () => { const value = { ...configuredWindow(), wizardStep: 5 as const }; for (const step of [1, 2, 3, 4, 5] as const) assert.equal(moveStructuredConfigurationStep(value, step, profiles).wizardStep, step) })
test('27. потвърждението е разрешено само в стъпка 5', () => { let value = updateStructuredConfiguration(configuredWindow(), { humanReviewChecked: true }, profiles); assert.notEqual(confirmStructuredConfiguration(value, profiles).status, 'HUMAN_CONFIRMED'); value = { ...value, wizardStep: 5 }; assert.equal(confirmStructuredConfiguration(value, profiles).status, 'HUMAN_CONFIRMED') })
test('28. невалидна стъпка Размери държи Продължи disabled', () => { const value = { ...createStructuredConfiguration('WINDOW'), wizardStep: 2 as const }; assert.equal(maximumAccessibleConfigurationStep(value, profiles) < 3, true) })
test('29. валидна стъпка Размери разрешава Продължи', () => { const value = updateStructuredConfiguration(createStructuredConfiguration('WINDOW'), { productName: 'Тестов прозорец', overallWidth: '1200', overallHeight: '1000' }, profiles); assert.equal(maximumAccessibleConfigurationStep(value, profiles) >= 3, true) })
test('30. предложенията за име нямат автоматичен избор и остават ръчно редактируеми', () => { const empty = createStructuredConfiguration('WINDOW'); assert.equal(empty.productName, ''); assert.equal(PRODUCT_NAME_SUGGESTIONS.length, 6); const suggested = updateStructuredConfiguration(empty, { productName: PRODUCT_NAME_SUGGESTIONS[1]! }, profiles), edited = updateStructuredConfiguration(suggested, { productName: 'Мое име' }, profiles); assert.equal(edited.productName, 'Мое име') })
test('31. примерният размер няма автоматичен избор и попълнените стойности остават редактируеми', () => { const empty = createStructuredConfiguration('WINDOW'), preset = PRODUCT_SIZE_PRESETS.find(({ id }) => id === '1400x1200')!; assert.equal(empty.overallWidth, ''); assert.equal(empty.overallHeight, ''); const suggested = updateStructuredConfiguration(empty, { overallWidth: preset.width, overallHeight: preset.height }, profiles), edited = updateStructuredConfiguration(suggested, { overallWidth: '1410' }, profiles); assert.equal(edited.overallWidth, '1410'); assert.equal(edited.overallHeight, '1200') })
