import assert from 'node:assert/strict'
import test from 'node:test'
import { calculateDwgBounds, fitDwgView, zoomDwgView } from '../src/dwgBounds'
import { applyDwgTransform, assertSafeBlockGraph, normalizeDwgDatabase } from '../src/dwgEntityNormalization'
import { extractDwgLayers, toggleDwgLayer } from '../src/dwgLayerState'
import { canvasPointToDwgWorld, detectDwgSections, DWG_SECTION_RULES, hitTestDwgSection, isDwgSectionClick, resolveDwgFocusBounds, resolveDwgSectionSelection } from '../src/dwgSectionDetection'
import { DWG_TEXT_LOD_MINIMUM_PIXELS, isDwgTextVisibleAtScale, normalizeDwgDisplayText } from '../src/dwgTextNormalization'
import { canvasPixelsToDwgLocal, layoutDwgText, type DwgTextLayoutInput } from '../src/dwgTextLayout'
import { DWG_SAFETY_FLAGS, type DwgDrawableEntity } from '../src/dwgViewerTypes'
import { deriveDwgApproximateTextAssignments, detectDwgVisualFields, resolveDwgTextDisplayMode } from '../src/dwgVisualFieldDetection'
import { applyDwgManualAssignment, cancelDwgCorrectionStep, clearDwgManualAssignments, hitTestDwgVisualField, hitTestVisibleDwgText, initialDwgCorrectionState, mergeDwgDisplayAssignments, removeDwgManualAssignment, resolveDwgManualDisplayAssignments, selectDwgCorrectionText, startDwgCorrection, undoDwgManualAssignment } from '../src/dwgManualTextCorrection'

const base = { handle: 'A', layer: 'TEST' }
const entities: DwgDrawableEntity[] = [
  { ...base, type: 'LINE', start: { x: 0, y: 0 }, end: { x: 10, y: 20 } },
  { ...base, type: 'POLYLINE', points: [{ x: -5, y: 2 }, { x: 4, y: 30 }], closed: false },
  { ...base, type: 'CIRCLE', center: { x: 20, y: 20 }, radius: 5 },
  { ...base, type: 'ARC', center: { x: 4, y: 4 }, radius: 3, startAngle: 0, endAngle: Math.PI },
]
const rectangleLines = (prefix: string, minX: number, minY: number, maxX: number, maxY: number, layer = 'FRAME'): DwgDrawableEntity[] => [
  { type: 'LINE', handle: `${prefix}-T`, layer, start: { x: minX, y: maxY }, end: { x: maxX, y: maxY } },
  { type: 'LINE', handle: `${prefix}-B`, layer, start: { x: minX, y: minY }, end: { x: maxX, y: minY } },
  { type: 'LINE', handle: `${prefix}-L`, layer, start: { x: minX, y: minY }, end: { x: minX, y: maxY } },
  { type: 'LINE', handle: `${prefix}-R`, layer, start: { x: maxX, y: minY }, end: { x: maxX, y: maxY } },
]
const contentCircles = (prefix: string, minX: number, minY: number): DwgDrawableEntity[] => Array.from({ length: 8 }, (_, index) => ({ type: 'CIRCLE' as const, handle: `${prefix}-${index}`, layer: 'CONTENT', center: { x: minX + 20 + index * 5, y: minY + 20 }, radius: 1 }))
const syntheticDrawingBounds = { minX: 0, minY: 0, maxX: 1000, maxY: 1000 }
const syntheticSectionsEntities = [
  ...rectangleLines('A', 50, 600, 450, 900), ...contentCircles('AC', 50, 600),
  ...rectangleLines('A-CELL', 100, 650, 200, 750),
  ...rectangleLines('B', 550, 100, 950, 400), ...contentCircles('BC', 550, 100),
]

test('LINE/POLYLINE/CIRCLE/ARC bounds са детерминистични', () => assert.deepEqual(calculateDwgBounds(entities), { minX: -5, minY: 0, maxX: 25, maxY: 30 }))
test('block affine transform се прилага безопасно', () => assert.deepEqual(applyDwgTransform({ x: 2, y: 3 }, { a: 2, b: 0, c: 0, d: 3, e: 10, f: -5 }), { x: 14, y: 4 }))
test('INSERT block се разгъва с трансформация и запазен source handle', () => { const result = normalizeDwgDatabase({ entities: [{ type: 'INSERT', handle: 'I', layer: '0', name: 'B', insertionPoint: { x: 10, y: 20 }, xScale: 2, yScale: 2, rotation: 0 }], tables: { BLOCK_RECORD: { entries: [{ name: 'B', basePoint: { x: 0, y: 0 }, entities: [{ type: 'LINE', handle: 'L', layer: 'B', startPoint: { x: 1, y: 1 }, endPoint: { x: 2, y: 3 } }] }] } } }); assert.deepEqual(result.entities[0], { type: 'LINE', handle: 'L', layer: 'B', start: { x: 12, y: 22 }, end: { x: 14, y: 26 } }) })
test('recursive blocks се отхвърлят', () => assert.throws(() => assertSafeBlockGraph({ A: ['B'], B: ['A'] }), /RECURSIVE_BLOCK/))
test('прекомерна block дълбочина се отхвърля', () => assert.throws(() => assertSafeBlockGraph({ A: ['B'], B: ['C'], C: [] }, 1), /LIMIT_BLOCK_DEPTH/))
test('прекомерният entity count се отхвърля', () => assert.throws(() => normalizeDwgDatabase({ entities: [{ type: 'LINE' }, { type: 'LINE' }] }, { maximumEntities: 1 }), /LIMIT_ENTITIES/))
test('NaN/Infinity координати не се приемат като geometry', () => { const result = normalizeDwgDatabase({ entities: [{ type: 'LINE', handle: '1', layer: '0', startPoint: { x: NaN, y: 0 }, endPoint: { x: Infinity, y: 1 } }] }); assert.equal(result.entities.length, 0); assert.equal(result.unsupportedCounts.INVALID_NUMERIC, 1) })
test('неподдържан entity се отчита явно', () => { const result = normalizeDwgDatabase({ entities: [{ type: 'HATCH', handle: '2', layer: 'A' }] }); assert.equal(result.unsupportedCounts.HATCH, 1); assert.match(result.warnings[0]?.message ?? '', /HATCH/) })
test('source font ресурсите се отчитат като локален fallback', () => { const result = normalizeDwgDatabase({ entities: [], tables: { STYLE: { entries: [{ font: 'example.shx' }] } } }); assert.equal(result.warnings[0]?.code, 'MISSING_FONT') })
test('единичен Unicode escape се декодира', () => assert.equal(normalizeDwgDisplayText('Code \\U+0410').displayText, 'Code А'))
test('последователни кирилски Unicode escapes се декодират', () => assert.equal(normalizeDwgDisplayText('\\U+0410\\U+0411\\U+0412').displayText, 'АБВ'))
test('нормален текст и Unicode evidence се запазват отделно', () => { const rawText = 'Ref \\U+0410-1'; const result = normalizeDwgDisplayText(rawText); assert.equal(result.rawText, rawText); assert.equal(result.displayText, 'Ref А-1'); assert.equal(result.hadUnicodeEscapes, true) })
test('MTEXT paragraph създава няколко реда', () => assert.equal(normalizeDwgDisplayText('Ред 1\\PРед 2').displayText, 'Ред 1\nРед 2'))
test('escaped backslash и braces остават четими', () => assert.equal(normalizeDwgDisplayText('A\\\\B \\{C\\} {D}').displayText, 'A\\B {C} D'))
test('завършени display formatting controls се премахват безопасно', () => { const result = normalizeDwgDisplayText('\\A1;\\C3;\\FArial;\\H2x;\\Q0;\\T1;\\W0.8;Текст'); assert.equal(result.displayText, 'Текст'); assert.equal(result.hadFormatting, true); assert.equal(result.warnings.length, 0); assert.deepEqual(result.runs.map(({ text, heightScale, widthScale }) => ({ text, heightScale, widthScale })), [{ text: 'Текст', heightScale: 2, widthScale: 0.8 }]) })
test('decoder lowercase font и paragraph controls се премахват само до semicolon', () => { const result = normalizeDwgDisplayText('\\fArial;\\pql;Текст'); assert.equal(result.displayText, 'Текст'); assert.deepEqual(result.warnings, []) })
test('stacked fraction става четим plain text', () => assert.equal(normalizeDwgDisplayText('Размер \\S1#2;').displayText, 'Размер 1/2'))
test('malformed и unknown controls запазват evidence и warning', () => { const malformed = normalizeDwgDisplayText('A\\H2x'); assert.equal(malformed.displayText, 'A\\H2x'); assert.ok(malformed.warnings.length); const unknown = normalizeDwgDisplayText('B\\Zvalue'); assert.equal(unknown.displayText, 'B\\Zvalue'); assert.ok(unknown.warnings.length) })
test('text mapping пази позиция, размер, rotation и alignment', () => { const result = normalizeDwgDatabase({ entities: [{ type: 'TEXT', handle: 'T1', layer: 'TXT', text: '\\U+0410', startPoint: { x: 2, y: 3 }, textHeight: 4, rotation: 0.5, xScale: 0.8, halign: 2, valign: 3 }] }); const textEntity = result.entities[0]; assert.equal(textEntity?.type, 'TEXT'); if (textEntity?.type !== 'TEXT') return; assert.deepEqual(textEntity.position, { x: 2, y: 3 }); assert.equal(textEntity.rawText, '\\U+0410'); assert.equal(textEntity.displayText, 'А'); assert.equal(textEntity.height, 4); assert.equal(textEntity.rotation, 0.5); assert.equal(textEntity.widthFactor, 0.8); assert.equal(textEntity.horizontalAlignment, 2); assert.equal(textEntity.verticalAlignment, 3) })
test('decoder visibility false пропуска text, true го запазва', () => { const result = normalizeDwgDatabase({ entities: [{ type: 'TEXT', handle: 'V', layer: 'TXT', text: 'V', startPoint: { x: 0, y: 0 }, textHeight: 1, isVisible: true }, { type: 'TEXT', handle: 'H', layer: 'TXT', text: 'H', startPoint: { x: 1, y: 1 }, textHeight: 1, isVisible: false }] }); assert.equal(result.entities.length, 1); assert.equal(result.entities[0]?.handle, 'V') })
test('text LOD е скрит под прага и видим над него', () => { assert.equal(isDwgTextVisibleAtScale(1, DWG_TEXT_LOD_MINIMUM_PIXELS - 0.01), false); assert.equal(isDwgTextVisibleAtScale(1, DWG_TEXT_LOD_MINIMUM_PIXELS), true) })
test('explicit show/hide override работи независимо от LOD', () => assert.equal(isDwgTextVisibleAtScale(100, 100, false), false))
test('Model е renderable, а Layout metadata остава disabled', () => { const result = normalizeDwgDatabase({ objects: { LAYOUT: [{ handle: 'L1', layoutName: 'Layout1' }] } }); assert.deepEqual(result.layouts.map(({ name, renderable }) => ({ name, renderable })), [{ name: 'Model', renderable: true }, { name: 'Layout1', renderable: false }]); assert.match(result.layouts[1]?.unsupportedReason ?? '', /Paper Space/) })
test('липса на layout metadata не поврежда Model viewer', () => { const result = normalizeDwgDatabase({}); assert.equal(result.layouts.length, 1); assert.equal(result.layouts[0]?.id, 'MODEL'); assert.equal(result.layouts[0]?.renderable, true) })
test('отделни външни line-loop рамки се откриват като секции', () => { const sections = detectDwgSections(syntheticSectionsEntities, syntheticDrawingBounds); assert.equal(sections.length, 2); assert.ok(sections.every((section) => section.detectionMethod === 'AXIS_ALIGNED_LINE_LOOP')) })
test('вложена table cell рамка не става отделна секция', () => { const sections = detectDwgSections(syntheticSectionsEntities, syntheticDrawingBounds); assert.equal(sections.some((section) => section.bounds.minX === 100), false) })
test('малки и невалидни bounds се отхвърлят', () => { const small = [...rectangleLines('SMALL', 10, 10, 40, 40), ...contentCircles('SC', 10, 10)]; assert.deepEqual(detectDwgSections(small, syntheticDrawingBounds), []); assert.deepEqual(detectDwgSections(small, { minX: 0, minY: 0, maxX: Infinity, maxY: 1 }), []) })
test('duplicate bounds се deduplicate-ват', () => { const duplicated = [...rectangleLines('D1', 50, 600, 450, 900), ...rectangleLines('D2', 50, 600, 450, 900), ...contentCircles('DC', 50, 600)]; assert.equal(detectDwgSections(duplicated, syntheticDrawingBounds).length, 1) })
test('section IDs и ranking са детерминистични', () => { const first = detectDwgSections(syntheticSectionsEntities, syntheticDrawingBounds), second = detectDwgSections(syntheticSectionsEntities, syntheticDrawingBounds); assert.deepEqual(first, second); assert.deepEqual(first.map((section) => section.sectionId), ['model-section-001', 'model-section-002']) })
test('world-coordinate hit test предпочита доказаната външна секция', () => { const sections = detectDwgSections(syntheticSectionsEntities, syntheticDrawingBounds); assert.equal(hitTestDwgSection(sections, { x: 150, y: 700 })?.sectionId, 'model-section-001'); assert.equal(hitTestDwgSection(sections, { x: 500, y: 500 }), null) })
test('canvas coordinate mapping следва активния view transform', () => assert.deepEqual(canvasPointToDwgWorld({ x: 30, y: 50 }, { scale: 2, offsetX: 10, offsetY: 90 }), { x: 10, y: 20 }))
test('click и drag се различават с централизирания праг', () => { assert.equal(isDwgSectionClick({ x: 0, y: 0 }, { x: 3, y: 4 }), true); assert.equal(isDwgSectionClick({ x: 0, y: 0 }, { x: DWG_SECTION_RULES.clickMovementPixels + 1, y: 0 }), false) })
test('click извън секция не предоставя нов focus target', () => assert.equal(hitTestDwgSection(detectDwgSections(syntheticSectionsEntities, syntheticDrawingBounds), { x: 500, y: 500 }), null))
test('section fit пази aspect ratio и padding при resize', () => { const section = detectDwgSections(syntheticSectionsEntities, syntheticDrawingBounds)[0]!; const small = fitDwgView(section.bounds, 500, 300, DWG_SECTION_RULES.fitPaddingPixels), large = fitDwgView(section.bounds, 1000, 600, DWG_SECTION_RULES.fitPaddingPixels); assert.ok(small.scale > 0); assert.ok(large.scale > small.scale); assert.equal((section.bounds.maxX - section.bounds.minX) * small.scale <= 500 - DWG_SECTION_RULES.fitPaddingPixels * 2, true) })
test('reset използва active section bounds, whole return и Escape използват Model bounds', () => { const sections = detectDwgSections(syntheticSectionsEntities, syntheticDrawingBounds), active = sections[0]!; assert.deepEqual(resolveDwgFocusBounds(syntheticDrawingBounds, sections, active.sectionId), active.bounds); assert.deepEqual(resolveDwgFocusBounds(syntheticDrawingBounds, sections, null), syntheticDrawingBounds) })
test('clear/reload премахва stale section selection', () => { const sections = detectDwgSections(syntheticSectionsEntities, syntheticDrawingBounds); assert.equal(resolveDwgSectionSelection(sections, 'missing-section'), null); assert.equal(resolveDwgSectionSelection([], sections[0]!.sectionId), null) })
test('pan/zoom след section fit не се презаписват от section resolver', () => { const sections = detectDwgSections(syntheticSectionsEntities, syntheticDrawingBounds), bounds = resolveDwgFocusBounds(syntheticDrawingBounds, sections, sections[0]!.sectionId), fit = fitDwgView(bounds, 500, 300, DWG_SECTION_RULES.fitPaddingPixels), zoomed = zoomDwgView(fit, 1.5, 250, 150); assert.ok(zoomed.scale > fit.scale); assert.deepEqual(resolveDwgFocusBounds(syntheticDrawingBounds, sections, sections[0]!.sectionId), bounds) })
test('section fit scale преоценява text LOD', () => { const section = detectDwgSections(syntheticSectionsEntities, syntheticDrawingBounds)[0]!, whole = fitDwgView(syntheticDrawingBounds, 500, 300), focused = fitDwgView(section.bounds, 500, 300, DWG_SECTION_RULES.fitPaddingPixels); assert.equal(isDwgTextVisibleAtScale(4, whole.scale), false); assert.equal(isDwgTextVisibleAtScale(4, focused.scale), true) })
test('section evidence е navigation-only и safety flags са заключени', () => { const section = detectDwgSections(syntheticSectionsEntities, syntheticDrawingBounds)[0]!; assert.equal(section.sourceEntities.length, 4); assert.deepEqual({ simulationOnly: section.simulationOnly, machineReady: section.machineReady, internalEvaluationOnly: section.internalEvaluationOnly }, { simulationOnly: true, machineReady: false, internalEvaluationOnly: true }) })
const baseLayoutInput: DwgTextLayoutInput = { textKind: 'MTEXT', displayText: '', referenceWidth: 50, textHeight: 10, widthFactor: 1, attachmentPoint: 1, horizontalAlignment: 0, verticalAlignment: 0, lineSpacingFactor: 1, lineSpacingStyle: 1 }
const measureFive = (text: string) => text.length * 5
test('MTEXT с finite source width се wrap-ва по думи', () => { const result = layoutDwgText({ ...baseLayoutInput, displayText: 'едно две три четири', referenceWidth: 45 }, measureFive); assert.deepEqual(result.lines.map((line) => line.text), ['едно две', 'три', 'четири']); assert.equal(result.usedSourceWidth, true) })
test('explicit paragraph break остава задължителен', () => assert.deepEqual(layoutDwgText({ ...baseLayoutInput, displayText: 'първи\nвтори' }, measureFive).lines.map((line) => line.text), ['първи', 'втори']))
test('дълга дума използва character fallback без загуба', () => { const word = 'abcdefghijkl'; const lines = layoutDwgText({ ...baseLayoutInput, displayText: word, referenceWidth: 20 }, measureFive).lines.map((line) => line.text); assert.equal(lines.join(''), word); assert.ok(lines.every((line) => measureFive(line) <= 20)) })
test('MTEXT без валидна width не получава измислен container', () => { const result = layoutDwgText({ ...baseLayoutInput, displayText: 'един дълъг ред', referenceWidth: null }, measureFive); assert.deepEqual(result.lines.map((line) => line.text), ['един дълъг ред']); assert.equal(result.usedSourceWidth, false) })
test('дълъг MTEXT без source width създава видимо limitation предупреждение', () => { const result = normalizeDwgDatabase({ entities: [{ type: 'MTEXT', handle: 'NW', layer: 'TXT', text: 'A'.repeat(100), insertionPoint: { x: 0, y: 0 }, textHeight: 2, rectWidth: 0 }] }); assert.equal(result.warnings.some((warning) => warning.code === 'TEXT_LAYOUT_LIMITATION'), true) })
test('TEXT остава single-line и не използва MTEXT wrapping', () => { const result = layoutDwgText({ ...baseLayoutInput, textKind: 'TEXT', displayText: 'ред едно\nред две', referenceWidth: 10 }, measureFive); assert.deepEqual(result.lines.map((line) => line.text), ['ред едно ред две']); assert.equal(result.usedSourceWidth, false) })
test('canvas pixel measurement се преобразува в drawing units', () => assert.equal(canvasPixelsToDwgLocal(100, 2, 0.8), 40))
test('width factor участва в measurement точно веднъж', () => { const normal = canvasPixelsToDwgLocal(100, 2, 1), narrow = canvasPixelsToDwgLocal(100, 2, 0.5); assert.equal(normal, 50); assert.equal(narrow, 25) })
test('rotation остава единствено в entity mapping, не в layout helper', () => { const entity = normalizeDwgDatabase({ entities: [{ type: 'MTEXT', handle: 'R', layer: 'TXT', text: 'R', insertionPoint: { x: 0, y: 0 }, textHeight: 2, rotation: 0.7, rectWidth: 20 }] }).entities[0]; assert.equal(entity?.type, 'TEXT'); if (entity?.type === 'TEXT') assert.equal(entity.rotation, 0.7); assert.equal('rotation' in layoutDwgText({ ...baseLayoutInput, displayText: 'R' }, measureFive), false) })
test('деветте MTEXT attachment позиции определят alignment и block anchor', () => { const expected = [{ align: 'left', y: 0 }, { align: 'center', y: 0 }, { align: 'right', y: 0 }, { align: 'left', y: -5 }, { align: 'center', y: -5 }, { align: 'right', y: -5 }, { align: 'left', y: -10 }, { align: 'center', y: -10 }, { align: 'right', y: -10 }]; expected.forEach((item, index) => { const result = layoutDwgText({ ...baseLayoutInput, displayText: 'X', attachmentPoint: index + 1 }, measureFive); assert.equal(result.textAlign, item.align); assert.equal(result.anchorOffsetY, item.y) }) })
test('multi-line anchor използва extent на целия block', () => { const result = layoutDwgText({ ...baseLayoutInput, displayText: 'A\nB', attachmentPoint: 8 }, measureFive); assert.equal(result.blockHeight, 10 + 10 * 5 / 3); assert.equal(result.anchorOffsetY, -result.blockHeight) })
test('line spacing factor се прилага детерминистично', () => { const normal = layoutDwgText({ ...baseLayoutInput, displayText: 'A\nB' }, measureFive), double = layoutDwgText({ ...baseLayoutInput, displayText: 'A\nB', lineSpacingFactor: 2, lineSpacingStyle: 2 }, measureFive); assert.equal(double.lineAdvance, normal.lineAdvance * 2) })
test('Unicode кирилица остава след wrapping и raw evidence е immutable', () => { const rawText = '\\U+0410\\U+0411 \\U+0412\\U+0413'; const normalized = normalizeDwgDisplayText(rawText), result = layoutDwgText({ ...baseLayoutInput, displayText: normalized.displayText, referenceWidth: 15 }, measureFive); assert.equal(result.lines.map((line) => line.text).join(''), 'АБВГ'); assert.equal(normalized.rawText, rawText) })
test('relative H и W създават immutable run metrics без промяна на raw evidence', () => { const raw = 'A{\\H0.8x;\\W0.75;Б}C', normalized = normalizeDwgDisplayText(raw); assert.equal(normalized.rawText, raw); assert.equal(normalized.displayText, 'AБC'); assert.deepEqual(normalized.runs.map(({ text, heightScale, widthScale }) => ({ text, heightScale, widthScale })), [{ text: 'A', heightScale: 1, widthScale: 1 }, { text: 'Б', heightScale: 0.8, widthScale: 0.75 }, { text: 'C', heightScale: 1, widthScale: 1 }]); assert.equal(Object.isFrozen(normalized.runs), true); assert.equal(Object.isFrozen(normalized.runs[0]), true) })
test('absolute H без потвърдена unit semantics остава warning, не metric guess', () => { const normalized = normalizeDwgDisplayText('A\\H12;B'); assert.equal(normalized.runs.at(-1)?.heightScale, 1); assert.ok(normalized.warnings.length) })
test('смесени runs се измерват по собствените metrics и wrap-ват по rectWidth', () => { const runs = normalizeDwgDisplayText('AA {\\W0.5;BBBB} CC').runs; const result = layoutDwgText({ ...baseLayoutInput, displayText: 'AA BBBB CC', runs, referenceWidth: 35 }, (text, run) => text.length * 5 * run.widthScale); assert.deepEqual(result.lines.map((line) => line.text), ['AA BBBB', 'CC']); assert.ok(result.lines[0]!.runs.some((run) => run.widthScale === 0.5)) })
test('layout bbox е същият резултат, използван от renderer runs', () => { const result = layoutDwgText({ ...baseLayoutInput, displayText: 'AB', attachmentPoint: 5 }, measureFive); assert.deepEqual(result.bounds, { minX: -5, minY: -5, maxX: 5, maxY: 5 }); assert.equal(result.lines[0]!.runs[0]!.x, result.bounds.minX) })
test('extentsWidth не се използва имплицитно като secondary wrap width', () => { const entity = normalizeDwgDatabase({ entities: [{ type: 'MTEXT', handle: 'E', layer: 'TXT', text: 'LONG SOURCE TEXT', insertionPoint: { x: 0, y: 0 }, textHeight: 2, rectWidth: 0, extentsWidth: 10 }] }).entities[0]; assert.equal(entity?.type, 'TEXT'); if (entity?.type !== 'TEXT') return; const result = layoutDwgText({ ...baseLayoutInput, displayText: entity.displayText, runs: entity.runs, referenceWidth: entity.referenceWidth }, measureFive); assert.equal(result.usedSourceWidth, false); assert.equal(result.lines.length, 1) })
test('run-aware multiline attachments 1, 3 и 5 използват целия действителен block bbox', () => { for (const attachmentPoint of [1, 3, 5]) { const normalized = normalizeDwgDisplayText('A\\P{\\H1.2x;BB}'), result = layoutDwgText({ ...baseLayoutInput, displayText: normalized.displayText, runs: normalized.runs, attachmentPoint }, measureFive); assert.equal(result.bounds.maxY - result.bounds.minY, result.blockHeight); assert.ok(result.bounds.maxX > result.bounds.minX) } })
test('wrapping не променя section bounds', () => { const sections = detectDwgSections(syntheticSectionsEntities, syntheticDrawingBounds), before = structuredClone(sections[0]!.bounds); layoutDwgText({ ...baseLayoutInput, displayText: 'много думи за пренасяне', referenceWidth: 20 }, measureFive); assert.deepEqual(sections[0]!.bounds, before) })
test('LOD не променя layout lines', () => { const layout = layoutDwgText({ ...baseLayoutInput, displayText: 'едно две три', referenceWidth: 30 }, measureFive), before = structuredClone(layout.lines); isDwgTextVisibleAtScale(10, 0.1); isDwgTextVisibleAtScale(10, 10); assert.deepEqual(layout.lines, before) })
test('слоевете и toggle state са неутрални', () => { const layers = extractDwgLayers(entities); assert.equal(layers[0]?.entityCount, 4); const visible = toggleDwgLayer(new Set(['TEST']), 'TEST'); assert.equal(visible.has('TEST'), false) })
test('fit, pan-compatible offset и anchored zoom остават ограничени', () => { const fit = fitDwgView({ minX: 0, minY: 0, maxX: 100, maxY: 50 }, 500, 300); assert.ok(fit.scale > 0); const zoom = zoomDwgView(fit, 1.2, 250, 150); assert.ok(zoom.scale > fit.scale) })
test('всички safety flags са заключени', () => assert.deepEqual(DWG_SAFETY_FLAGS, { readOnly: true, simulationOnly: true, machineReady: false, productionGeometryApproved: false, internalEvaluationOnly: true, externalDistributionApproved: false }))

const visualSection = { sectionId: 'S', bounds: { minX: 0, minY: 0, maxX: 200, maxY: 200 }, detectionMethod: 'AXIS_ALIGNED_LINE_LOOP' as const, confidence: 'HIGH' as const, reason: 'synthetic', sourceEntities: [], boundaryLayer: 'FRAME', simulationOnly: true as const, machineReady: false as const, internalEvaluationOnly: true as const }
const visualBounds = { minX: 0, minY: 0, maxX: 200, maxY: 200 }
const syntheticMText = (x: number, y: number, rectWidth = 0, height = 5) => normalizeDwgDatabase({ entities: [{ type: 'MTEXT', handle: 'TXT', layer: 'TEXT', text: 'Синтетичен текст за проверка', insertionPoint: { x, y }, textHeight: height, rectWidth }] }).entities[0]!
test('visual field се доказва от четири LINE edges', () => assert.ok(detectDwgVisualFields(rectangleLines('F', 20, 20, 100, 80), [visualSection], visualBounds).some((field) => field.bounds.minX === 20 && field.bounds.maxY === 80)))
test('страна от collinear segments има непрекъснато coverage', () => { const lines = rectangleLines('F', 20, 20, 100, 80); lines.splice(0, 1, { type: 'LINE', handle: 'T1', layer: 'FRAME', start: { x: 20, y: 80 }, end: { x: 60, y: 80 } }, { type: 'LINE', handle: 'T2', layer: 'FRAME', start: { x: 60, y: 80 }, end: { x: 100, y: 80 } }); assert.ok(detectDwgVisualFields(lines, [visualSection], visualBounds).length) })
test('gap в страна не създава visual field', () => { const lines = rectangleLines('F', 20, 20, 100, 80); lines.splice(0, 1, { type: 'LINE', handle: 'T1', layer: 'FRAME', start: { x: 20, y: 80 }, end: { x: 55, y: 80 } }, { type: 'LINE', handle: 'T2', layer: 'FRAME', start: { x: 60, y: 80 }, end: { x: 100, y: 80 } }); assert.equal(detectDwgVisualFields(lines, [visualSection], visualBounds).length, 0) })
test('duplicate visual bounds се дедупликират', () => assert.equal(detectDwgVisualFields([...rectangleLines('A', 20, 20, 100, 80), ...rectangleLines('B', 20, 20, 100, 80)], [visualSection], visualBounds).length, 1))
test('insertion point вътре получава high-confidence assignment', () => { const geometry = rectangleLines('F', 20, 20, 100, 80), text = syntheticMText(40, 40), entities = [...geometry, text]; const result = deriveDwgApproximateTextAssignments(entities, detectDwgVisualFields(entities, [visualSection], visualBounds), [visualSection]); assert.equal(result.assignments.get(geometry.length)?.confidence, 'HIGH') })
test('nested fields избират детерминистично най-малкото валидно поле', () => { const geometry = [...rectangleLines('O', 20, 20, 150, 150), ...rectangleLines('I', 40, 40, 100, 100)], text = syntheticMText(60, 60), entities = [...geometry, text], fields = detectDwgVisualFields(entities, [visualSection], visualBounds), assignment = deriveDwgApproximateTextAssignments(entities, fields, [visualSection]).assignments.get(geometry.length); assert.equal(assignment?.fieldBounds.minX, 40) })
test('boundary point остава unresolved', () => { const geometry = rectangleLines('F', 20, 20, 100, 80), entities = [...geometry, syntheticMText(20, 40)], result = deriveDwgApproximateTextAssignments(entities, detectDwgVisualFields(entities, [visualSection], visualBounds), [visualSection]); assert.equal(result.assignments.size, 0); assert.equal(result.summary.unresolvedTexts, 1) })
test('nearest field без containment не се използва', () => { const geometry = rectangleLines('F', 20, 20, 100, 80), entities = [...geometry, syntheticMText(110, 40)], result = deriveDwgApproximateTextAssignments(entities, detectDwgVisualFields(entities, [visualSection], visualBounds), [visualSection]); assert.equal(result.assignments.size, 0) })
test('micro field спрямо text height се отхвърля', () => { const geometry = rectangleLines('F', 20, 20, 28, 28), entities = [...geometry, syntheticMText(24, 24, 0, 5)], result = deriveDwgApproximateTextAssignments(entities, detectDwgVisualFields(entities, [visualSection], visualBounds), [visualSection]); assert.equal(result.assignments.size, 0) })
test('section frame не се избира вместо конкретно поле', () => { const geometry = [...rectangleLines('S', 0, 0, 200, 200), ...rectangleLines('F', 20, 20, 100, 80)], entities = [...geometry, syntheticMText(40, 40)], result = deriveDwgApproximateTextAssignments(entities, detectDwgVisualFields(entities, [visualSection], visualBounds), [visualSection]); assert.deepEqual(result.assignments.get(geometry.length)?.fieldBounds, { minX: 20, minY: 20, maxX: 100, maxY: 80 }) })
test('MTEXT с rectWidth остава source-driven', () => { const geometry = rectangleLines('F', 20, 20, 100, 80), entities = [...geometry, syntheticMText(40, 40, 30)], result = deriveDwgApproximateTextAssignments(entities, detectDwgVisualFields(entities, [visualSection], visualBounds), [visualSection]); assert.equal(result.assignments.size, 0); assert.equal(result.summary.sourceWidthTexts, 1) })
test('approximate assignment има padding и заключени safety flags', () => { const geometry = rectangleLines('F', 20, 20, 100, 80), entities = [...geometry, syntheticMText(40, 40)], assignment = deriveDwgApproximateTextAssignments(entities, detectDwgVisualFields(entities, [visualSection], visualBounds), [visualSection]).assignments.get(geometry.length)!; assert.ok(assignment.innerBounds.minX > assignment.fieldBounds.minX); assert.deepEqual({ simulationOnly: assignment.simulationOnly, machineReady: assignment.machineReady, internalEvaluationOnly: assignment.internalEvaluationOnly }, { simulationOnly: true, machineReady: false, internalEvaluationOnly: true }) })
test('toggle off възстановява SOURCE без да променя derived assignment', () => { const assignment = { mode: 'APPROXIMATE_FIELD' as const } as never; assert.equal(resolveDwgTextDisplayMode(true, assignment), 'APPROXIMATE_FIELD'); assert.equal(resolveDwgTextDisplayMode(false, assignment), 'SOURCE') })
test('manual correction state machine преминава idle → text → field → applied', () => { const entity = syntheticMText(40, 40), field = detectDwgVisualFields(rectangleLines('F', 20, 20, 100, 80), [visualSection], visualBounds)[0]!, started = startDwgCorrection(initialDwgCorrectionState()), selected = selectDwgCorrectionText(started, 0), applied = applyDwgManualAssignment(selected, field, entity); assert.equal(started.step, 'SELECT_TEXT'); assert.equal(selected.step, 'SELECT_FIELD'); assert.equal(applied.step, 'SELECT_TEXT'); assert.equal(applied.assignments.length, 1) })
test('visible MTEXT bbox hit-test предпочита unresolved и после това най-малък bbox', () => { const hit = hitTestVisibleDwgText([{ entityIndex: 2, bounds: { minX: 0, minY: 0, maxX: 20, maxY: 20 }, unresolvedNoWidth: false }, { entityIndex: 3, bounds: { minX: 2, minY: 2, maxX: 18, maxY: 18 }, unresolvedNoWidth: true }], 10, 10); assert.equal(hit?.entityIndex, 3) })
test('overlapping equal text candidates имат deterministic entity ranking', () => { const bounds = { minX: 0, minY: 0, maxX: 10, maxY: 10 }; assert.equal(hitTestVisibleDwgText([{ entityIndex: 8, bounds, unresolvedNoWidth: true }, { entityIndex: 4, bounds, unresolvedNoWidth: true }], 5, 5)?.entityIndex, 4) })
test('drag над movement threshold не е selection click', () => assert.equal(isDwgSectionClick({ x: 0, y: 0 }, { x: 20, y: 0 }), false))
test('hidden или stale field evidence прави manual assignment inactive', () => { const geometry = rectangleLines('F', 20, 20, 100, 80), entity = syntheticMText(40, 40), entities = [...geometry, entity], fields = detectDwgVisualFields(entities, [visualSection], visualBounds), applied = applyDwgManualAssignment(selectDwgCorrectionText(startDwgCorrection(initialDwgCorrectionState()), geometry.length), fields[0]!, entity); assert.equal(resolveDwgManualDisplayAssignments(applied.assignments, entities, [], new Set(['FRAME', 'TEXT'])).size, 0); assert.equal(resolveDwgManualDisplayAssignments(applied.assignments, entities, fields, new Set(['FRAME'])).size, 0) })
test('field от друга section не се връща от section-scoped hit-test', () => { const field = { ...detectDwgVisualFields(rectangleLines('F', 20, 20, 100, 80), [visualSection], visualBounds)[0]!, sectionId: 'OTHER' }; assert.equal(hitTestDwgVisualField([field], 'S', 40, 40), null) })
test('section outer frame не е visual target', () => assert.equal(detectDwgVisualFields(rectangleLines('S', 0, 0, 200, 200), [visualSection], visualBounds).length, 0))
test('human apply създава заключен MANUAL_APPROXIMATE_FIELD запис', () => { const entity = syntheticMText(40, 40), field = detectDwgVisualFields(rectangleLines('F', 20, 20, 100, 80), [visualSection], visualBounds)[0]!, applied = applyDwgManualAssignment(selectDwgCorrectionText(startDwgCorrection(initialDwgCorrectionState()), 0), field, entity), assignment = applied.assignments[0]!; assert.deepEqual({ mode: assignment.mode, humanConfirmed: assignment.humanConfirmed, simulationOnly: assignment.simulationOnly, machineReady: assignment.machineReady, internalEvaluationOnly: assignment.internalEvaluationOnly }, { mode: 'MANUAL_APPROXIMATE_FIELD', humanConfirmed: true, simulationOnly: true, machineReady: false, internalEvaluationOnly: true }) })
test('manual assignment има приоритет над automatic само за същия entity', () => { const automatic = new Map([[1, { mode: 'APPROXIMATE_FIELD' } as never], [2, { mode: 'APPROXIMATE_FIELD' } as never]]), manual = new Map([[1, { mode: 'MANUAL_APPROXIMATE_FIELD' } as never]]), merged = mergeDwgDisplayAssignments(automatic, manual); assert.equal(merged.get(1)?.mode, 'MANUAL_APPROXIMATE_FIELD'); assert.equal(merged.get(2)?.mode, 'APPROXIMATE_FIELD') })
test('approximate toggle off не изтрива session manual assignment', () => { const visible = (enabled: boolean, manual: Map<number, never>) => enabled ? manual.get(1) : undefined, manual = new Map([[1, { mode: 'MANUAL_APPROXIMATE_FIELD' } as never]]); assert.equal(visible(false, manual), undefined); assert.equal(manual.size, 1) })
test('manual assignment използва доказан inner field padding за wrap и clip', () => { const entity = syntheticMText(40, 40), field = detectDwgVisualFields(rectangleLines('F', 20, 20, 100, 80), [visualSection], visualBounds)[0]!, assignment = applyDwgManualAssignment(selectDwgCorrectionText(startDwgCorrection(initialDwgCorrectionState()), 0), field, entity).assignments[0]!; assert.ok(assignment.innerBounds.minX > assignment.fieldBounds.minX); assert.ok(assignment.innerBounds.maxX < assignment.fieldBounds.maxX) })
test('manual apply не променя source entity или raw text', () => { const entity = syntheticMText(40, 40), before = structuredClone(entity), field = detectDwgVisualFields(rectangleLines('F', 20, 20, 100, 80), [visualSection], visualBounds)[0]!; applyDwgManualAssignment(selectDwgCorrectionText(startDwgCorrection(initialDwgCorrectionState()), 0), field, entity); assert.deepEqual(entity, before) })
test('undo е LIFO, remove е specific, clear премахва всички', () => { const fields = detectDwgVisualFields([...rectangleLines('A', 20, 20, 80, 80), ...rectangleLines('B', 100, 20, 160, 80)], [visualSection], visualBounds), entity = syntheticMText(40, 40); let state = applyDwgManualAssignment(selectDwgCorrectionText(startDwgCorrection(initialDwgCorrectionState()), 1), fields[0]!, entity); state = applyDwgManualAssignment(selectDwgCorrectionText(state, 2), fields[1]!, entity); const firstId = state.assignments[0]!.id; state = undoDwgManualAssignment(state); assert.equal(state.assignments.length, 1); assert.equal(state.assignments[0]!.id, firstId); assert.equal(removeDwgManualAssignment(state, firstId).assignments.length, 0); assert.equal(clearDwgManualAssignments(state).assignments.length, 0) })
test('Escape priority връща field step към text step преди idle', () => { const selected = selectDwgCorrectionText(startDwgCorrection(initialDwgCorrectionState()), 1), first = cancelDwgCorrectionStep(selected), second = cancelDwgCorrectionStep(first); assert.equal(first.step, 'SELECT_TEXT'); assert.equal(second.step, 'IDLE') })
test('manual state не съдържа viewport, export, product или operation данни', () => { const state = initialDwgCorrectionState(); assert.equal('view' in state || 'export' in state || 'product' in state || 'operations' in state, false) })
