import { useMemo, useState } from 'react'
import type { CombinedAnalysisJob, CombinedAuditEntry, CombinedCandidate } from '../combinedAnalysisTypes'
import { getProductTemplate, productTemplates } from '../productTemplates'
import { TemplateDiagram } from './TemplateDiagram'

export interface CombinedApplication { templateId?: string; width?: number; height?: number; quantity?: number; productReference?: string }
interface Props { job: CombinedAnalysisJob; cropDataUrl: string; audit: CombinedAuditEntry[]; onDecision: (candidate: CombinedCandidate, status: 'ACCEPTED' | 'REJECTED', value: string) => void; onScheme: (templateId: string) => void; onApply: (values: CombinedApplication) => void }

export function CombinedAnalysisReview({ job, cropDataUrl, audit, onDecision, onScheme, onApply }: Props) {
  const [selectedTemplateId, setSelectedTemplateId] = useState(job.schemeRankings[0]?.templateId ?? 'REF-01')
  const [edits, setEdits] = useState<Record<string, string>>({})
  const [checked, setChecked] = useState(false)
  const [highlightedCandidateId, setHighlightedCandidateId] = useState<string | null>(null)
  const accepted = useMemo(() => job.candidates.filter((item) => item.status === 'ACCEPTED'), [job.candidates])
  const acceptedValue = (type: CombinedCandidate['type']) => { const item = accepted.find((candidate) => candidate.type === type); return item ? (edits[item.id] ?? item.normalizedValue) : undefined }
  const application: CombinedApplication = { templateId: selectedTemplateId, width: Number(acceptedValue('OVERALL_WIDTH')) || undefined, height: Number(acceptedValue('OVERALL_HEIGHT')) || undefined, quantity: Number(acceptedValue('QUANTITY')) || undefined, productReference: acceptedValue('PRODUCT_REFERENCE') }
  const selectedTemplate = getProductTemplate(selectedTemplateId)
  const targetFor = (candidate: CombinedCandidate) => candidate.type === 'OVERALL_WIDTH' ? 'Ширина' : candidate.type === 'OVERALL_HEIGHT' ? 'Височина' : candidate.type === 'QUANTITY' ? 'Количество' : candidate.type === 'PRODUCT_REFERENCE' ? 'Референция на изделието' : 'Само review — без автоматична цел'
  return <section className="combined-review" aria-labelledby="combined-review-title"><header><h3 id="combined-review-title">Комбиниран локален анализ</h3><p>Всички оценки са предложения. „Демонстрационно сходство“ не е вероятност или технологично одобрение.</p></header>{job.warnings.length > 0 && <ul className="combined-warnings" role="alert">{job.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul>}<div className="combined-review-grid">
    <section><h4>A. Source evidence</h4><div className="combined-evidence" id="combined-source-evidence"><img src={cropDataUrl} alt="Потвърдена комбинирана зона"/>{job.ocrItems.filter((item) => item.bbox).map((item, index) => { const box = item.bbox!; return <span key={`${index}-${item.text}`} title={`${item.text} · ${item.confidence.toFixed(1)}%`} style={{ left: `${box.x / job.evidenceWidth * 100}%`, top: `${box.y / job.evidenceHeight * 100}%`, width: `${box.width / job.evidenceWidth * 100}%`, height: `${box.height / job.evidenceHeight * 100}%` }}/>} )}{job.candidates.filter((item) => item.sourceBox).map((candidate) => { const box = candidate.sourceBox!; return <span key={candidate.id} className={`candidate-source-box ${highlightedCandidateId === candidate.id ? 'highlighted' : ''}`} aria-hidden="true" style={{ left: `${box.x / job.evidenceWidth * 100}%`, top: `${box.y / job.evidenceHeight * 100}%`, width: `${box.width / job.evidenceWidth * 100}%`, height: `${box.height / job.evidenceHeight * 100}%` }}/> })}</div><p>Стр. {job.sourcePage} · X {Math.round(job.crop.x)}, Y {Math.round(job.crop.y)} · {Math.round(job.crop.width)} × {Math.round(job.crop.height)} px</p><details><summary>Raw OCR evidence</summary><pre>{job.rawOcrText || 'Няма разпознат текст.'}</pre></details></section>
    <section><h4>B. Proposed product</h4>{job.schemeRankings.map((ranking) => <article key={ranking.templateId} className={selectedTemplateId === ranking.templateId ? 'selected' : ''}><button type="button" onClick={() => { setSelectedTemplateId(ranking.templateId); onScheme(ranking.templateId) }}><TemplateDiagram template={getProductTemplate(ranking.templateId)} compact/><b>{ranking.templateId} — {ranking.title}</b><span>Демонстрационно сходство: {ranking.similarity}%</span></button><details><summary>Feature breakdown</summary>{Object.entries(ranking.scores).map(([key, value]) => <span key={key}>{key}: {value.toFixed(1)}</span>)}</details>{ranking.warnings.map((warning) => <small key={warning}>{warning}</small>)}</article>)}<label>Ръчен избор на схема<select value={selectedTemplateId} onChange={(event) => { setSelectedTemplateId(event.target.value); onScheme(event.target.value) }}>{productTemplates.map((template) => <option key={template.id} value={template.id}>{template.id} — {template.name}</option>)}</select></label><div className="combined-selected-template"><TemplateDiagram template={selectedTemplate}/></div></section>
    <section><h4>C. Proposed data</h4><p>OCR confidence: {job.ocrConfidence.toFixed(1)}%</p><div className="combined-candidates">{job.candidates.map((candidate) => { const value = edits[candidate.id] ?? candidate.normalizedValue; return <article key={candidate.id}><b>{candidate.type}</b><small>{candidate.rawSourceText}</small><label>Предложение<input value={value} onChange={(event) => setEdits({ ...edits, [candidate.id]: event.target.value })}/></label><span>Целево поле: {targetFor(candidate)}</span><span>OCR {candidate.ocrConfidence.toFixed(1)}% · parser {candidate.parserConfidence}% · {candidate.status}</span>{candidate.warning && <strong>{candidate.warning}</strong>}<div><a href="#combined-source-evidence" role="button" onClick={() => setHighlightedCandidateId(candidate.id)}>Покажи източника</a><button type="button" onClick={() => onDecision(candidate, 'ACCEPTED', value)}>Приеми</button><button type="button" onClick={() => onDecision(candidate, 'REJECTED', value)}>Отхвърли</button></div></article> })}</div></section>
  </div><section className="combined-confirmation"><div><h4>Потвърждение на изделието</h4><p>Схема: {selectedTemplateId} · ширина: {application.width ?? 'неприета'} · височина: {application.height ?? 'неприета'} · количество: {application.quantity ?? 'неприето'} · референция: {application.productReference ?? 'неприета'}</p><p>Нерешени предложения: {job.candidates.filter((item) => item.status === 'SUGGESTED').length}</p></div><img src={cropDataUrl} alt="Оригинална извадка за финално човешко потвърждение"/><label className="combined-check"><input type="checkbox" checked={checked} onChange={(event) => setChecked(event.target.checked)}/>Проверих схемата и размерите по оригиналния чертеж.</label><button type="button" className="primary-button" disabled={!checked} onClick={() => onApply(application)}>Приложи изрично потвърдените стойности</button><details><summary>Combined audit ({audit.length})</summary><ul>{audit.map((entry) => <li key={entry.id}>{entry.timestamp} · {entry.action} · {entry.target}</li>)}</ul></details></section></section>
}
