import { useEffect, useMemo, useRef, useState, type KeyboardEvent, type PointerEvent, type WheelEvent } from 'react'
import { beginCameraDrag, cameraKey, clampConceptualZoom, CONCEPTUAL_3D_INITIAL_VIEW, presetView, updateCameraDrag } from '../conceptual3dCamera'
import { fitSceneToViewport, hitTestProjected, sceneFitsViewport } from '../conceptual3dScene'
import { renderConceptualScene } from '../conceptual3dRenderer'
import type { CameraDragState, ConceptualScene, ConceptualViewPreset, ConceptualViewState, ProjectedNode } from '../conceptual3dTypes'
import '../conceptual3d.css'

export interface Conceptual3DViewSummary { label: string; zoom: number }
interface Props { scene: ConceptualScene; selectedSemanticId: string | null; onSelect: (semanticId: string, kind: string) => void; onViewStatus?: (status: Conceptual3DViewSummary) => void }
const views: Array<{ value: Exclude<ConceptualViewPreset, 'CUSTOM'>; label: string }> = [{ value: 'FRONT', label: 'Отпред' }, { value: 'BACK', label: 'Отзад' }, { value: 'LEFT', label: 'Отляво' }, { value: 'RIGHT', label: 'Отдясно' }, { value: 'ISOMETRIC', label: 'Изометрия' }]
const viewLabel = (value: ConceptualViewPreset) => ({ FRONT: 'Отпред', BACK: 'Отзад', LEFT: 'Отляво', RIGHT: 'Отдясно', ISOMETRIC: 'Изометрия', CUSTOM: 'Персонализирана' }[value])

export function Conceptual3DPreview({ scene, selectedSemanticId, onSelect, onViewStatus }: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null), projectedRef = useRef<ProjectedNode[]>([]), dragRef = useRef<CameraDragState | null>(null), movedRef = useRef(false), fittedSceneKeyRef = useRef('')
  const [view, setView] = useState<ConceptualViewState>(CONCEPTUAL_3D_INITIAL_VIEW), [dragging, setDragging] = useState(false), [size, setSize] = useState({ width: 640, height: 440 })
  const accessibleNodes = useMemo(() => scene.nodes.filter((node) => node.selectable), [scene])
  const fitKey = useMemo(() => JSON.stringify([scene.bounds, scene.nodes.map((node) => [node.nodeId, node.bounds])]), [scene])
  useEffect(() => onViewStatus?.({ label: viewLabel(view.preset), zoom: Math.round(view.zoom * 100) }), [view, onViewStatus])
  useEffect(() => { const canvas = canvasRef.current; if (!canvas || typeof ResizeObserver === 'undefined') return; const measure=()=>{const width=canvas.clientWidth,height=canvas.clientHeight;if(width>0&&height>0)setSize({width:Math.max(280,width),height:Math.max(260,height)})};const observer = new ResizeObserver(measure); observer.observe(canvas);measure();return () => observer.disconnect() }, [])
  useEffect(() => { setView((current) => { const firstFit=fittedSceneKeyRef.current===''; fittedSceneKeyRef.current=fitKey; return firstFit||!sceneFitsViewport(scene,current,size.width,size.height)?fitSceneToViewport(scene,current,size.width,size.height):current }) }, [fitKey, scene, size])
  useEffect(() => { const canvas = canvasRef.current, context = canvas?.getContext('2d'); if (!canvas || !context) return; const ratio = Math.max(1, window.devicePixelRatio || 1); canvas.width = Math.round(size.width * ratio); canvas.height = Math.round(size.height * ratio); context.setTransform(ratio, 0, 0, ratio, 0, 0); const frame = requestAnimationFrame(() => { projectedRef.current = renderConceptualScene(context, scene, view, size.width, size.height, selectedSemanticId).projected }); return () => cancelAnimationFrame(frame) }, [scene, view, size, selectedSemanticId])
  const start = (event: PointerEvent<HTMLCanvasElement>) => { event.preventDefault(); event.currentTarget.focus(); event.currentTarget.setPointerCapture(event.pointerId); dragRef.current = beginCameraDrag(event.pointerId, event.clientX, event.clientY, view); movedRef.current = false; setDragging(true) }
  const move = (event: PointerEvent<HTMLCanvasElement>) => { const drag = dragRef.current; if (!drag || drag.pointerId !== event.pointerId) return; event.preventDefault(); const next = updateCameraDrag(drag, event.clientX, event.clientY); movedRef.current ||= Math.hypot(event.clientX - drag.startX, event.clientY - drag.startY) > 4; dragRef.current = next; setView(next.preview) }
  const finish = (event: PointerEvent<HTMLCanvasElement>, cancelled = false) => { const drag = dragRef.current; if (!drag || drag.pointerId !== event.pointerId) return; if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); dragRef.current = null; setDragging(false); if (cancelled) setView(drag.initial); else if (!movedRef.current) { const rect = event.currentTarget.getBoundingClientRect(), hit = hitTestProjected(projectedRef.current, event.clientX - rect.left, event.clientY - rect.top); if (hit) onSelect(hit.semanticSourceId, hit.kind) } }
  const keyboard = (event: KeyboardEvent<HTMLCanvasElement>) => { if (event.key === 'Escape' && dragRef.current) { event.preventDefault(); setView(dragRef.current.initial); dragRef.current = null; setDragging(false); return } const next=event.key==='0'?fitSceneToViewport(scene,CONCEPTUAL_3D_INITIAL_VIEW,size.width,size.height):event.key.toLowerCase()==='f'?fitSceneToViewport(scene,view,size.width,size.height):cameraKey(view,event.key); if (next !== view) { event.preventDefault(); setView(next) } }
  const wheel = (event: WheelEvent<HTMLCanvasElement>) => { event.preventDefault(); setView((current) => ({ ...current, zoom: clampConceptualZoom(current.zoom * (event.deltaY > 0 ? .9 : 1.1)), preset: 'CUSTOM' })) }
  return <section className="conceptual-3d-preview" aria-label="Концептуален триизмерен изглед">
    <div className="conceptual-3d-controls" aria-label="Готови гледни точки">{views.map((item) => <button type="button" key={item.value} aria-pressed={view.preset === item.value} onClick={() => setView(fitSceneToViewport(scene,presetView(item.value),size.width,size.height))}>{item.label}</button>)}<button type="button" onClick={() => setView((current) => fitSceneToViewport(scene,current,size.width,size.height))}>Побери в изгледа</button><button type="button" onClick={() => setView(fitSceneToViewport(scene,CONCEPTUAL_3D_INITIAL_VIEW,size.width,size.height))}>Нулирай изгледа</button></div>
    <div className="conceptual-3d-safety-line" role="note"><b>Концептуална 3D визуализация — не е производствен модел.</b>{scene.thresholdUnresolved && <strong>Праг: НЕРАЗРЕШЕН.</strong>}</div>
    <canvas ref={canvasRef} tabIndex={0} className={dragging ? 'dragging' : ''} aria-label={`Интерактивна концептуална 3D визуализация. Гледна точка: ${viewLabel(view.preset)}. Използвайте стрелките за въртене, плюс и минус за мащаб.`} onPointerDown={start} onPointerMove={move} onPointerUp={(event) => finish(event)} onPointerCancel={(event) => finish(event, true)} onKeyDown={keyboard} onWheel={wheel}/>
    <details className="conceptual-3d-notes"><summary>За концептуалния 3D изглед</summary><p>Дълбочините са демонстрационни и нямат производствено значение. Посоката е концептуално означение; крилото не е кинематично симулирано.</p></details>
    <div className="conceptual-3d-legend"><span>Отпред — външен цвят</span><span>Отзад — вътрешен цвят</span></div>
    <details className="conceptual-3d-access"><summary>Достъпен списък на елементите</summary><ul>{accessibleNodes.map((node) => <li key={node.nodeId}><button type="button" aria-pressed={node.semanticSourceId === selectedSemanticId} onClick={() => onSelect(node.semanticSourceId, node.kind)}>{node.label}{node.openingLabel ? ` — ${node.openingLabel}` : ''}</button></li>)}</ul></details>
    <p className="conceptual-3d-instructions">Мишка или докосване: плъзнете за въртене. Колелце: мащаб. Клавиши: стрелки, +/−, 0, F и Escape.</p>
    <dl className="conceptual-3d-view-status"><dt>3D изглед</dt><dd>{viewLabel(view.preset)}</dd><dt>Zoom</dt><dd>{Math.round(view.zoom * 100)}%</dd><dt>Режим</dt><dd>Концептуален</dd></dl>
  </section>
}
