import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent, type WheelEvent as ReactWheelEvent } from 'react'
import { createDetailDraftDocument, DETAIL_DRAFT_INITIAL_VIEWPORT, DETAIL_DRAFT_VIEWPORT_LIMITS, fitDetailDraftViewport, panDetailDraftViewport, zoomDetailDraftViewport } from '../detailDraftViewport'

interface Props { onClose: () => void }
const plannedTools = ['Линия', 'Полилиния', 'Правоъгълник', 'Окръжност', 'Дъга']

export function DetailDraftingPlaceholder({ onClose }: Props) {
  const document = useMemo(() => createDetailDraftDocument(), [])
  const stageRef = useRef<HTMLElement>(null)
  const dragRef = useRef<{ pointerId: number; x: number; y: number } | null>(null)
  const [navigationActive, setNavigationActive] = useState(false)
  const [viewport, setViewport] = useState(DETAIL_DRAFT_INITIAL_VIEWPORT)
  const fit = () => { const box = stageRef.current?.getBoundingClientRect(); if (box) setViewport(fitDetailDraftViewport(box.width, box.height)) }
  useEffect(() => { fit() }, [])
  useEffect(() => { const keydown = (event: KeyboardEvent) => { if (event.key === 'Escape' && navigationActive) { setNavigationActive(false); dragRef.current = null } }; window.addEventListener('keydown', keydown); return () => window.removeEventListener('keydown', keydown) }, [navigationActive])
  const localPoint = (clientX: number, clientY: number) => { const box = stageRef.current?.getBoundingClientRect(); return { x: clientX - (box?.left ?? 0), y: clientY - (box?.top ?? 0) } }
  const onPointerDown = (event: ReactPointerEvent<HTMLElement>) => { if (!navigationActive) { setNavigationActive(true); return }; dragRef.current = { pointerId: event.pointerId, x: event.clientX, y: event.clientY }; event.currentTarget.setPointerCapture(event.pointerId) }
  const onPointerMove = (event: ReactPointerEvent<HTMLElement>) => { const drag = dragRef.current; if (!drag || drag.pointerId !== event.pointerId) return; setViewport((current) => panDetailDraftViewport(current, event.clientX - drag.x, event.clientY - drag.y)); dragRef.current = { ...drag, x: event.clientX, y: event.clientY } }
  const stopDrag = (event: ReactPointerEvent<HTMLElement>) => { if (dragRef.current?.pointerId === event.pointerId) dragRef.current = null }
  const onWheel = (event: ReactWheelEvent<HTMLElement>) => { if (!navigationActive) return; event.preventDefault(); const point = localPoint(event.clientX, event.clientY); const factor = event.deltaY < 0 ? DETAIL_DRAFT_VIEWPORT_LIMITS.zoomStep : 1 / DETAIL_DRAFT_VIEWPORT_LIMITS.zoomStep; setViewport((current) => zoomDetailDraftViewport(current, factor, point.x, point.y)) }
  const gridSize = 20 * viewport.scale
  return <section className="detail-drafting" role="dialog" aria-modal="true" aria-labelledby="detail-drafting-title"><header className="detail-drafting-header"><div><span>PHASE 06A.1 · VIEWPORT FOUNDATION</span><h2 id="detail-drafting-title">Чертане на детайл</h2><p>Отделно локално работно пространство · session-only · без геометрия.</p></div><button type="button" onClick={onClose}>Назад към FacadeFlow</button></header><div className="detail-drafting-safety">Безопасна визуална подготовка: не се създава геометрия, не се променя DWG и няма export или връзка с машина.</div><div className="detail-drafting-toolbar" aria-label="Навигация на работната зона"><button type="button" aria-pressed={navigationActive} onClick={() => setNavigationActive((active) => !active)}>✋ {navigationActive ? 'Ръчичка активна' : 'Активирай ръчичката'}</button><button type="button" onClick={fit}>Побери изгледа</button><button type="button" onClick={() => setViewport(DETAIL_DRAFT_INITIAL_VIEWPORT)}>Нулирай изгледа</button><output aria-live="polite">Zoom {Math.round(viewport.scale * 100)}%</output></div><div className="detail-drafting-layout"><aside><h3>Инструменти</h3>{plannedTools.map((tool) => <button type="button" disabled key={tool}>{tool}</button>)}<small>Инструментите остават заключени до следваща отделна фаза.</small></aside><main ref={stageRef} className={`detail-drafting-stage ${navigationActive ? 'navigation-active' : ''}`} aria-label="Работна зона за безопасна viewport навигация" tabIndex={0} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={stopDrag} onPointerCancel={stopDrag} onWheel={onWheel} style={{ backgroundSize: `${gridSize}px ${gridSize}px, ${gridSize}px ${gridSize}px, ${gridSize * 5}px ${gridSize * 5}px, ${gridSize * 5}px ${gridSize * 5}px`, backgroundPosition: `${viewport.offsetX}px ${viewport.offsetY}px` }}><div className="detail-drafting-origin" style={{ transform: `translate(${viewport.offsetX}px, ${viewport.offsetY}px)` }} aria-hidden="true"><span /><i /></div><div className="detail-drafting-empty"><strong>Празен detail document</strong><p>{navigationActive ? 'Drag за pan · wheel за zoom · Escape освобождава мишката.' : 'Щракнете в зоната, за да активирате навигацията.'}</p><span>0 геометрични обекта</span></div></main><aside><h3>Свойства</h3><p>Няма избран обект.</p><dl><dt>Документ</dt><dd>{document.id}</dd><dt>Съхранение</dt><dd>Само текущата сесия</dd><dt>Simulation only</dt><dd>true</dd><dt>Machine ready</dt><dd>false</dd><dt>Production approved</dt><dd>false</dd></dl></aside></div></section>
}
