import { useEffect, useMemo, useRef, useState, type DragEvent, type PointerEvent } from 'react'
import type * as React from 'react'
import { hasUnusualDemonstrationalDoorProportion, type StructuredProfileConfiguration } from '../hybridProductDesigner'
import { applyDoorTemplate, canAddDoorHardware, canConceptuallyReviewDoor, canConfigureDoorOpening, clearDoorComposition, conceptuallyReviewDoor, deleteDoorHardware, doorFieldDisplayName, doorOpeningWorkflowStatus, moveDoorHardware, selectDoorField, selectDoorHardware, setDoorColor, setDoorHandleStyle, validateDoorComposition } from '../doorComposerState'
import { addDoorHardwareForExplicitTarget, setDoorInfillForExplicitTarget, setDoorOpeningForExplicitTarget } from '../doorComposerExplicitFieldTarget'
import { DOOR_TEMPLATES } from '../doorComposerTemplates'
import type { DoorColor, DoorComposition, DoorHardware, DoorInfill } from '../doorComposerTypes'
import type { CatalogueProfile } from '../profileCatalogueTypes'
import { doorOpeningGeometry } from '../doorOpeningGeometry'
import { calculateDoorDrawingLayout, calculateDoorFieldBounds, calculateDoorHingeAnchor, calculateDoorThumbnailFieldBounds } from '../doorComposerLayout'
import { beginHardwareDrag, hardwareDragChanged, positionRatioFromSvgY, previewHardwareDrag, type HardwareDragSession } from '../visualComposerPointerDrag'
import { buildDoorConceptualScene } from '../conceptual3dDoorScene'
import { Conceptual3DPreview, type Conceptual3DViewSummary } from './Conceptual3DPreview'
import { containsVisualBounds, fitVisualBounds } from '../composerViewport'
import '../visualComposerUx.css'
import '../doorComposerFieldFocus.css'
import { WorkingConfigurationDataPanel } from './WorkingConfigurationDataPanel'

interface Props { configuration: StructuredProfileConfiguration; profiles: CatalogueProfile[]; onConfigurationChange: (patch: Partial<Pick<StructuredProfileConfiguration, 'profileSystem' | 'frameProfileId' | 'sashProfileId' | 'mullionProfileId'>>) => void; initial: DoorComposition; onChange: (composition: DoorComposition) => void; initialTemplateId?: string | null; onBack: () => void; onCloseFacadeFlow: () => void }
const colors: Array<{value:DoorColor;label:string}>=[{value:'',label:'Не е избран'},{value:'WHITE',label:'Бяло'},{value:'ANTHRACITE',label:'Антрацит'},{value:'BLACK',label:'Черно'},{value:'BROWN',label:'Кафяво'},{value:'SILVER',label:'Сребристо'},{value:'CUSTOM',label:'Друг цвят'}]
const doorCanvasFieldLabel=(fields:DoorComposition['fields'],id:string)=>{const label=doorFieldDisplayName(fields,id);return fields.length>2?label.replace(/ от \d+$/,''):label}
const hingeSideLabel=(value:DoorComposition['fields'][number]['hingeSide'])=>value==='LEFT'?'Ляво':value==='RIGHT'?'Дясно':'Не е избрана'
const swingLabel=(value:DoorComposition['fields'][number]['swing'])=>value==='INWARD'?'Навътре':value==='OUTWARD'?'Навън':'Не е избрана'

export function DoorVisualComposer({configuration,profiles,onConfigurationChange,initial,onChange,initialTemplateId=null,onBack,onCloseFacadeFlow}:Props){
  const stageRef=useRef<HTMLElement>(null)
  const [state,setState]=useState(()=>initial),[past,setPast]=useState<DoorComposition[]>([]),[future,setFuture]=useState<DoorComposition[]>([]),[open,setOpen]=useState('templates'),[drag,setDrag]=useState<HardwareDragSession|null>(null),[review,setReview]=useState(false),[thresholdAcknowledged,setThresholdAcknowledged]=useState(false),[workspaceMessage,setWorkspaceMessageState]=useState(''),[viewMode,setViewMode]=useState<'2D'|'3D'>('2D'),[threeDView,setThreeDView]=useState<Conceptual3DViewSummary>({label:'Изометрия',zoom:82})
  useEffect(()=>{onChange(state)},[state,onChange])
  const setWorkspaceMessage=(message:string)=>{if(message!=='Изгледът е побран'){setWorkspaceMessageState(message);return}const svg=stageRef.current?.querySelector('svg'),box=svg?.getBoundingClientRect(),fitted=box?fitVisualBounds({x:0,y:0,width:800,height:520},box.width,box.height):null;setWorkspaceMessageState(fitted&&box&&containsVisualBounds(box.width,box.height,fitted.rect)?message:'Изгледът още не е измерен или не е побран.')}
  useEffect(()=>{const stage=stageRef.current;if(!stage||typeof ResizeObserver==='undefined')return;const observer=new ResizeObserver(()=>setWorkspaceMessage(''));observer.observe(stage);return()=>observer.disconnect()},[configuration.overallWidth,configuration.overallHeight])
  const commit=(next:DoorComposition)=>{if(JSON.stringify(next)===JSON.stringify(state))return;setPast(v=>[...v,state]);setFuture([]);setState(next);setReview(false)}
  const undo=()=>{const previous=past.at(-1);if(!previous)return;setPast(v=>v.slice(0,-1));setFuture(v=>[state,...v]);setState(previous);setReview(false)}
  const redo=()=>{const next=future[0];if(!next)return;setFuture(v=>v.slice(1));setPast(v=>[...v,state]);setState(next);setReview(false)}
  const field=state.fields.find(f=>f.id===state.selectedFieldId),hardware=state.hardware.find(h=>h.id===state.selectedHardwareId),errors=validateDoorComposition(state)
  const tool=(value:string,id=state.selectedFieldId,position?:number)=>{const targetFieldId=id;if(!targetFieldId)return;const selected=state.fields.find(f=>f.id===targetFieldId);if(value.startsWith('INFILL:'))commit(setDoorInfillForExplicitTarget(state,targetFieldId,value.slice(7) as DoorInfill));else if(value.startsWith('SIDE:'))commit(setDoorOpeningForExplicitTarget(state,targetFieldId,value.slice(5) as 'LEFT'|'RIGHT',selected?.swing??null));else if(value.startsWith('SWING:'))commit(setDoorOpeningForExplicitTarget(state,targetFieldId,selected?.hingeSide??null,value.slice(6) as 'INWARD'|'OUTWARD'));else if(value==='HINGE'||value==='HANDLE')commit(addDoorHardwareForExplicitTarget(state,targetFieldId,value,()=>crypto.randomUUID(),position))}
  const applyTemplate=(id:string)=>{if(initialTemplateId&&id!==initialTemplateId)return;commit(applyDoorTemplate(state,id));setWorkspaceMessage('Изгледът е побран')}
  const drop=(e:DragEvent,id?:string)=>{e.preventDefault();e.stopPropagation();const template=e.dataTransfer.getData('application/x-facadeflow-door-template'),item=e.dataTransfer.getData('application/x-facadeflow-door-tool');if(template){applyTemplate(template);return}if(!item||!id){setWorkspaceMessage('Пуснете инструмента върху валидно крило.');return}const svg=(e.currentTarget as SVGGElement).ownerSVGElement,matrix=svg?.getScreenCTM(),target=state.fields.find(f=>f.id===id);if(!target||target.role!=='DOOR_LEAF'){setWorkspaceMessage('Фиксираното поле не приема обков.');return}if(!svg||!matrix){setWorkspaceMessage('Позицията не може да бъде определена.');return}const point=svg.createSVGPoint();point.x=e.clientX;point.y=e.clientY;const svgPoint=point.matrixTransform(matrix.inverse()),bounds=calculateDoorFieldBounds(calculateDoorDrawingLayout(Number(configuration.overallWidth),Number(configuration.overallHeight)).frame,target);tool(item,id,positionRatioFromSvgY(svgPoint.y,bounds.y,bounds.height));setWorkspaceMessage(item==='HINGE'?'Добавена е панта.':'Добавена е дръжка.')}
  const ratio=(e:PointerEvent<SVGGElement>,y:number,h:number)=>{const svg=e.currentTarget.ownerSVGElement,matrix=svg?.getScreenCTM();if(!svg||!matrix)return .5;const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return positionRatioFromSvgY(p.matrixTransform(matrix.inverse()).y,y,h)}
  const start=(e:PointerEvent<SVGGElement>,id:string)=>{e.preventDefault();e.stopPropagation();const item=state.hardware.find(h=>h.id===id);if(!item)return;e.currentTarget.setPointerCapture(e.pointerId);setState(selectDoorHardware(state,id));setDrag(beginHardwareDrag(id,e.pointerId,item.positionRatio))}
  const move=(e:PointerEvent<SVGGElement>,y:number,h:number)=>{if(!drag||drag.pointerId!==e.pointerId)return;e.preventDefault();setDrag(previewHardwareDrag(drag,ratio(e,y,h)))}
  const end=(e:PointerEvent<SVGGElement>)=>{if(!drag||drag.pointerId!==e.pointerId)return;e.preventDefault();e.stopPropagation();if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);const done=drag;setDrag(null);if(hardwareDragChanged(done))commit(moveDoorHardware(state,done.componentId,done.previewRatio))}
  const cancel=(element?:SVGGElement)=>{if(!drag)return;if(element?.hasPointerCapture(drag.pointerId))element.releasePointerCapture(drag.pointerId);setDrag(null)}
  const scene=useMemo(()=>buildDoorConceptualScene(state,Number(configuration.overallWidth),Number(configuration.overallHeight)),[state,configuration.overallWidth,configuration.overallHeight])
  const selectFrom3d=(id:string)=>setState(state.hardware.some(item=>item.id===id)?selectDoorHardware(state,id):selectDoorField(state,id))
  return <main className="visual-composer door-composer focused-composer">
    <header className="visual-composer-header"><div><b>Врата · {configuration.productName || 'Без име'} · {configuration.overallWidth} × {configuration.overallHeight} mm</b><p className="hybrid-neutral-status">Работна конфигурация · попълвайте само данните, които знаете. Липсващите стойности остават видимо непопълнени.</p>{hasUnusualDemonstrationalDoorProportion(configuration.overallWidth,configuration.overallHeight)&&<p className="hybrid-dimension-warning">Необичайна пропорция за врата — проверете общите размери.</p>}</div><div className="focused-composer-actions"><button onClick={onBack}>Назад към конфигурацията</button><button onClick={onCloseFacadeFlow}>Назад към FacadeFlow</button></div></header>
    <div className="visual-composer-warning">Праг: НЕРАЗРЕШЕН · {viewMode==='2D'?'Работна 2D композиция · не е производствен чертеж.':'Работна 3D визуализация · не е производствен модел.'}</div>
    <div className="visual-composer-toolbar"><button onClick={undo} disabled={!past.length}>Отмени</button><button onClick={redo} disabled={!future.length}>Повтори</button><button disabled={!state.templateId} onClick={()=>{const message=initialTemplateId?'Да се върне ли композицията към избрания в конфигурацията начален шаблон?':'Да се изчисти ли концептуалната композиция?';if(window.confirm(message)){commit(initialTemplateId?applyDoorTemplate(clearDoorComposition(),initialTemplateId):clearDoorComposition());setViewMode('2D')}}}>{initialTemplateId?'Нулирай редакциите':'Изчисти'}</button><button onClick={()=>setWorkspaceMessage('Изгледът е побран')}>Побери в изгледа</button><div className="composer-view-tabs" role="tablist" aria-label="Режим на визуализация"><button role="tab" aria-selected={viewMode==='2D'} onClick={()=>setViewMode('2D')}>2D</button><button role="tab" aria-selected={viewMode==='3D'} disabled={!state.templateId} onClick={()=>setViewMode('3D')}>3D</button></div><output>{drag?hardwareName(state,drag.componentId,true):workspaceMessage||statusText(state)}</output></div>
    <div className="visual-composer-layout"><Library state={state} open={open} setOpen={setOpen} lockedTemplateId={initialTemplateId} template={applyTemplate} tool={tool} color={(surface,c,x)=>commit(setDoorColor(state,surface,c,x))}/><section ref={stageRef} className="visual-composer-stage" onDragOver={e=>e.preventDefault()} onDrop={drop}>{viewMode==='3D'?<Conceptual3DPreview scene={scene} selectedSemanticId={state.selectedHardwareId??state.selectedFieldId} onSelect={selectFrom3d} onViewStatus={setThreeDView}/>:<><Drawing state={state} drag={drag} width={Number(configuration.overallWidth)} height={Number(configuration.overallHeight)} field={id=>setState(selectDoorField(state,id))} hardware={id=>setState(selectDoorHardware(state,id))} drop={drop} start={start} move={move} end={end} cancel={cancel}/><footer className="door-canvas-footer"><div className="door-active-field-context" aria-live="polite"><b>{field?`Работите по: ${doorFieldDisplayName(state.fields,field.id)}`:'Изберете поле от чертежа'}</b>{field?.role==='DOOR_LEAF'&&<span>Панти: {hingeSideLabel(field.hingeSide)} · Посока: {swingLabel(field.swing)}</span>}</div><output aria-live="polite">{drag?hardwareName(state,drag.componentId,true):workspaceMessage||statusText(state)}</output><div className="door-opening-legend" aria-label="Легенда за отваряне"><span>Плътна линия — навътре</span><span>Прекъсната линия — навън</span></div></footer></>}</section><Properties configuration={configuration} profiles={profiles} onConfigurationChange={onConfigurationChange} state={state} field={field} hardware={hardware} errors={errors} review={review} setReview={setReview} thresholdAcknowledged={thresholdAcknowledged} setThresholdAcknowledged={setThresholdAcknowledged} canReview={canConceptuallyReviewDoor(state,thresholdAcknowledged)&&review} commit={commit} viewMode={viewMode} threeDView={threeDView}/></div>
  </main>
}

function Library({state,open,setOpen,lockedTemplateId,template,tool,color}:{state:DoorComposition;open:string;setOpen:(v:string)=>void;lockedTemplateId:string|null;template:(id:string)=>void;tool:(v:string)=>void;color:(s:'INTERIOR'|'EXTERIOR',c:DoorColor,x?:string)=>void}){
  const selected=state.fields.find(f=>f.id===state.selectedFieldId),openingEnabled=canConfigureDoorOpening(state),hardwareEnabled=canAddDoorHardware(state)
  const visibleTemplates=lockedTemplateId?DOOR_TEMPLATES.filter(t=>t.id===lockedTemplateId):DOOR_TEMPLATES
  const section=(id:string,title:string,body:React.ReactNode)=><section className="composer-library-section"><button aria-expanded={open===id} aria-controls={`door-library-${id}`} onClick={()=>setOpen(open===id?'':id)}>{title}<span>{open===id?'−':'+'}</span></button><div id={`door-library-${id}`} hidden={open!==id}>{body}</div></section>
  const drag=(e:DragEvent,value:string)=>e.dataTransfer.setData('application/x-facadeflow-door-tool',value)
  return <aside className="visual-library"><p className="visual-field-target" aria-live="polite"><b>Активно поле:</b> {selected?doorFieldDisplayName(state.fields,selected.id):'няма избрано'}</p><div className="door-quick-hardware" aria-label="Бързо добавяне на обков"><b>Целево крило: {selected?.role==='DOOR_LEAF'?doorFieldDisplayName(state.fields,selected.id):'Не е избрано'}</b><button disabled={!hardwareEnabled} onClick={()=>tool('HINGE')}>+ Добави панта</button><button disabled={!hardwareEnabled||Boolean(selected?.handleId)} onClick={()=>tool('HANDLE')}>+ Добави дръжка</button>{!hardwareEnabled&&<small>Първо изберете лява или дясна страна на пантите.</small>}</div><h4>Библиотека</h4>
    {section('templates','Шаблони',<>{lockedTemplateId&&<p className="composer-demo-note">Началната композиция е избрана в конфигурацията. За друг тип се върнете към стъпка „Размери“.</p>}<div className="template-card-list">{visibleTemplates.map(t=><article className="composer-template-card" key={t.id} draggable={!lockedTemplateId} onDragStart={e=>{if(!lockedTemplateId)e.dataTransfer.setData('application/x-facadeflow-door-template',t.id)}}><Thumbnail id={t.id}/><b>{t.name}</b><small>Работен шаблон · {t.fields.length} полета · без обков</small><button disabled={Boolean(lockedTemplateId)} onClick={()=>template(t.id)}>{lockedTemplateId?'Избрано в конфигурацията':'Използвай шаблона'}</button></article>)}</div></>)}
    {section('infill','Пълнеж',<>{([['SOLID','Плътен панел'],['GLAZED','Остъкляване'],['GLASS_TOP_PANEL_BOTTOM','Стъкло отгоре / панел отдолу']] as const).map(([v,l])=><button key={v} draggable onDragStart={e=>drag(e,`INFILL:${v}`)} onClick={()=>tool(`INFILL:${v}`)}>{l}</button>)}</>)}
    {section('opening','Отваряне',<div className="door-opening-workflow"><ol><li>Изберете крило върху чертежа</li><li>Изберете страна на пантите</li><li>Изберете навътре или навън</li><li>Добавете панти и дръжка от секция „Обков“</li></ol><p className="door-workflow-status" aria-live="polite">{doorOpeningWorkflowStatus(state)}</p><fieldset disabled={!openingEnabled}><legend>Страна на пантите</legend><label><input type="radio" name="door-library-hinge-side" checked={selected?.hingeSide==='LEFT'} onChange={()=>tool('SIDE:LEFT')}/> Ляво</label><label><input type="radio" name="door-library-hinge-side" checked={selected?.hingeSide==='RIGHT'} onChange={()=>tool('SIDE:RIGHT')}/> Дясно</label></fieldset><fieldset disabled={!openingEnabled||!selected?.hingeSide}><legend>Посока на движение</legend><label><input type="radio" name="door-library-swing" checked={selected?.swing==='INWARD'} onChange={()=>tool('SWING:INWARD')}/> Навътре</label><label><input type="radio" name="door-library-swing" checked={selected?.swing==='OUTWARD'} onChange={()=>tool('SWING:OUTWARD')}/> Навън</label></fieldset><p><b>Панти:</b> {selected?.hingeSide==='LEFT'?'Ляво':selected?.hingeSide==='RIGHT'?'Дясно':'Не е избрано'}<br/><b>Отваряне:</b> {selected?.swing==='INWARD'?'Навътре':selected?.swing==='OUTWARD'?'Навън':'Не е избрано'}</p></div>)}
    {section('hardware','Обков',<><button disabled={!hardwareEnabled} draggable={hardwareEnabled} onDragStart={e=>hardwareEnabled&&drag(e,'HINGE')} onClick={()=>tool('HINGE')}>Добави панта</button><button disabled={!hardwareEnabled||Boolean(selected?.handleId)} draggable={hardwareEnabled&&!selected?.handleId} onDragStart={e=>hardwareEnabled&&!selected?.handleId&&drag(e,'HANDLE')} onClick={()=>tool('HANDLE')}>Добави дръжка</button>{!hardwareEnabled&&<small className="composer-disabled-reason">Първо изберете лява или дясна страна на пантите.</small>}<small>Началната позиция е ориентировъчна — преместете пантата ръчно.</small><small>Посоката навътре/навън е необходима за концептуалния преглед, но не за ръчното поставяне на обков.</small></>)}
    {section('appearance','Външен вид',<><Color label="Цвят отвътре" value={state.interiorColor} custom={state.interiorColorCustom} change={(c,x)=>color('INTERIOR',c,x)}/><Color label="Цвят отвън" value={state.exteriorColor} custom={state.exteriorColorCustom} change={(c,x)=>color('EXTERIOR',c,x)}/><small>Работни визуални цветове — наличността се проверява по официален каталог.</small></>)}
  </aside>
}
function Color({label,value,custom,change}:{label:string;value:DoorColor;custom:string;change:(c:DoorColor,x?:string)=>void}){return <label>{label}<select value={value} onChange={e=>change(e.target.value as DoorColor)}>{colors.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</select>{value==='CUSTOM'&&<input value={custom} maxLength={80} onChange={e=>change('CUSTOM',e.target.value)} placeholder="Кратко описание"/>}</label>}
function Thumbnail({id}:{id:string}){const t=DOOR_TEMPLATES.find(x=>x.id===id)!;return <svg className="composer-template-thumb door-template-thumb" viewBox="0 0 120 124" role="img" aria-label={`Разпределение на врата: ${t.name}`}><rect className="door-thumb-frame" x="33" y="3" width="54" height="116"/>{t.fields.map(f=>{const b=calculateDoorThumbnailFieldBounds(f),combined=f.infill==='GLASS_TOP_PANEL_BOTTOM',split=b.y+b.height*f.splitRatio;return <g key={f.id} data-role={f.role}>{combined?<><rect className="door-thumb-glass" x={b.x} y={b.y} width={b.width} height={split-b.y}/><rect className="door-thumb-solid" x={b.x} y={split} width={b.width} height={b.y+b.height-split}/><line className="door-thumb-divider" x1={b.x} y1={split} x2={b.x+b.width} y2={split}/></>:<rect className={f.infill==='SOLID'?'door-thumb-solid':'door-thumb-glass'} x={b.x} y={b.y} width={b.width} height={b.height}/>}</g>})}<line className="door-thumb-baseline" x1="31" y1="119" x2="89" y2="119"/></svg>}

function Drawing({state,drag,width,height,field,hardware,drop,start,move,end,cancel}:{state:DoorComposition;drag:HardwareDragSession|null;width:number;height:number;field:(id:string)=>void;hardware:(id:string)=>void;drop:(e:DragEvent,id?:string)=>void;start:(e:PointerEvent<SVGGElement>,id:string)=>void;move:(e:PointerEvent<SVGGElement>,y:number,h:number)=>void;end:(e:PointerEvent<SVGGElement>)=>void;cancel:(el?:SVGGElement)=>void}){
  if(!state.templateId)return <div className="visual-empty-drop">Изберете или плъзнете работен шаблон тук.</div>
  const layout=calculateDoorDrawingLayout(width,height),frame=layout.frame
  return <svg viewBox="0 0 800 520" role="img" aria-label={`Пропорционална концептуална композиция на врата ${width} на ${height} милиметра`}>
    <rect className="composer-frame" style={{fill:previewColor(state.interiorColor)}} x={frame.x} y={frame.y} width={frame.width} height={frame.height}/>
    {state.fields.map(f=>{
      const bounds=calculateDoorFieldBounds(frame,f),x=bounds.x,y=bounds.y,fw=bounds.width,fh=bounds.height,inset=Math.min(8,fw*.08,fh*.04),openingInset=Math.min(15,fw*.12,fh*.06),g=doorOpeningGeometry(f.hingeSide,f.swing,x+openingInset,y+openingInset,fw-openingInset*2,fh-openingInset*2),selected=state.selectedFieldId===f.id,compact=state.fields.length>2
      return <g key={f.id} role="button" tabIndex={0} aria-label={doorFieldDisplayName(state.fields,f.id)} className={`door-field-group ${selected?'active':'inactive'}`} onClick={()=>field(f.id)} onKeyDown={e=>(e.key==='Enter'||e.key===' ')&&field(f.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,f.id)}>
        <Fill field={f} x={x+inset} y={y+inset} w={fw-inset*2} h={fh-inset*2} color={state.interiorColor}/>
        {selected&&<rect className="door-field-selection-wash" x={x+inset} y={y+inset} width={fw-inset*2} height={fh-inset*2}/>}
        {g&&<path className="composer-opening" d={g.path} strokeDasharray={g.dash}/>}
        <rect x={x+inset} y={y+inset} width={fw-inset*2} height={fh-inset*2} className={`composer-field door-field-outline ${selected?'selected':''}`}/>
        <text className={`door-field-label ${compact?'compact':''}`} x={x+fw/2} y={y+Math.min(27,fh*.14)}>{doorCanvasFieldLabel(state.fields,f.id)}</text>
        {state.hardware.filter(i=>i.parentFieldId===f.id).map(i=><Hardware key={i.id} item={i} ratio={drag?.componentId===i.id?drag.previewRatio:i.positionRatio} x={x} y={y} w={fw} h={fh} selected={state.selectedHardwareId===i.id} dragging={drag?.componentId===i.id} select={hardware} start={start} move={move} end={end} cancel={cancel}/>) }
      </g>
    })}
    <Dimension {...layout.horizontalDimension} label={`${width} mm`}/><Dimension {...layout.verticalDimension} label={`${height} mm`} vertical/><line className="door-threshold" {...layout.threshold}/><text x={frame.x+frame.width/2} y={frame.y+frame.height+24}>Праг: НЕРАЗРЕШЕН</text>
  </svg>
}
function Fill({field,x,y,w,h,color}:{field:DoorComposition['fields'][number];x:number;y:number;w:number;h:number;color:DoorColor}){const panel=previewColor(color),glass='#dff2f4';if(field.role==='FIXED_GLAZING'||field.infill==='GLAZED')return <rect x={x} y={y} width={w} height={h} fill={glass}/>;if(field.infill==='SOLID')return <rect x={x} y={y} width={w} height={h} fill={panel}/>;const split=y+h*field.splitRatio;return <><rect x={x} y={y} width={w} height={split-y} fill={glass}/><rect x={x} y={split} width={w} height={y+h-split} fill={panel}/><line className="door-panel-split" x1={x} y1={split} x2={x+w} y2={split}/></>}
function Hardware({item,ratio,x,y,w,h,selected,dragging,select,start,move,end,cancel}:{item:DoorHardware;ratio:number;x:number;y:number;w:number;h:number;selected:boolean;dragging:boolean;select:(id:string)=>void;start:(e:PointerEvent<SVGGElement>,id:string)=>void;move:(e:PointerEvent<SVGGElement>,y:number,h:number)=>void;end:(e:PointerEvent<SVGGElement>)=>void;cancel:(el?:SVGGElement)=>void}){const inset=Math.min(8,w*.08,h*.04),leaf={x:x+inset,y:y+inset,width:w-inset*2,height:h-inset*2},hinge=calculateDoorHingeAnchor(leaf,item.side,ratio,8,22),px=item.kind==='HINGE'?hinge.bounds.x+hinge.bounds.width/2:item.side==='LEFT'?x+12:x+w-12,py=item.kind==='HINGE'?hinge.bounds.y+hinge.bounds.height/2:y+Math.max(14,Math.min(h-14,ratio*h)),label=item.kind==='HINGE'?'Панта':'Дръжка';return <g role="button" tabIndex={0} aria-label={`${label}, ${Math.round(ratio*100)} процента`} className={`composer-hardware-drag ${dragging?'dragging':''}`} onPointerDown={e=>start(e,item.id)} onPointerMove={e=>move(e,y,h)} onPointerUp={end} onPointerCancel={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);cancel()}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();cancel(e.currentTarget)}}} onClick={e=>{e.stopPropagation();select(item.id)}}><rect className="composer-hardware-hit" x={px-14} y={py-18} width="28" height="36" rx="7"/>{item.kind==='HANDLE'?<circle className={`composer-handle ${selected?'selected':''}`} cx={px} cy={py} r="7"/>:<rect className={`composer-hinge ${selected?'selected':''}`} {...hinge.bounds}/>}</g>}

function Properties({configuration,profiles,onConfigurationChange,state,field,hardware,errors,review,setReview,thresholdAcknowledged,setThresholdAcknowledged,canReview,commit,viewMode,threeDView}:{configuration:StructuredProfileConfiguration;profiles:CatalogueProfile[];onConfigurationChange:(patch:Partial<Pick<StructuredProfileConfiguration,'profileSystem'|'frameProfileId'|'sashProfileId'|'mullionProfileId'>>)=>void;state:DoorComposition;field:DoorComposition['fields'][number]|undefined;hardware:DoorHardware|undefined;errors:string[];review:boolean;setReview:(v:boolean)=>void;thresholdAcknowledged:boolean;setThresholdAcknowledged:(v:boolean)=>void;canReview:boolean;commit:(s:DoorComposition)=>void;viewMode:'2D'|'3D';threeDView:Conceptual3DViewSummary}){
  const incompleteLeaves=state.fields.filter(item=>item.role==='DOOR_LEAF'&&(!item.hingeSide||!item.swing)).length
  const fieldNeedsOpening=field?.role==='DOOR_LEAF'&&(!field.hingeSide||!field.swing)
  const systemName=configuration.profileSystem==='DEMO SYSTEM'?'Примерна система (служебна)':configuration.profileSystem||'Не е избрана'
  const profileName=(id:string,emptyLabel:string)=>{const profile=profiles.find(item=>item.id===id);return profile?(profile.status==='DEMONSTRATION'?`${profile.code} — служебен примерен профил`:`${profile.code} — ${profile.nameBg}`):emptyLabel}
  return <aside className="visual-properties">
    <h4>Свойства и обобщение</h4>
    <WorkingConfigurationDataPanel configuration={configuration} profiles={profiles} onUpdate={onConfigurationChange}/>
    <p className="visual-field-target"><b>Активно поле:</b> {field?doorFieldDisplayName(state.fields,field.id):'няма избрано'}</p>
    {viewMode==='3D'&&<section className="selected-component" aria-label="Състояние на 3D изгледа"><b>3D изглед</b><dl><dt>Гледна точка</dt><dd>{threeDView.label}</dd><dt>Zoom</dt><dd>{threeDView.zoom}%</dd><dt>Режим</dt><dd>Концептуален</dd><dt>Външен цвят</dt><dd>{doorColorLabel(state.exteriorColor,state.exteriorColorCustom)}</dd><dt>Вътрешен цвят</dt><dd>{doorColorLabel(state.interiorColor,state.interiorColorCustom)}</dd><dt>Видима страна</dt><dd>{threeDView.label==='Отпред'?'външна':threeDView.label==='Отзад'?'вътрешна':'смесена'}</dd></dl></section>}
    {field?<>
      <dl><dt>Целево крило</dt><dd>{doorFieldDisplayName(state.fields,field.id)}</dd><dt>Технически ID</dt><dd><small>{field.id}</small></dd><dt>Роля</dt><dd>{field.role==='DOOR_LEAF'?'Крило':'Фиксирано остъкляване'}</dd><dt>Пълнеж</dt><dd>{infillLabel(field.infill)}</dd></dl>
      {field.role==='DOOR_LEAF'&&<>
        <section className={`door-focused-status ${fieldNeedsOpening?'needs-input':'ready'}`} aria-label="Състояние на активното крило"><b>Настройки на активното крило</b><span>Страна на пантите: {hingeSideLabel(field.hingeSide)}</span><span>Посока: {swingLabel(field.swing)}</span></section>
        <label>Страна на пантите<select value={field.hingeSide??''} onChange={e=>commit(setDoorOpeningForExplicitTarget(state,field.id,(e.target.value||null) as 'LEFT'|'RIGHT'|null,field.swing))}><option value="">Не е избрана</option><option value="LEFT">Ляво</option><option value="RIGHT">Дясно</option></select></label>
        <label>Движение<select value={field.swing??''} disabled={!field.hingeSide} onChange={e=>commit(setDoorOpeningForExplicitTarget(state,field.id,field.hingeSide,(e.target.value||null) as 'INWARD'|'OUTWARD'|null))}><option value="">Не е избрано</option><option value="INWARD">Навътре</option><option value="OUTWARD">Навън</option></select></label>
        {field.infill==='GLASS_TOP_PANEL_BOTTOM'&&<label>Разделяне стъкло / панел<input type="range" min="20" max="80" value={Math.round(field.splitRatio*100)} onChange={e=>commit(setDoorInfillForExplicitTarget(state,field.id,field.infill,Number(e.target.value)/100))}/></label>}
      </>}
    </>:<p>Изберете поле от чертежа.</p>}
    {hardware&&<HardwareProperties state={state} item={hardware} commit={commit}/>}<hr/><h5>Обобщение на вратата</h5>
    <dl><dt>Изделие</dt><dd>{configuration.productName}</dd><dt>Размери</dt><dd>{configuration.overallWidth} × {configuration.overallHeight} mm</dd><dt>Система</dt><dd>{systemName}</dd><dt>Каса</dt><dd>{profileName(configuration.frameProfileId,'Не е избрана')}</dd><dt>Крило</dt><dd>{profileName(configuration.sashProfileId,'Не е избрано')}</dd><dt>Шаблон</dt><dd>{DOOR_TEMPLATES.find(t=>t.id===state.templateId)?.name??'Не е избран'}</dd><dt>Полета</dt><dd>{state.fields.length}</dd><dt>Обков</dt><dd>{state.hardware.length}</dd><dt>Праг</dt><dd>НЕРАЗРЕШЕН</dd><dt>Готово за машина</dt><dd>Не</dd></dl>
    {errors.length>0&&<section className="door-review-summary" aria-live="polite"><b>Остава за настройване</b><span>{incompleteLeaves} {incompleteLeaves===1?'крило изисква':'крила изискват'} страна на пантите и/или посока.</span><small>Работете по едно избрано крило. Подробностите за активното поле са показани по-горе.</small></section>}
    <label><input type="checkbox" checked={thresholdAcknowledged} onChange={e=>setThresholdAcknowledged(e.target.checked)}/> Разбирам, че прагът още не е определен и тази композиция не е готова за производство.</label><label><input type="checkbox" checked={review} onChange={e=>setReview(e.target.checked)}/> Проверих работната композиция.</label><button className="primary-button" disabled={!canReview} onClick={()=>commit(conceptuallyReviewDoor(state,true))}>Потвърди работната композиция</button>{!thresholdAcknowledged&&<small>За потвърждение на работната композиция отбележете, че прагът остава неразрешен.</small>}<small>Статусът остава NEEDS_REVIEW. Това не е производствено или машинно одобрение.</small>
  </aside>
}
function HardwareProperties({state,item,commit}:{state:DoorComposition;item:DoorHardware;commit:(s:DoorComposition)=>void}){return <section className="selected-component"><b>{hardwareName(state,item.id)}</b><small>Технически ID: {item.id}</small><label>Позиция по височината<input aria-label="Позиция по височината" type="range" min="0" max="100" value={Math.round(item.positionRatio*100)} onChange={e=>commit(moveDoorHardware(state,item.id,Number(e.target.value)/100))}/></label><output>{Math.round(item.positionRatio*100)}%</output>{item.kind==='HANDLE'&&<><label>Вид дръжка<select value={item.handleStyle} onChange={e=>commit(setDoorHandleStyle(state,item.id,e.target.value as NonNullable<DoorHardware['handleStyle']>,item.customDescription))}><option value="STANDARD">Стандартна</option><option value="KNOB">Топка</option><option value="PULL">Изтегляща</option><option value="CUSTOM">Друга</option></select></label>{item.handleStyle==='CUSTOM'&&<input aria-label="Описание на дръжката" value={item.customDescription??''} onChange={e=>commit(setDoorHandleStyle(state,item.id,'CUSTOM',e.target.value))}/>}</>}<button onClick={()=>commit(deleteDoorHardware(state,item.id))}>Изтрий компонента</button></section>}
function Dimension({x1,y1,x2,y2,label,vertical=false}:{x1:number;y1:number;x2:number;y2:number;label:string;vertical?:boolean}){return <g className="composer-dimension"><line x1={x1} y1={y1} x2={x2} y2={y2}/><text x={vertical?x1-8:(x1+x2)/2} y={vertical?(y1+y2)/2:y1-7} transform={vertical?`rotate(-90 ${x1-8} ${(y1+y2)/2})`:undefined}>{label}</text></g>}
const previewColor=(c:DoorColor)=>({WHITE:'#f8f8f4',ANTHRACITE:'#4b5357',BLACK:'#202629',BROWN:'#72503b',SILVER:'#bac3c5'} as Partial<Record<DoorColor,string>>)[c]??'#d7e0e2'
const doorColorLabel=(c:DoorColor,custom:string)=>c==='CUSTOM'?(custom.trim()||'Друг цвят — без описание'):({WHITE:'Бяло',ANTHRACITE:'Антрацит',BLACK:'Черно',BROWN:'Кафяво',SILVER:'Сребристо'} as Partial<Record<DoorColor,string>>)[c]??'Не е избран'
const infillLabel=(v:DoorInfill)=>({SOLID:'Плътен панел',GLAZED:'Остъкляване',GLASS_TOP_PANEL_BOTTOM:'Стъкло отгоре / панел отдолу'}[v])
const statusText=(s:DoorComposition)=>!s.templateId?'Няма композиция':validateDoorComposition(s).length?'Композицията изисква избори':'Готово за концептуална проверка'
const hardwareName=(s:DoorComposition,id:string,moving=false)=>{const item=s.hardware.find(h=>h.id===id);if(item?.kind==='HANDLE')return moving?'Преместване на дръжката':'Дръжка';const hinges=s.hardware.filter(h=>h.kind==='HINGE'&&h.parentFieldId===item?.parentFieldId).sort((a,b)=>a.positionRatio-b.positionRatio);return `${moving?'Преместване на ':''}Панта ${hinges.findIndex(h=>h.id===id)+1}`}
