import { useEffect, useMemo, useRef, useState } from 'react'
import { fitDwgView, zoomDwgView } from '../dwgBounds'
import { canvasPointToDwgWorld, DWG_SECTION_RULES, hitTestDwgSection, isDwgSectionClick } from '../dwgSectionDetection'
import { hitTestDwgVisualField, hitTestVisibleDwgText, type DwgCorrectionStep, type DwgManualTextAssignment, type DwgTextHitCandidate } from '../dwgManualTextCorrection'
import { canvasPixelsToDwgLocal, dwgCanvasFont, layoutDwgText } from '../dwgTextLayout'
import { isDwgTextVisibleAtScale } from '../dwgTextNormalization'
import type { DwgDecodeResult, DwgSection, DwgViewState } from '../dwgViewerTypes'
import type { DwgApproximateTextAssignment, DwgVisualField } from '../dwgVisualFieldDetection'

interface Props { drawing: DwgDecodeResult; visibleLayers: ReadonlySet<string>; showText: boolean; approximateText: boolean; displayAssignments: ReadonlyMap<number, DwgApproximateTextAssignment | DwgManualTextAssignment>; visualFields: readonly DwgVisualField[]; correctionStep: DwgCorrectionStep; selectedEntityIndex: number | null; dark: boolean; fitToken: number; resetToken: number; selectedSection: DwgSection | null; onSelectCorrectionText: (entityIndex: number) => void; onSelectCorrectionField: (fieldId: string) => void; onSelectSection: (sectionId: string) => void }
export function DwgCanvas({ drawing, visibleLayers, showText, approximateText, displayAssignments, visualFields, correctionStep, selectedEntityIndex, dark, fitToken, resetToken, selectedSection, onSelectCorrectionText, onSelectCorrectionField, onSelectSection }: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null), hostRef = useRef<HTMLDivElement>(null), renderedText = useRef<DwgTextHitCandidate[]>([]), drag = useRef<{ x: number; y: number; view: DwgViewState; panning: boolean } | null>(null), suppressClick = useRef(false), handledResetToken = useRef(resetToken)
  const [size, setSize] = useState({ width: 0, height: 0 }), [view, setView] = useState<DwgViewState>({ scale: 1, offsetX: 0, offsetY: 0 }), [hoveredFieldId, setHoveredFieldId] = useState<string | null>(null)
  const activeBounds = selectedSection?.bounds ?? drawing.bounds
  useEffect(() => { const observer = new ResizeObserver(([entry]) => { if (entry) setSize({ width: Math.max(320, Math.round(entry.contentRect.width)), height: Math.max(360, Math.round(entry.contentRect.height)) }) }); if (hostRef.current) observer.observe(hostRef.current); return () => observer.disconnect() }, [])
  useEffect(() => { if (!size.width || !size.height) return; /* oxlint-disable-next-line react-hooks/set-state-in-effect -- external fit command synchronizes the canvas viewport */ setView(fitDwgView(activeBounds, size.width, size.height, selectedSection ? DWG_SECTION_RULES.fitPaddingPixels : 32)) }, [activeBounds, fitToken, selectedSection, size])
  useEffect(() => { if (resetToken === handledResetToken.current || !size.width || !size.height) return; handledResetToken.current = resetToken; /* oxlint-disable-next-line react-hooks/set-state-in-effect -- external reset command synchronizes the canvas viewport */ setView(fitDwgView(activeBounds, size.width, size.height, selectedSection ? DWG_SECTION_RULES.fitPaddingPixels : 32)) }, [activeBounds, resetToken, selectedSection, size.width, size.height])
  const visibleEntities = useMemo(() => drawing.entities.map((entity, index) => ({ entity, index })).filter(({ entity }) => visibleLayers.has(entity.layer) && (showText || entity.type !== 'TEXT')), [drawing.entities, visibleLayers, showText])
  useEffect(() => {
    const canvas = canvasRef.current; if (!canvas || !size.width || !size.height) return
    const ratio = window.devicePixelRatio || 1; canvas.width = size.width * ratio; canvas.height = size.height * ratio; canvas.style.width = `${size.width}px`; canvas.style.height = `${size.height}px`
    const context = canvas.getContext('2d'); if (!context) return
    context.setTransform(ratio, 0, 0, ratio, 0, 0); context.fillStyle = dark ? '#111b20' : '#f6fafb'; context.fillRect(0, 0, size.width, size.height); context.strokeStyle = dark ? '#bce6e8' : '#163b45'; context.fillStyle = dark ? '#f0f7f7' : '#15353d'; context.lineWidth = 1; renderedText.current = []
    const map = (x: number, y: number) => ({ x: x * view.scale + view.offsetX, y: -y * view.scale + view.offsetY })
    for (const { entity, index: entityIndex } of visibleEntities) {
      context.beginPath()
      if (entity.type === 'LINE') { const a = map(entity.start.x, entity.start.y), b = map(entity.end.x, entity.end.y); context.moveTo(a.x, a.y); context.lineTo(b.x, b.y); context.stroke(); continue }
      if (entity.type === 'POLYLINE') { entity.points.forEach((point, index) => { const p = map(point.x, point.y); if (!index) context.moveTo(p.x, p.y); else context.lineTo(p.x, p.y) }); if (entity.closed) context.closePath(); context.stroke(); continue }
      if (entity.type === 'CIRCLE' || entity.type === 'ARC') { const center = map(entity.center.x, entity.center.y); context.arc(center.x, center.y, entity.radius * view.scale, entity.type === 'CIRCLE' ? 0 : -entity.endAngle, entity.type === 'CIRCLE' ? Math.PI * 2 : -entity.startAngle); context.stroke(); continue }
      if (entity.type === 'ELLIPSE') { const center = map(entity.center.x, entity.center.y), major = Math.hypot(entity.major.x, entity.major.y) * view.scale; context.ellipse(center.x, center.y, major, major * entity.ratio, -Math.atan2(entity.major.y, entity.major.x), -entity.endAngle, -entity.startAngle); context.stroke(); continue }
      if (!isDwgTextVisibleAtScale(entity.height, view.scale, showText)) continue
      const position = map(entity.position.x, entity.position.y), fontSize = Math.min(512, entity.height * view.scale), assignment = approximateText ? displayAssignments.get(entityIndex) : undefined
      context.save()
      if (assignment) { const a = map(assignment.innerBounds.minX, assignment.innerBounds.maxY), b = map(assignment.innerBounds.maxX, assignment.innerBounds.minY); context.beginPath(); context.rect(a.x, a.y, b.x - a.x, b.y - a.y); context.clip() }
      context.translate(position.x, position.y); context.rotate(-entity.rotation)
      const visualWidth = assignment ? assignment.innerBounds.maxX - assignment.innerBounds.minX : entity.referenceWidth
      const layout = layoutDwgText({ textKind: entity.textKind, displayText: entity.displayText, runs: entity.runs, referenceWidth: visualWidth, textHeight: entity.height, widthFactor: entity.widthFactor, attachmentPoint: entity.attachmentPoint, horizontalAlignment: entity.horizontalAlignment, verticalAlignment: entity.verticalAlignment, lineSpacingFactor: entity.lineSpacing, lineSpacingStyle: entity.lineSpacingStyle }, (text, run) => { context.font = dwgCanvasFont(fontSize * run.heightScale); return canvasPixelsToDwgLocal(context.measureText(text).width, view.scale, entity.widthFactor * run.widthScale) })
      context.textAlign = 'left'; context.textBaseline = 'top'
      let offsetX = 0, offsetY = 0
      if (assignment) { const corners = screenCorners(layout.bounds, position, entity.rotation, view.scale), rendered = enclosing(corners), a = map(assignment.innerBounds.minX, assignment.innerBounds.maxY), b = map(assignment.innerBounds.maxX, assignment.innerBounds.minY), sx = rendered.minX < a.x ? a.x - rendered.minX : rendered.maxX > b.x ? b.x - rendered.maxX : 0, sy = rendered.minY < a.y ? a.y - rendered.minY : rendered.maxY > b.y ? b.y - rendered.maxY : 0; offsetX = (Math.cos(entity.rotation) * sx - Math.sin(entity.rotation) * sy) / view.scale; offsetY = (Math.sin(entity.rotation) * sx + Math.cos(entity.rotation) * sy) / view.scale }
      const hitBounds = enclosing(screenCorners({ minX: layout.bounds.minX + offsetX, minY: layout.bounds.minY + offsetY, maxX: layout.bounds.maxX + offsetX, maxY: layout.bounds.maxY + offsetY }, position, entity.rotation, view.scale))
      renderedText.current.push({ entityIndex, bounds: hitBounds, unresolvedNoWidth: entity.textKind === 'MTEXT' && entity.referenceWidth === null && !displayAssignments.has(entityIndex) })
      layout.lines.forEach((line) => line.runs.forEach((run) => { context.save(); context.translate((offsetX + run.x) * view.scale, (offsetY + layout.anchorOffsetY + line.y) * view.scale); context.scale(entity.widthFactor * run.widthScale, 1); context.font = dwgCanvasFont(fontSize * run.heightScale); context.fillText(run.text.slice(0, 4096), 0, 0); context.restore() })); context.restore()
    }
    if (selectedSection) { const a = map(selectedSection.bounds.minX, selectedSection.bounds.maxY), b = map(selectedSection.bounds.maxX, selectedSection.bounds.minY); context.save(); context.strokeStyle = '#008b8b'; context.lineWidth = 2; context.setLineDash([7, 5]); context.strokeRect(a.x, a.y, b.x - a.x, b.y - a.y); context.restore() }
    const hovered = visualFields.find((field) => field.id === hoveredFieldId); if (correctionStep === 'SELECT_FIELD' && hovered) { const a = map(hovered.bounds.minX, hovered.bounds.maxY), b = map(hovered.bounds.maxX, hovered.bounds.minY); context.save(); context.strokeStyle = '#b94b86'; context.lineWidth = 3; context.setLineDash([4, 3]); context.strokeRect(a.x, a.y, b.x - a.x, b.y - a.y); context.restore() }
    const selected = renderedText.current.find((candidate) => candidate.entityIndex === selectedEntityIndex); if (selected) { context.save(); context.strokeStyle = '#7d3bb3'; context.lineWidth = 3; context.setLineDash([6, 3]); context.strokeRect(selected.bounds.minX, selected.bounds.minY, selected.bounds.maxX - selected.bounds.minX, selected.bounds.maxY - selected.bounds.minY); context.restore() }
  }, [approximateText, correctionStep, dark, displayAssignments, hoveredFieldId, selectedEntityIndex, selectedSection, showText, size, view, visibleEntities, visualFields])
  const point = (event: React.PointerEvent<HTMLCanvasElement> | React.MouseEvent<HTMLCanvasElement>) => { const rect = event.currentTarget.getBoundingClientRect(); return { canvas: { x: event.clientX - rect.left, y: event.clientY - rect.top }, world: canvasPointToDwgWorld({ x: event.clientX - rect.left, y: event.clientY - rect.top }, view) } }
  return <div ref={hostRef} className={`dwg-canvas-host ${dark ? 'dark' : ''}`}><canvas ref={canvasRef} aria-label={correctionStep === 'IDLE' ? 'Локално визуализирана read-only DWG геометрия.' : 'Ръчна визуална корекция. Изборът не променя DWG файла.'} tabIndex={0} onWheel={(event) => { event.preventDefault(); const p = point(event); setView((current) => zoomDwgView(current, event.deltaY < 0 ? 1.15 : 1 / 1.15, p.canvas.x, p.canvas.y)) }} onPointerDown={(event) => { suppressClick.current = false; event.currentTarget.setPointerCapture(event.pointerId); drag.current = { x: event.clientX, y: event.clientY, view, panning: false } }} onPointerMove={(event) => { const p = point(event); if (correctionStep === 'SELECT_FIELD' && selectedSection) setHoveredFieldId(hitTestDwgVisualField(visualFields, selectedSection.sectionId, p.world.x, p.world.y)?.id ?? null); const current = drag.current; if (!current) return; if (!current.panning && !isDwgSectionClick({ x: current.x, y: current.y }, { x: event.clientX, y: event.clientY })) { current.panning = true; suppressClick.current = true } if (current.panning) setView({ ...current.view, offsetX: current.view.offsetX + event.clientX - current.x, offsetY: current.view.offsetY + event.clientY - current.y }) }} onPointerUp={(event) => { if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); drag.current = null }} onPointerCancel={() => { suppressClick.current = true; drag.current = null }} onClick={(event) => { if (suppressClick.current) { suppressClick.current = false; return } const p = point(event); if (correctionStep === 'SELECT_TEXT') { const text = hitTestVisibleDwgText(renderedText.current, p.canvas.x, p.canvas.y); if (text) onSelectCorrectionText(text.entityIndex); return } if (correctionStep === 'SELECT_FIELD' && selectedSection) { const field = hitTestDwgVisualField(visualFields, selectedSection.sectionId, p.world.x, p.world.y); if (field) onSelectCorrectionField(field.id); return } const section = hitTestDwgSection(drawing.sections, p.world); if (section) onSelectSection(section.sectionId) }}/></div>
}

function screenCorners(bounds: { minX: number; minY: number; maxX: number; maxY: number }, position: { x: number; y: number }, rotation: number, scale: number) { return [[bounds.minX, bounds.minY], [bounds.maxX, bounds.minY], [bounds.minX, bounds.maxY], [bounds.maxX, bounds.maxY]].map(([x, y]) => ({ x: position.x + (Math.cos(rotation) * x + Math.sin(rotation) * y) * scale, y: position.y + (-Math.sin(rotation) * x + Math.cos(rotation) * y) * scale })) }
function enclosing(points: Array<{ x: number; y: number }>) { return { minX: Math.min(...points.map((point) => point.x)), minY: Math.min(...points.map((point) => point.y)), maxX: Math.max(...points.map((point) => point.x)), maxY: Math.max(...points.map((point) => point.y)) } }
