import { useEffect, useMemo, useRef, useState } from 'react'
import { calculateSha256 } from '../drawingImportHash'
import { LibreDwgWorkerDecoder } from '../libreDwgDecoder'
import { toggleDwgLayer } from '../dwgLayerState'
import { applyDwgManualAssignment, cancelDwgCorrectionStep, clearDwgManualAssignments, initialDwgCorrectionState, mergeDwgDisplayAssignments, removeDwgManualAssignment, resolveDwgManualDisplayAssignments, selectDwgCorrectionText, startDwgCorrection, stopDwgCorrection, undoDwgManualAssignment } from '../dwgManualTextCorrection'
import { DWG_LIMITS, type DwgDecodeResult, type DwgSourceMetadata } from '../dwgViewerTypes'
import { deriveDwgApproximateTextAssignments, detectDwgVisualFields } from '../dwgVisualFieldDetection'
import { detectImportFormat } from '../importSignatureInspection'
import { DwgCanvas } from './DwgCanvas'
import { DwgLayersPanel } from './DwgLayersPanel'
import { DwgSectionsPanel } from './DwgSectionsPanel'
import { DwgViewerToolbar } from './DwgViewerToolbar'
import { DwgManualCorrectionPanel } from './DwgManualCorrectionPanel'
import { completeDwgPreparationStep, moveDwgPreparationStep, startDwgSectionPreparation, type DwgSectionPreparationState } from '../dwgSectionPreparation'
import { DwgSectionPreparationPanel } from './DwgSectionPreparationPanel'
import { createDwgSectionDraft, type DwgSectionDraft } from '../dwgSectionDraft'
import { DwgSectionDraftPanel } from './DwgSectionDraftPanel'
import { addDwgVisualNote, clearDwgVisualTextEdits, initialDwgVisualTextEditorState, moveDwgVisualSource, removeDwgVisualNote, resetDwgVisualSource, selectDwgVisualSource, setDwgVisualEditorMode, setDwgVisualSourceBox, setDwgVisualSourceHidden, undoDwgVisualTextEdit, updateDwgVisualNote } from '../dwgVisualTextEditor'
import { DwgVisualTextEditorPanel } from './DwgVisualTextEditorPanel'

export function DwgViewerWorkspace({ onBack }: { onBack: () => void }) {
  const decoder = useRef<LibreDwgWorkerDecoder | null>(null), input = useRef<HTMLInputElement>(null)
  const [drawing, setDrawing] = useState<DwgDecodeResult | null>(null), [metadata, setMetadata] = useState<DwgSourceMetadata | null>(null), [visibleLayers, setVisibleLayers] = useState<Set<string>>(new Set())
  const [busy, setBusy] = useState(false), [progress, setProgress] = useState(0), [status, setStatus] = useState('Изберете локален DWG файл.'), [error, setError] = useState('')
  const [dark, setDark] = useState(false), [showText, setShowText] = useState(true), [approximateText, setApproximateText] = useState(true), [fitToken, setFitToken] = useState(0), [resetToken, setResetToken] = useState(0), [layout, setLayout] = useState('MODEL')
  const [selectedSectionId, setSelectedSectionId] = useState<string | null>(null)
  const [correction, setCorrection] = useState(initialDwgCorrectionState)
  const [preparation, setPreparation] = useState<DwgSectionPreparationState | null>(null)
  const [sectionDraft, setSectionDraft] = useState<DwgSectionDraft | null>(null)
  const [visualTextEditor, setVisualTextEditor] = useState(initialDwgVisualTextEditorState)
  const selectSection = (sectionId: string | null) => { setSelectedSectionId(sectionId); setPreparation((current) => current?.sectionId === sectionId ? current : null); setSectionDraft((current) => current?.sectionId === sectionId ? current : null) }
  const selectedSection = useMemo(() => drawing?.sections.find((section) => section.sectionId === selectedSectionId) ?? null, [drawing, selectedSectionId])
  const visualFields = useMemo(() => drawing ? detectDwgVisualFields(drawing.entities, drawing.sections, drawing.bounds, visibleLayers) : [], [drawing, visibleLayers])
  const approximateDisplay = useMemo(() => drawing ? deriveDwgApproximateTextAssignments(drawing.entities, visualFields, drawing.sections) : null, [drawing, visualFields])
  const activeManualAssignments = useMemo(() => drawing ? resolveDwgManualDisplayAssignments(correction.assignments, drawing.entities, visualFields, visibleLayers) : new Map(), [correction.assignments, drawing, visibleLayers, visualFields])
  const displayAssignments = useMemo(() => mergeDwgDisplayAssignments(approximateDisplay?.assignments ?? new Map(), activeManualAssignments), [activeManualAssignments, approximateDisplay])
  useEffect(() => () => { void decoder.current?.dispose() }, [])
  useEffect(() => { if (!selectedSectionId && correction.step === 'IDLE') return; const escape = (event: KeyboardEvent) => { if (event.key !== 'Escape') return; event.preventDefault(); event.stopPropagation(); if (correction.step !== 'IDLE') setCorrection((current) => cancelDwgCorrectionStep(current)); else { setSelectedSectionId(null); setPreparation(null); setSectionDraft(null) } }; window.addEventListener('keydown', escape, true); return () => window.removeEventListener('keydown', escape, true) }, [correction.step, selectedSectionId])
  const clear = () => { void decoder.current?.dispose(); decoder.current = null; setDrawing(null); setMetadata(null); setVisibleLayers(new Set()); setBusy(false); setProgress(0); setError(''); setStatus('Изберете локален DWG файл.'); setDark(false); setShowText(true); setApproximateText(true); setFitToken(0); setResetToken(0); setLayout('MODEL'); setSelectedSectionId(null); setCorrection(initialDwgCorrectionState()); setPreparation(null); setSectionDraft(null); setVisualTextEditor(initialDwgVisualTextEditorState()); if (input.current) input.current.value = '' }
  const toggleLayer = (name: string) => { const next = toggleDwgLayer(visibleLayers, name); setVisibleLayers(next); if (selectedSection?.boundaryLayer === name && !next.has(name)) selectSection(null) }
  const selectCorrectionText = (entityIndex: number) => { const entity = drawing?.entities[entityIndex]; if (!drawing || entity?.type !== 'TEXT' || !visibleLayers.has(entity.layer) || !showText) return; const section = drawing.sections.find((candidate) => entity.position.x > candidate.bounds.minX && entity.position.x < candidate.bounds.maxX && entity.position.y > candidate.bounds.minY && entity.position.y < candidate.bounds.maxY); if (!section) return; setSelectedSectionId(section.sectionId); setCorrection((current) => selectDwgCorrectionText(current, entityIndex)) }
  const selectCorrectionField = (fieldId: string) => { if (!drawing || correction.selectedEntityIndex === null || !selectedSection) return; const field = visualFields.find((candidate) => candidate.id === fieldId && candidate.sectionId === selectedSection.sectionId), entity = drawing.entities[correction.selectedEntityIndex]; if (!field || !entity) return; setCorrection((current) => applyDwgManualAssignment(current, field, entity)) }
  const open = async (file?: File) => {
    if (!file) return
    clear(); setBusy(true); setStatus('Проверка на локалния файл…')
    try {
      if (file.size <= 0 || file.size > DWG_LIMITS.maximumFileBytes) throw new Error(`DWG файлът трябва да бъде между 1 byte и ${DWG_LIMITS.maximumFileBytes / 1024 / 1024} MB.`)
      const bytes = await file.arrayBuffer(), signature = detectImportFormat(bytes, file.name)
      if (signature.format !== 'DWG') throw new Error('Файлът няма валидна AC10xx DWG заглавна част.')
      const sha256 = await calculateSha256(bytes)
      setMetadata({ fileName: file.name, sizeBytes: file.size, sha256, version: signature.version ?? 'AC10xx' })
      const instance = new LibreDwgWorkerDecoder((next, message) => { setProgress(next); setStatus(message) }); decoder.current = instance
      const result = await instance.decode(bytes, { maximumEntities: DWG_LIMITS.maximumEntities, maximumBlockDepth: DWG_LIMITS.maximumBlockDepth, maximumTextLength: DWG_LIMITS.maximumTextLength, maximumCoordinateMagnitude: DWG_LIMITS.maximumCoordinateMagnitude })
      setDrawing(result); setVisibleLayers(new Set(result.layers.filter((item) => item.initiallyVisible).map((item) => item.name))); setLayout('MODEL'); setProgress(1); setStatus(`Декодирани ${result.entities.length.toLocaleString('bg-BG')} визуализируеми обекта.`)
    } catch (reason) { const message = reason instanceof Error ? reason.message : 'DWG файлът не може да бъде декодиран локално.'; if (message !== 'Декодирането е прекратено.') setError(message); setStatus('Декодирането не завърши.') }
    finally { setBusy(false) }
  }
  const textChoices = useMemo(() => !drawing || !selectedSection || !showText ? [] : drawing.entities.map((entity, entityIndex) => ({ entity, entityIndex })).filter(({ entity }) => entity.type === 'TEXT' && entity.textKind === 'MTEXT' && visibleLayers.has(entity.layer) && entity.position.x > selectedSection.bounds.minX && entity.position.x < selectedSection.bounds.maxX && entity.position.y > selectedSection.bounds.minY && entity.position.y < selectedSection.bounds.maxY).map(({ entity, entityIndex }) => ({ entityIndex, unresolved: entity.type === 'TEXT' && entity.referenceWidth === null && !displayAssignments.has(entityIndex) })).sort((a, b) => Number(b.unresolved) - Number(a.unresolved) || a.entityIndex - b.entityIndex), [displayAssignments, drawing, selectedSection, showText, visibleLayers])
  const fieldChoices = useMemo(() => selectedSection ? visualFields.filter((field) => field.sectionId === selectedSection.sectionId) : [], [selectedSection, visualFields])
  const activeAssignmentIds = useMemo(() => new Set([...activeManualAssignments.values()].map((assignment) => assignment.id)), [activeManualAssignments])
  return <section className="dwg-workspace" aria-labelledby="dwg-workspace-title">
    <div className="dwg-internal-warning" role="note"><b>ВЪТРЕШЕН ПРОТОТИП · ЛИЦЕНЗЪТ НЕ Е ОДОБРЕН ЗА ВЪНШНО РАЗПРОСТРАНЕНИЕ</b><span>INTERNAL EVALUATION ONLY — EXTERNAL DISTRIBUTION NOT APPROVED</span></div>
    <header><div><span className="route-badge">DWG · READ ONLY · LOCAL</span><h3 id="dwg-workspace-title">Локален технически DWG преглед</h3><p>LibreDWG/WASM работи в изолиран browser worker. Файлът остава в паметта и не се изпраща.</p></div><button type="button" onClick={() => { clear(); onBack() }}>Назад към форматите</button></header>
    {!drawing ? <div className="dwg-file-start"><div className="drawing-drop-zone" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); void open(event.dataTransfer.files[0]) }}><b>Пуснете локален DWG файл тук</b><p>Максимум 20 MB · AC10xx · без upload, conversion или export.</p><input ref={input} type="file" accept=".dwg,.DWG,application/acad,application/x-dwg,image/vnd.dwg" disabled={busy} onChange={(event) => void open(event.target.files?.[0])}/></div>{busy && <div className="dwg-progress" aria-live="polite"><progress max="1" value={progress}/><span>{status}</span><button type="button" onClick={() => { decoder.current?.cancel(); setBusy(false); setStatus('Декодирането е прекратено.') }}>Прекрати</button></div>}{error && <p className="field-error" role="alert">{error}</p>}</div> : <>
      <div className="dwg-source-meta"><span><b>{metadata?.fileName}</b></span><span>{((metadata?.sizeBytes ?? 0) / 1024 / 1024).toFixed(2)} MB</span><span>{metadata?.version}</span><span title={metadata?.sha256}>SHA-256: {metadata?.sha256}</span><button type="button" onClick={clear}>Премахни файла</button></div>
      <DwgViewerToolbar dark={dark} showText={showText} approximateText={approximateText} layouts={drawing.layouts} selectedLayout={layout} onFit={() => { selectSection(null); setFitToken((value) => value + 1) }} onReset={() => setResetToken((value) => value + 1)} onDark={() => setDark((value) => !value)} onText={() => setShowText((value) => !value)} onApproximateText={() => setApproximateText((value) => !value)} onLayout={setLayout}/>
      <div className="dwg-approximate-status" role="status"><span>Приблизителният режим използва рамките на чертежа само за по-четимо визуално подреждане. Не е източник на производствени данни.</span>{approximateDisplay && <small>Source width: {approximateDisplay.summary.sourceWidthTexts} · Приблизително ограничени: {approximateText ? approximateDisplay.summary.approximateContainedTexts : 0} · Неразрешени: {approximateDisplay.summary.unresolvedTexts}</small>}</div>
      <DwgManualCorrectionPanel state={correction} textChoices={textChoices} fieldChoices={fieldChoices} activeAssignmentIds={activeAssignmentIds} onStart={() => setCorrection((current) => startDwgCorrection(current))} onCancel={() => setCorrection((current) => stopDwgCorrection(current))} onText={selectCorrectionText} onField={selectCorrectionField} onUndo={() => setCorrection((current) => undoDwgManualAssignment(current))} onRemove={(id) => setCorrection((current) => removeDwgManualAssignment(current, id))} onClear={() => { if (correction.assignments.length && window.confirm('Да бъдат ли изчистени всички ръчни визуални корекции за текущата сесия?')) setCorrection((current) => clearDwgManualAssignments(current)) }}/>
      {drawing.layouts.some((item) => !item.renderable) && <p id="dwg-layout-status" className="dwg-layout-status" role="status"><b>Model е активният поддържан изглед.</b> Открит е Paper Space layout, но текущият decoder не предоставя неговите entities и viewport данни. Файлът не се изпраща никъде и не се показва празен или симулиран лист.</p>}
      <DwgSectionsPanel sections={drawing.sections} selectedSectionId={selectedSectionId} onSelect={(sectionId) => selectSection(sectionId)} onBack={() => selectSection(null)}/>
      {selectedSection && <p className="dwg-section-status" role="status"><b>Избрана секция:</b> {drawing.sections.indexOf(selectedSection) + 1}. Нулиране възстановява fit на секцията; Escape или „Назад към целия чертеж“ връща целия Model.</p>}
      {selectedSection && (!preparation || preparation.sectionId !== selectedSection.sectionId) && <div className="dwg-preparation-start"><div><b>Готови ли сте да прегледате секцията?</b><span>Помощникът води през размери, каса, делители, крила и човешка проверка.</span></div><button type="button" onClick={() => setPreparation(startDwgSectionPreparation(selectedSection.sectionId))}>Използвай тази секция</button></div>}
      {selectedSection && preparation?.sectionId === selectedSection.sectionId && <DwgSectionPreparationPanel sectionNumber={drawing.sections.indexOf(selectedSection) + 1} state={preparation} onPrevious={() => setPreparation((current) => current ? moveDwgPreparationStep(current, -1) : current)} onCompleteStep={() => setPreparation((current) => current ? completeDwgPreparationStep(current) : current)} onStartDraft={() => setSectionDraft((current) => current ?? createDwgSectionDraft(selectedSection.sectionId, metadata?.sha256 ?? '', drawing.sections.indexOf(selectedSection) + 1))} onClose={() => { setPreparation(null); setSectionDraft(null) }}/>}
      {selectedSection && sectionDraft?.sectionId === selectedSection.sectionId && <DwgSectionDraftPanel draft={sectionDraft} onChange={setSectionDraft} onClose={() => setSectionDraft(null)}/>}
      <DwgVisualTextEditorPanel state={visualTextEditor} onMode={(mode) => { setCorrection((current) => stopDwgCorrection(current)); setVisualTextEditor((current) => setDwgVisualEditorMode(current, mode)) }} onState={setVisualTextEditor} onHide={(hidden) => setVisualTextEditor((current) => current.selectedEntityIndex === null ? current : setDwgVisualSourceHidden(current, current.selectedEntityIndex, hidden))} onResetSource={() => setVisualTextEditor((current) => current.selectedEntityIndex === null ? current : resetDwgVisualSource(current, current.selectedEntityIndex))} onUndo={() => setVisualTextEditor((current) => undoDwgVisualTextEdit(current))} onClear={() => { if (window.confirm('Да бъдат ли изчистени всички визуални текстови редакции?')) setVisualTextEditor((current) => clearDwgVisualTextEdits(current)) }} onUpdateNote={(id, text) => setVisualTextEditor((current) => updateDwgVisualNote(current, id, { text }))} onRemoveNote={(id) => setVisualTextEditor((current) => removeDwgVisualNote(current, id))}/>
      <div className="dwg-view-grid"><DwgCanvas drawing={drawing} visibleLayers={visibleLayers} showText={showText} approximateText={approximateText} displayAssignments={displayAssignments} visualFields={visualFields} correctionStep={correction.step} selectedEntityIndex={correction.selectedEntityIndex} visualTextEditor={visualTextEditor} dark={dark} fitToken={fitToken} resetToken={resetToken} selectedSection={selectedSection} onSelectCorrectionText={selectCorrectionText} onSelectCorrectionField={selectCorrectionField} onSelectVisualSource={(entityIndex) => setVisualTextEditor((current) => selectDwgVisualSource(current, entityIndex))} onMoveVisualSource={(entityIndex, dx, dy) => setVisualTextEditor((current) => moveDwgVisualSource(current, entityIndex, dx, dy))} onSetVisualSourceBox={(entityIndex, bounds) => setVisualTextEditor((current) => setDwgVisualSourceBox(current, entityIndex, bounds))} onPlaceVisualNote={(position) => setVisualTextEditor((current) => addDwgVisualNote(current, position))} onSelectSection={(sectionId) => selectSection(sectionId)}/><DwgLayersPanel layers={drawing.layers} visible={visibleLayers} onToggle={toggleLayer}/></div>
      <div className="dwg-inspection-grid"><section><h4>Обекти</h4>{Object.entries(drawing.entityCounts).sort().map(([type, count]) => <span key={type}>{type}: <b>{count}</b></span>)}</section><section><h4>Неподдържани / ресурси</h4>{drawing.warnings.length ? drawing.warnings.map((warning, index) => <p key={`${warning.code}-${index}`}>{warning.message}</p>) : <p>Няма отчетени предупреждения.</p>}</section><section><h4>Граници на Model space</h4><code>X {drawing.bounds.minX.toFixed(2)}…{drawing.bounds.maxX.toFixed(2)}<br/>Y {drawing.bounds.minY.toFixed(2)}…{drawing.bounds.maxY.toFixed(2)}</code></section></div>
      <footer className="dwg-safety-footer"><b>READ ONLY · СИМУЛАЦИЯ · МАШИННА ГОТОВНОСТ: НЕ</b><span>Геометрията не е производствено одобрена. Няма редактиране, export, операции или машинна връзка.</span></footer>
    </>}
  </section>
}
