import { useState } from 'react'
import { ocrLimits } from '../ocrLimits'
import type { OcrAuditEntry, OcrCandidate, OcrJob, OcrTargetField } from '../ocrTypes'

interface Props {
  jobs: OcrJob[]; activeJobId: string | null; audit: OcrAuditEntry[]
  cropDataUrl?: string
  onCandidate: (jobId: string, candidate: OcrCandidate, action: 'ACCEPT' | 'REJECT' | 'EDIT') => void
  onApply: (jobId: string, candidate: OcrCandidate, field: OcrTargetField, value: string) => void
}
const targets: Record<OcrTargetField, string> = { projectReference: 'Проект / референция', productReference: 'Референция на изделието', width: 'Ширина', height: 'Височина', drawingPosition: 'Позиция в чертежа', notes: 'Общи бележки' }

export function OcrSuggestionsPanel({ jobs, activeJobId, audit, cropDataUrl, onCandidate, onApply }: Props) {
  const [edits, setEdits] = useState<Record<string, string>>({})
  const [target, setTarget] = useState<Record<string, OcrTargetField>>({})
  const job = jobs.find(({ id }) => id === activeJobId) ?? jobs[0]
  if (!job) return <section className="ocr-suggestions"><h3>OCR предложения</h3><p>Все още няма локален OCR резултат.</p></section>
  return <section className="ocr-suggestions" aria-labelledby="ocr-suggestions-title"><h3 id="ocr-suggestions-title">OCR предложения</h3><p className="ocr-warning">OCR резултатът може да е грешен и трябва да бъде проверен по оригиналния чертеж.</p><dl className="ocr-job-meta"><div><dt>Състояние</dt><dd>{job.state}</dd></div><div><dt>Увереност</dt><dd>{job.confidence.toFixed(1)}%</dd></div><div><dt>Език</dt><dd>English / Latin / числа</dd></div><div><dt>Страница</dt><dd>{job.sourcePage}</dd></div><div><dt>Зона</dt><dd>{Math.round(job.selection.x)}, {Math.round(job.selection.y)} · {Math.round(job.selection.width)} × {Math.round(job.selection.height)} px</dd></div><div><dt>Създадено</dt><dd>{job.createdAt}</dd></div><div><dt>SHA-256</dt><dd title={job.sourceSha256}>{job.sourceSha256.slice(0, 16)}…</dd></div></dl>{cropDataUrl && <div className="ocr-evidence-crop" id="ocr-evidence-crop"><b>Извадка за сравнение</b><img src={cropDataUrl} alt="OCR извадка за сравнение с предложенията"/></div>}<label>Суров OCR резултат<textarea readOnly value={job.rawText}/></label><label>Нормализиран текст<textarea readOnly value={job.normalizedText}/></label>{job.items.length > 0 && <details><summary>Разпознати редове</summary><ul>{job.items.map((item, index) => <li key={`${index}-${item.text}`}>{item.text} — {item.confidence.toFixed(1)}%</li>)}</ul></details>}
    <div className="ocr-candidate-list">{job.candidates.map((candidate) => { const value = edits[candidate.id] ?? candidate.normalizedValue; const low = candidate.ocrConfidence < ocrLimits.lowConfidenceThreshold || candidate.parserConfidence < ocrLimits.lowConfidenceThreshold; return <article key={candidate.id}><div><b>{candidate.type}</b><span>{candidate.rawSourceText}</span><small>OCR {candidate.ocrConfidence.toFixed(1)}% · parser {candidate.parserConfidence}% · {candidate.status}</small>{low && <strong className="low-confidence">Ниска увереност — сравнете с източника</strong>}<a href="#ocr-evidence-crop">Сравни с извадката</a></div><label>Редактирана стойност<input value={value} onChange={(event) => setEdits({ ...edits, [candidate.id]: event.target.value })}/></label><div className="ocr-review-actions"><button type="button" onClick={() => onCandidate(job.id, { ...candidate, normalizedValue: value }, edits[candidate.id] === undefined ? 'ACCEPT' : 'EDIT')}>Приеми</button><button type="button" onClick={() => onCandidate(job.id, candidate, 'REJECT')}>Отхвърли</button></div>{candidate.status === 'ACCEPTED' && <div className="ocr-apply"><label>Целево поле<select value={target[candidate.id] ?? 'notes'} onChange={(event) => setTarget({ ...target, [candidate.id]: event.target.value as OcrTargetField })}>{Object.entries(targets).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><button type="button" onClick={() => onApply(job.id, { ...candidate, normalizedValue: value }, target[candidate.id] ?? 'notes', value)}>Приложи с потвърждение</button></div>}</article> })}</div><details><summary>OCR audit trail ({audit.length})</summary><ul>{audit.map((entry) => <li key={entry.id}>{entry.timestamp} · {entry.action} · {entry.appliedField ?? 'предложение'} · humanConfirmed: {String(entry.humanConfirmed)}</li>)}</ul></details>
  </section>
}
