import type { MachiningOperation, OperationDraft } from '../types'
import { ContextHelp } from './ContextHelp'
interface Props { draft: OperationDraft; operations: MachiningOperation[]; editingId: string | null; errors: string[]; onDraft: (v: OperationDraft) => void; onSubmit: () => void; onEdit: (v: MachiningOperation) => void; onDelete: (id: string) => void; onMove: (i: number, d: -1 | 1) => void; onCancel: () => void }
export function OperationsPanel(props: Props) {
  const set = (key: keyof OperationDraft, value: string) => props.onDraft({ ...props.draft, [key]: key === 'type' ? value : Number(value) } as OperationDraft)
  const numberField = (label: string, key: keyof OperationDraft, helpId?: string) => <label>{label} {helpId && <ContextHelp helpId={helpId}/>} <span>mm</span><input type="number" min="0" step="0.1" value={String(props.draft[key])} onChange={(e) => set(key, e.target.value)} /></label>
  return <aside className="panel operations-panel" data-help-id="operations-panel" aria-labelledby="operations-title"><div className="panel-heading"><span className="step">02</span><div><h2 id="operations-title">Операции</h2><p>Ред на изпълнение</p></div></div><form onSubmit={(e) => { e.preventDefault(); props.onSubmit() }} noValidate><label>Тип операция<select value={props.draft.type} onChange={(e) => set('type', e.target.value)}><option value="drill">Пробиване</option><option value="mill">Фрезоване</option></select></label><div className="field-grid three">{numberField('X', 'x', 'x')}{numberField('Y', 'y', 'y')}{numberField('Z', 'z', 'z')}</div><div className="field-grid">{props.draft.type === 'drill' ? numberField('Диаметър', 'diameter', 'diameter') : <>{numberField('Дължина канал', 'slotLength')}{numberField('Ширина канал', 'slotWidth')}</>}{numberField('Дълбочина', 'depth', 'depth')}</div>{props.errors.length > 0 && <div id="operation-form-errors" className="inline-errors" role="alert"><b>Проверете операцията:</b><ul>{props.errors.map((error) => <li key={error}>{error}</li>)}</ul></div>}<div className="form-actions"><button className="primary" type="submit" aria-describedby={props.errors.length > 0?'operation-form-errors':undefined}>{props.editingId ? 'Запази промените' : '＋ Добави операция'}</button>{props.editingId && <button type="button" className="text-button" onClick={props.onCancel}>Отказ</button>}</div></form>
    <div className="operation-list"><h3>Последователност <span>{props.operations.length}</span></h3>{props.operations.length === 0 ? <p className="empty">Все още няма добавени операции.</p> : props.operations.map((op, index) => <article className="operation-card" key={op.id}><span className={`op-index ${op.type}`}>{index + 1}</span><div className="op-copy"><b>{op.type === 'drill' ? 'Пробиване' : 'Фрезоване'}</b><small>X {op.x} · Y {op.y} · ↓ {op.depth} mm</small></div><div className="card-actions"><button type="button" aria-label={`Премести операция ${index + 1} нагоре`} disabled={index === 0} onClick={() => props.onMove(index, -1)}>↑</button><button type="button" aria-label={`Премести операция ${index + 1} надолу`} disabled={index === props.operations.length - 1} onClick={() => props.onMove(index, 1)}>↓</button><button type="button" aria-label={`Редактирай операция ${index + 1}`} onClick={() => props.onEdit(op)}>✎</button><button type="button" aria-label={`Изтрий операция ${index + 1}`} onClick={() => props.onDelete(op.id)}>×</button></div></article>)}</div></aside>
}
