import { Component, useEffect, useMemo, useState, type ErrorInfo, type ReactNode } from 'react'
import type { DimensionAnnotation, DimensionVisibility } from '../dimensionTypes'
import { defaultThreeDVisibility, type CameraPreset, type Product3DScene as SceneData, type ThreeDVisibility } from '../threeDTypes'
import { Product3DControls } from './Product3DControls'
import { Product3DScene } from './Product3DScene'
import { Selected3DComponentInfo } from './Selected3DComponentInfo'

interface Props { buildScene: (depth: number) => SceneData; selectedId: string | null; nominalLengths?: Record<string, number>; annotations: DimensionAnnotation[]; dimensionVisibility: DimensionVisibility; depth: number; onDepth: (value: number) => void; onSelect: (id: string) => void; onOpenComponent?: (id: string) => void; onUnavailable?: () => void }
interface BoundaryProps { children: ReactNode; onFailure: () => void }
class ThreeDErrorBoundary extends Component<BoundaryProps, { failed: boolean }> { state = { failed: false }; static getDerivedStateFromError() { return { failed: true } } componentDidCatch(_error: Error, _info: ErrorInfo) { this.props.onFailure() } render() { return this.state.failed ? null : this.props.children } }
function webGLAvailable() { try { const canvas = document.createElement('canvas'); return Boolean(canvas.getContext('webgl2') || canvas.getContext('webgl')) } catch { return false } }

export function Product3DPreview({ buildScene, selectedId, nominalLengths = {}, annotations, dimensionVisibility, depth, onDepth, onSelect, onOpenComponent, onUnavailable }: Props) {
  const [preset, setPreset] = useState<CameraPreset>('ISOMETRIC'), [visibility, setVisibility] = useState<ThreeDVisibility>(defaultThreeDVisibility), [exploded, setExploded] = useState(0), [opening, setOpening] = useState(0), [failed, setFailed] = useState(() => !webGLAvailable()), [announcement, setAnnouncement] = useState('3D прегледът е активен.')
  const scene = useMemo(() => buildScene(depth), [buildScene, depth]), selected = scene.nodes.find((node) => node.id === selectedId), openingAvailable = scene.nodes.some((node) => node.role === 'SASH' && node.openingConfirmed)
  useEffect(() => { if (failed) { onUnavailable?.(); window.dispatchEvent(new CustomEvent('facadeflow-3d-unavailable')) } }, [failed, onUnavailable])
  if (failed) return <div className="three-d-fallback" role="alert"><b>3D визуализацията не е достъпна на този компютър. Използвайте 2D чертежа.</b><p>Останалата част от приложението продължава да работи.</p></div>
  return <section className="product-3d-preview" aria-labelledby="three-d-title" aria-describedby="three-d-boundary">
    <header><div><h3 id="three-d-title">Интерактивен концептуален 3D преглед</h3><p id="three-d-boundary">Концептуален 3D преглед. Дебелините и сеченията не са технологично потвърдени.</p></div><span className="preview-badge">CONCEPTUAL ONLY</span></header>
    <div className="three-d-layout"><Product3DControls preset={preset} visibility={visibility} depth={depth} exploded={exploded} opening={opening} openingAvailable={openingAvailable} onPreset={(value) => { setPreset(value); setAnnouncement(`Камера: ${value}.`) }} onVisibility={setVisibility} onDepth={onDepth} onExploded={setExploded} onOpening={setOpening}/><div className="three-d-stage"><ThreeDErrorBoundary onFailure={() => setFailed(true)}><Product3DScene scene={scene} selectedId={selectedId} preset={preset} visibility={visibility} exploded={exploded} opening={opening} annotations={annotations} dimensionVisibility={dimensionVisibility} onSelect={(id) => { onSelect(id); setAnnouncement(`Избран компонент ${id}.`) }} onReady={() => setAnnouncement('3D сцената е готова.')}/></ThreeDErrorBoundary>{visibility.labels && <div className="three-d-label-list" aria-hidden="true">{scene.nodes.filter((node) => node.selectable).map((node) => <span key={node.id}>{node.id}</span>)}</div>}<div className="orientation-indicator">X → · Y ↑ · Z отпред</div></div></div>
    <div className="three-d-measurements">{annotations.length ? <><span>Ширина: {scene.bounds.width} mm</span><span>Височина: {scene.bounds.height} mm</span><span>Концептуална дълбочина: {scene.bounds.depth} mm</span></> : <strong>Неразрешен размер</strong>}</div>
    <Selected3DComponentInfo node={selected} nominalLength={selected ? nominalLengths[selected.id] : undefined} onOpen={selected?.selectable && onOpenComponent ? () => onOpenComponent(selected.id) : undefined}/><div className="accessible-3d-list"><h4>Достъпен списък на 3D компонентите</h4>{scene.nodes.filter((node) => node.selectable).map((node) => <button type="button" key={node.id} aria-pressed={selectedId === node.id} onClick={() => onSelect(node.id)}>{node.id} — {node.role}</button>)}</div><p className="sr-only" aria-live="polite">{announcement}</p>
  </section>
}
