import { useEffect, useMemo, useRef } from 'react'
import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'
import type { DimensionAnnotation, DimensionVisibility } from '../dimensionTypes'
import { cameraPosition } from '../threeDCameraPresets'
import { selected3DColor, threeDColors } from '../threeDMaterials'
import type { CameraPreset, Component3DNode, Product3DScene as SceneData, ThreeDVisibility } from '../threeDTypes'
import { ProductDimensions3D } from './ProductDimensions3D'

interface Props { scene: SceneData; selectedId: string | null; preset: CameraPreset; visibility: ThreeDVisibility; exploded: number; opening: number; annotations: DimensionAnnotation[]; dimensionVisibility: DimensionVisibility; onSelect: (id: string) => void; onReady?: () => void }
const visibleNode = (node: Component3DNode, visibility: ThreeDVisibility) => node.role === 'FRAME' ? visibility.frame : node.role === 'DIVIDER' ? visibility.dividers : node.role === 'SASH' ? visibility.sashes : visibility.glazing

function CameraRig({ scene, preset, onReady }: Pick<Props, 'scene' | 'preset' | 'onReady'>) { const { camera, gl } = useThree(), controls = useRef<OrbitControls | null>(null), ready = useRef(onReady); useEffect(() => { ready.current = onReady }, [onReady]); useEffect(() => { const instance = new OrbitControls(camera, gl.domElement); instance.enableDamping = !window.matchMedia('(prefers-reduced-motion: reduce)').matches; instance.screenSpacePanning = true; instance.target.set(0, 0, 0); controls.current = instance; ready.current?.(); return () => { instance.dispose(); controls.current = null } }, [camera, gl]); useEffect(() => { const position = cameraPosition(preset, scene.bounds); camera.position.set(position.x, position.y, position.z); camera.up.set(0, 1, 0); camera.lookAt(0, 0, 0); controls.current?.target.set(0, 0, 0); controls.current?.update() }, [camera, preset, scene.bounds]); useFrame(() => controls.current?.update()); return null }
function NodeMesh({ node, selected, visibility, exploded, onSelect }: { node: Component3DNode; selected: boolean; visibility: ThreeDVisibility; exploded: number; onSelect: () => void }) { if (!visibleNode(node, visibility)) return null; const zOffset = (node.role === 'GLAZING' || node.role === 'PANEL' ? -1 : 1) * exploded * .45; return <mesh position={[node.position.x, node.position.y, node.position.z + zOffset]} rotation={[node.rotation.x, node.rotation.y, node.rotation.z]} onClick={(event) => { event.stopPropagation(); if (node.selectable) onSelect() }}><boxGeometry args={[node.dimensions.x, node.dimensions.y, node.dimensions.z]}/><meshStandardMaterial color={selected ? selected3DColor : threeDColors[node.role]} transparent={node.role === 'GLAZING' || visibility.transparent} opacity={node.role === 'GLAZING' ? .34 : visibility.transparent ? .55 : 1} wireframe={visibility.wireframe}/></mesh> }
function SceneContent(props: Props) {
  const groups = useMemo(() => { const map = new Map<string, Component3DNode[]>(); props.scene.nodes.forEach((node) => { const key = node.openingGroupId ?? `single-${node.id}`; map.set(key, [...(map.get(key) ?? []), node]) }); return [...map.entries()] }, [props.scene.nodes])
  return <><ambientLight intensity={1.7}/><directionalLight position={[500, 800, 900]} intensity={2.2}/>{props.visibility.grid && <gridHelper args={[Math.max(props.scene.bounds.width, props.scene.bounds.height) * 1.8, 20, '#78919a', '#c7d2d5']} position={[0, -props.scene.bounds.height / 2 - 40, 0]}/>}<axesHelper args={[Math.max(props.scene.bounds.width, props.scene.bounds.height) * .16]}/>{groups.map(([key, nodes]) => { const opening = nodes[0]?.openingConfirmed ? props.opening * Math.PI / 180 * (nodes[0].openingDirection === 'right' ? -1 : 1) : 0; const pivotX = nodes[0]?.openingDirection === 'right' ? Math.max(...nodes.map((item) => item.position.x + item.dimensions.x / 2)) : Math.min(...nodes.map((item) => item.position.x - item.dimensions.x / 2)); if (nodes[0]?.openingGroupId) return <group key={key} position={[pivotX, 0, 0]} rotation={[0, opening, 0]}>{nodes.map((node) => <group key={node.id} position={[-pivotX, 0, 0]}><NodeMesh node={node} selected={props.selectedId === node.id} visibility={props.visibility} exploded={props.exploded} onSelect={() => props.onSelect(node.id)}/></group>)}</group>; return nodes.map((node) => <NodeMesh key={node.id} node={node} selected={props.selectedId === node.id} visibility={props.visibility} exploded={props.exploded} onSelect={() => props.onSelect(node.id)}/>) })}<ProductDimensions3D annotations={props.annotations} visibility={props.dimensionVisibility} width={props.scene.bounds.width} height={props.scene.bounds.height}/><CameraRig scene={props.scene} preset={props.preset} onReady={props.onReady}/></>
}
export function Product3DScene(props: Props) { return <Canvas className="three-d-canvas" dpr={[1, 1.5]} camera={{ near: 1, far: 20000 }} onPointerMissed={() => undefined}><SceneContent {...props}/></Canvas> }
