import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { calculateTemplateDimensions } from '../dimensionCalculations'
import { defaultDimensionVisibility, type ImportedDimensionEvidence } from '../dimensionTypes'
import { calculateProductComponents } from '../productCalculations'
import type { ProductComponent, ProductParameters } from '../productTypes'
import { getProductTemplate, templateCategoryLabels } from '../productTemplates'
import { templateProductTo3DScene } from '../templateProduct3DAdapter'
import { DEFAULT_CONCEPTUAL_DEPTH_MM } from '../threeDSceneBuilder'
import { verifiedImportTo3DScene } from '../verifiedImport3DAdapter'
import { DimensionControls } from './DimensionControls'
import { OpeningLegend } from './OpeningLegend'
import { Product3DPreview } from './Product3DPreview'
import { ProductDrawing } from './ProductDrawing'

interface Props { product: ProductParameters; project: string; profileCode: string; profileSystem: string; selectedComponentId: string | null; onSelectComponent: (componentId: string) => void; onOpenComponent: (component: ProductComponent) => void; onClose: () => void; importedSource?: boolean; verifiedImport?: boolean; importedDimensionEvidence?: ImportedDimensionEvidence[] }

export function ProductPreview({ product, project, profileCode, profileSystem, selectedComponentId, onSelectComponent, onOpenComponent, onClose, importedSource = false, verifiedImport = false, importedDimensionEvidence = [] }: Props) {
  const closeButton = useRef<HTMLButtonElement>(null), modal = useRef<HTMLElement>(null)
  const template = useMemo(() => getProductTemplate(product.templateId), [product.templateId]), components = useMemo(() => calculateProductComponents(product, profileCode), [product, profileCode])
  const [view, setView] = useState<'2D' | '3D' | 'SPLIT'>('2D'), [conceptualDepth, setConceptualDepth] = useState(DEFAULT_CONCEPTUAL_DEPTH_MM), [dimensionVisibility, setDimensionVisibility] = useState(defaultDimensionVisibility)
  const build3DScene = useCallback((depth: number) => verifiedImport ? verifiedImportTo3DScene({ status: 'VERIFIED', product, profileCode }, depth) : templateProductTo3DScene(product, profileCode, depth), [product, profileCode, verifiedImport])
  const annotations = useMemo(() => importedSource && !verifiedImport ? [] : calculateTemplateDimensions(product, components, selectedComponentId, conceptualDepth, importedDimensionEvidence), [product, components, selectedComponentId, conceptualDepth, importedDimensionEvidence, importedSource, verifiedImport])
  const nominalLengths = Object.fromEntries(components.map((component) => [component.id, component.nominalLength]))
  useEffect(() => { const fallback = () => setView('2D'); window.addEventListener('facadeflow-3d-unavailable', fallback); return () => window.removeEventListener('facadeflow-3d-unavailable', fallback) }, [])
  useEffect(() => { const previouslyFocused = document.activeElement instanceof HTMLElement ? document.activeElement : null; closeButton.current?.focus(); const handleKey = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); if (event.key !== 'Tab') return; const focusable = modal.current?.querySelectorAll<HTMLElement>('button:not([disabled]), [href], [tabindex]:not([tabindex="-1"])'); if (!focusable?.length) return; const first = focusable[0], last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus() } if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus() } }; document.addEventListener('keydown', handleKey); return () => { document.removeEventListener('keydown', handleKey); previouslyFocused?.focus() } }, [onClose])
  return <div className="preview-overlay" role="presentation"><section ref={modal} className="preview-modal" role="dialog" aria-modal="true" aria-labelledby="preview-title" aria-describedby="preview-safety"><div className="preview-header"><div><span className="preview-badge">СИМУЛАЦИЯ</span><h2 id="preview-title">Визуализация на изделието</h2><p>{templateCategoryLabels[template.libraryCategory]} · Референтна схема {template.displayNumber} — {template.name} · {profileSystem} · {project}</p></div><button ref={closeButton} type="button" className="preview-close" aria-label="Затвори визуализацията" onClick={onClose}>×</button></div>
    <OpeningLegend/><div className="view-switch" role="group" aria-label="Изглед на изделието"><button type="button" aria-pressed={view === '2D'} onClick={() => setView('2D')}>2D чертеж</button><button type="button" aria-pressed={view === '3D'} onClick={() => setView('3D')}>3D преглед</button><button type="button" aria-pressed={view === 'SPLIT'} onClick={() => setView('SPLIT')}>Разделен изглед</button></div><DimensionControls value={dimensionVisibility} onChange={setDimensionVisibility} unresolved={importedSource && !verifiedImport}/>
    <div className={`preview-content ${view === 'SPLIT' ? 'split-preview-content' : ''}`}>{view !== '3D' && <div className="product-drawing-wrap"><ProductDrawing product={product} template={template} selectedComponentId={selectedComponentId} onSelectComponent={onSelectComponent} annotations={annotations} dimensionVisibility={dimensionVisibility}/><p className="dimension-legend">Размерите са проектни/геометрични. Производствените отнемания и допуски не са приложени.</p></div>}{view !== '2D' && <Product3DPreview buildScene={build3DScene} selectedId={selectedComponentId} nominalLengths={nominalLengths} annotations={annotations} dimensionVisibility={dimensionVisibility} depth={conceptualDepth} onDepth={setConceptualDepth} onSelect={onSelectComponent} onOpenComponent={(id) => { const component = components.find((item) => item.id === id); if (component) onOpenComponent(component) }}/>}<section className="component-list" aria-labelledby="component-list-title"><h3 id="component-list-title">Симулационен компонентен списък</h3><div className="component-table-wrap"><table><thead><tr><th>№ / ID</th><th>Роля</th><th>Код</th><th>Номинална дължина</th><th>Бр.</th><th>Примерни ъгли Л/Д</th><th></th></tr></thead><tbody>{components.map((component) => { const selected = component.id === selectedComponentId; return <tr key={component.id} className={selected ? 'selected-component-row' : undefined} aria-selected={selected}><td><b>{component.number}</b><small>{component.id}</small></td><td>{component.role}</td><td>{component.profileCode || 'Без код'}</td><td>{component.nominalLength} mm</td><td>{component.quantity}</td><td>{component.suggestedLeftAngle}° / {component.suggestedRightAngle}°</td><td><button type="button" className="open-component-button" aria-pressed={selected} onFocus={() => onSelectComponent(component.id)} onClick={() => onOpenComponent(component)}>Отвори профила</button></td></tr> })}</tbody></table></div></section></div>
    <div className="dimension-summary" aria-label="Текстово обобщение на размерите">{annotations.filter((item) => item.type === 'OVERALL_WIDTH' || item.type === 'OVERALL_HEIGHT' || item.id.includes(selectedComponentId ?? 'never')).map((item) => <span key={item.id}>{item.type}: {item.value} mm · {item.origin}</span>)}</div>
    <div className="preview-footer"><p id="preview-safety"><b>Демонстрационна геометрия — изисква проверка от технолог.</b><br/>Размерите и номиналните дължини не са одобрени производствени изчисления.</p><div><button type="button" className="print-button" onClick={() => window.print()}>Разпечатай визуализация</button><button type="button" className="secondary-button" onClick={onClose}>Затвори</button></div></div>
  </section></div>
}
