import { useMemo, useState } from 'react'
import { catalogueExport, duplicateCatalogueProfile, profileStatusLabels, roleLabels } from '../profileCatalogueState'
import type { ActiveProfileSelection, CatalogueProfile, ProfileCatalogueFilters, ProfileRole } from '../profileCatalogueTypes'
import { catalogueHasRequiredRoles, validateCatalogueProfile } from '../profileCatalogueValidation'
import { ContextHelp } from './ContextHelp'
import { ProfileEditor } from './ProfileEditor'
import { FacadeFlowWorkspaceHeader } from './FacadeFlowWorkspaceHeader'

interface Props { profiles: CatalogueProfile[]; selection: ActiveProfileSelection; onProfiles: (profiles: CatalogueProfile[], changedProfileId?: string) => boolean; onSelection: (selection: ActiveProfileSelection) => void; onClose: () => void }
const blankProfile = (): CatalogueProfile => { const now = new Date().toISOString(); return { id: crypto.randomUUID(), role: 'FRAME', system: '', code: '', nameBg: '', dimensionA: 1, dimensionB: 1, status: 'DEMONSTRATION', createdAt: now, updatedAt: now, simulationOnly: true, requiresHumanApproval: true } }

export function ProfileCatalogue({ profiles, selection, onProfiles, onSelection, onClose }: Props) {
  const [filters, setFilters] = useState<ProfileCatalogueFilters>({ role: 'ALL', system: '', status: 'ALL' }), [editing, setEditing] = useState<CatalogueProfile | null>(null), [errors, setErrors] = useState<string[]>([])
  const visible = useMemo(() => profiles.filter((item) => (filters.role === 'ALL' || item.role === filters.role) && (filters.status === 'ALL' || item.status === filters.status) && (!filters.system || item.system.toLocaleLowerCase('bg').includes(filters.system.toLocaleLowerCase('bg')))), [profiles, filters])
  const save = () => { if (!editing) return; const result = validateCatalogueProfile(editing, profiles); setErrors(result.errors); if (!result.valid) return; if (!onProfiles(profiles.some(({ id }) => id === editing.id) ? profiles.map((item) => item.id === editing.id ? editing : item) : [...profiles, editing], editing.id)) return; setEditing(null) }
  const setActive = (role: ProfileRole, id: string) => { const item = profiles.find((profile) => profile.id === id); if (!item || item.status === 'ARCHIVED') return; onSelection({ ...selection, [role]: id }) }
  return <div className="preview-overlay catalogue-overlay ff-section-workspace"><section className="catalogue-modal" role="dialog" aria-modal="true" aria-labelledby="catalogue-title">
    <FacadeFlowWorkspaceHeader titleId="catalogue-title" icon="catalogue" eyebrow="Данни и каталози" title="Каталог на профилите" subtitle="Локален каталог в паметта · без потвърдени производствени данни." onBack={onClose}/>
    <div className="catalogue-workspace-content">
    <div className="catalogue-warning" role="note"><b>Размер A / Размер B — временни наименования.</b> Наименованията и технологичното значение на Размер A и Размер B предстоят за потвърждение от технолог. <ContextHelp helpId="profile-dimensions"/></div>
    {!catalogueHasRequiredRoles(profiles) && <div className="inline-errors" role="alert">Необходим е поне един активен профил за каса, крило и делител.</div>}
    <div className="catalogue-toolbar"><button className="primary" onClick={() => { setEditing(blankProfile()); setErrors([]) }}>Добави профил</button><label>Роля<select value={filters.role} onChange={(event) => setFilters({ ...filters, role: event.target.value as ProfileCatalogueFilters['role'] })}><option value="ALL">Всички</option>{Object.entries(roleLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label>Система<input value={filters.system} onChange={(event) => setFilters({ ...filters, system: event.target.value })}/></label><label>Статус<select value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value as ProfileCatalogueFilters['status'] })}><option value="ALL">Всички</option>{Object.entries(profileStatusLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><button onClick={() => catalogueExport(profiles)}>Експортирай симулационен каталог</button></div>
    <div className="catalogue-content"><div className="catalogue-list">{visible.map((item) => <article key={item.id} className={item.status === 'ARCHIVED' ? 'archived' : ''}><div><span className="context-badge">{roleLabels[item.role]}</span><span className="catalogue-status-badge">{item.status === 'ARCHIVED' ? 'Архивиран' : 'Активен'}</span><b>{item.code} — {item.nameBg}</b><small>{item.system} · Размер A {item.dimensionA} mm · Размер B {item.dimensionB} mm</small><small>{profileStatusLabels[item.status]} · {item.description}</small>{item.status === 'DEMONSTRATION' && <strong>Примерни placeholder стойности — не са реални каталожни данни.</strong>}</div><div className="catalogue-actions"><label>{selection[item.role] === item.id ? 'Основен за тази роля' : 'Задай като основен'}<input type="radio" name={`active-${item.role}`} checked={selection[item.role] === item.id} disabled={item.status === 'ARCHIVED'} onChange={() => setActive(item.role, item.id)}/></label><button onClick={() => { setEditing({ ...item }); setErrors([]) }}>Редактирай</button><button onClick={() => { const now = new Date().toISOString(), copy = duplicateCatalogueProfile(item, crypto.randomUUID(), now); setEditing(copy); setErrors([]) }}>Дублирай</button><button onClick={() => { const nextStatus = item.status === 'ARCHIVED' ? 'DEMONSTRATION' : 'ARCHIVED'; onProfiles(profiles.map((profile) => profile.id === item.id ? { ...profile, status: nextStatus, updatedAt: new Date().toISOString() } : profile), item.id) }}>{item.status === 'ARCHIVED' ? 'Възстанови' : 'Архивирай'}</button></div></article>)}</div>{editing && <ProfileEditor value={editing} errors={errors} onChange={setEditing} onSave={save} onCancel={() => setEditing(null)}/>}</div>
    </div>
  </section></div>
}
