import type { MachiningOperation, Orientation, Profile } from '../types'
interface Props { profile: Profile; operations: MachiningOperation[]; orientation: Orientation }
export function ProfileWorkspace({ profile, operations, orientation }: Props) {
  const length = profile.length > 0 && Number.isFinite(profile.length) ? profile.length : 1
  const xFor = (x: number) => 90 + (orientation === 'left' ? x / length : 1 - x / length) * 720
  return <section className="workspace panel" aria-labelledby="workspace-title"><div className="workspace-head"><div><span className="eyebrow">РАБОТНА ЗОНА</span><h2 id="workspace-title">Визуализация на профила</h2></div><div className="legend"><span><i className="dot drill" />Пробиване</span><span><i className="dot mill" />Фрезоване</span></div></div>
    <div className="canvas-wrap"><svg viewBox="0 0 900 430" role="img" aria-label={`Профил с дължина ${profile.length} милиметра и ${operations.length} операции`}><defs><pattern id="metal" width="12" height="12" patternUnits="userSpaceOnUse"><path d="M0 12L12 0" stroke="#d8e0e4" strokeWidth="1" /></pattern><marker id="arrow" markerWidth="8" markerHeight="8" refX="4" refY="4" orient="auto-start-reverse"><path d="M8 0L0 4L8 8" fill="#64747b" /></marker></defs><line x1="90" y1="95" x2="810" y2="95" className="dimension" markerStart="url(#arrow)" markerEnd="url(#arrow)"/><line x1="90" y1="108" x2="90" y2="70" className="guide"/><line x1="810" y1="108" x2="810" y2="70" className="guide"/><text x="450" y="78" className="dim-label">{profile.length} mm</text><rect x="90" y="150" width="720" height="150" rx="4" className="profile-shape"/><rect x="98" y="158" width="704" height="134" rx="2" fill="url(#metal)"/><line x1="90" y1="225" x2="810" y2="225" className="centerline"/>
      {operations.map((op, index) => { const x = xFor(op.x); return <g key={op.id}>{op.type === 'drill' ? <circle cx={x} cy="225" r={Math.max(7, Math.min(16, op.diameter))} className="op drill-shape"/> : <rect x={x - 20} y="213" width="40" height="24" rx="12" className="op mill-shape"/>}<line x1={x} y1="195" x2={x} y2="132" className="op-guide"/><circle cx={x} cy="125" r="14" className="number-badge"/><text x={x} y="130" className="number-text">{index + 1}</text><text x={x} y="330" className="op-label">X {op.x}</text></g> })}<text x="90" y="365" className="origin">0</text><text x="810" y="365" className="origin" textAnchor="end">{profile.length}</text><path d={orientation === 'left' ? 'M90 345h45l-10-7m10 7l-10 7' : 'M810 345h-45l10-7m-10 7l10 7'} className="orientation-arrow"/></svg></div><div className="workspace-meta"><span><b>{profile.system}</b> · {profile.code || 'Без код'}</span><span>{profile.width} × {profile.height} mm</span><span>{orientation === 'left' ? 'Ляво начало' : 'Дясно начало'}</span></div>
  </section>
}
