import { useMemo, useRef, useState } from 'react'
import type { CombinedAnalysisJob } from '../combinedAnalysisTypes'
import { validateProvisionalDraft, type RecognitionDerivedDraft } from '../combinedProvisionalDraft'
import type { ProductParameters } from '../productTypes'
import { getProductTemplate, productTemplates } from '../productTemplates'
import { ProductDrawing } from './ProductDrawing'

interface Props { draft: RecognitionDerivedDraft; analysis: CombinedAnalysisJob; baseProduct: ProductParameters; onDraft: (draft: RecognitionDerivedDraft) => void; onReject: () => void; onVerify: (draft: RecognitionDerivedDraft) => void }
const confidenceText = (confidence: number, warning?: string) => `${confidence.toFixed(1)}%${warning ? ` · ${warning}` : ''}`

export function ProvisionalProductDraft({ draft, analysis, baseProduct, onDraft, onReject, onVerify }: Props) {
  const form = useRef<HTMLDivElement>(null)
  const [checked, setChecked] = useState(false)
  const errors = useMemo(() => validateProvisionalDraft(draft), [draft])
  const template = getProductTemplate(draft.templateId || 'REF-01')
  const product: ProductParameters = { ...baseProduct, templateId: template.id, type: template.category, width: draft.width ?? baseProduct.width, height: draft.height ?? baseProduct.height }
  const update = (patch: Partial<RecognitionDerivedDraft>) => onDraft({ ...draft, ...patch, status: 'NEEDS_REVIEW', humanVerified: false, machineReady: false, updatedAt: new Date().toISOString() })
  return <section className="provisional-product" aria-labelledby="provisional-product-title"><header><div><span>АВТОМАТИЧНО ПОПЪЛНЕНА СИМУЛАЦИОННА ЧЕРНОВА</span><h3 id="provisional-product-title">Предложение за изделие · NEEDS_REVIEW</h3></div><p>recognitionDerived: true · automaticallyPopulated: true · humanVerified: false · machineReady: false</p></header>
    <div className="provisional-compare"><section><h4>Оригинална потвърдена зона</h4><img src={draft.sourceCropDataUrl} alt="Оригинална зона, от която е създадена автоматичната чернова"/><p>Стр. {draft.sourcePage} · X {Math.round(draft.sourceCrop.x)}, Y {Math.round(draft.sourceCrop.y)} · {Math.round(draft.sourceCrop.width)} × {Math.round(draft.sourceCrop.height)} px</p><p title={draft.sourceSha256}>Source: {draft.sourceFileName} · SHA-256 {draft.sourceSha256.slice(0, 16)}…</p></section><section><h4>Редактируема продуктова визуализация</h4>{draft.templateId ? <ProductDrawing product={product} template={template} selectedComponentId={null} onSelectComponent={() => undefined}/> : <div className="provisional-missing-model">Схемата е двусмислена или липсва. Изберете REF схема ръчно, за да се покаже модел.</div>}</section></div>
    <div ref={form} className="provisional-fields"><label>Предложена схема<select value={draft.templateId} onChange={(event) => update({ templateId: event.target.value })}><option value="">Изберете схема</option>{productTemplates.map((item) => <option key={item.id} value={item.id}>{item.id} — {item.name}</option>)}</select><small>{confidenceText(draft.evidence.templateId.confidence, draft.evidence.templateId.warning)}</small></label><label>Ширина (mm)<input type="number" min="1" value={draft.width ?? ''} aria-invalid={draft.width === null} onChange={(event) => update({ width: event.target.value ? Number(event.target.value) : null })}/><small>{confidenceText(draft.evidence.width.confidence, draft.evidence.width.warning)}</small></label><label>Височина (mm)<input type="number" min="1" value={draft.height ?? ''} aria-invalid={draft.height === null} onChange={(event) => update({ height: event.target.value ? Number(event.target.value) : null })}/><small>{confidenceText(draft.evidence.height.confidence, draft.evidence.height.warning)}</small></label><label>Количество<input type="number" min="1" step="1" value={draft.quantity} onChange={(event) => update({ quantity: Number(event.target.value) })}/><small>{confidenceText(draft.evidence.quantity.confidence, draft.evidence.quantity.warning)}</small></label><label>Продуктова референция<input value={draft.productReference} onChange={(event) => update({ productReference: event.target.value })}/><small>{confidenceText(draft.evidence.productReference.confidence, draft.evidence.productReference.warning)}</small></label><label>Проект / референция<input value={draft.projectReference} onChange={(event) => update({ projectReference: event.target.value })}/><small>Ръчно редактируемо поле</small></label></div>
    <section className="provisional-unresolved"><h4>Нерешени предложения</h4>{draft.unresolvedCandidateIds.length ? <ul>{analysis.candidates.filter((candidate) => draft.unresolvedCandidateIds.includes(candidate.id)).map((candidate) => <li key={candidate.id}>{candidate.type}: {candidate.normalizedValue} — {candidate.warning ?? 'изисква човешка преценка'}</li>)}</ul> : <p>Няма допълнителни нерешени предложения.</p>}</section>
    {errors.length > 0 && <ul className="form-errors" role="alert">{errors.map((error) => <li key={error}>{error}</li>)}</ul>}<div className="provisional-actions"><button type="button" onClick={() => form.current?.querySelector<HTMLElement>('input,select')?.focus()}>Коригирай предложението</button><button type="button" onClick={() => form.current?.querySelector<HTMLSelectElement>('select')?.focus()}>Избери друга схема</button><button type="button" className="danger-button" onClick={onReject}>Отхвърли автоматичната чернова</button></div><div className="provisional-verification"><label><input type="checkbox" checked={checked} onChange={(event) => setChecked(event.target.checked)}/>Проверих схемата и всички размери по оригиналния чертеж.</label><button type="button" className="primary-button" disabled={!checked || errors.length > 0} onClick={() => onVerify({ ...draft, status: 'VERIFIED', humanVerified: true, updatedAt: new Date().toISOString() })}>Потвърди след проверка</button><p>Потвърждението не създава операции и не прави изделието машинно готово.</p></div>
  </section>
}
