import { useState, type DragEvent } from 'react'
import type { StructuredProfileConfiguration } from '../hybridProductDesigner'
import { applyComposerItem, applyComposerTemplate, clearComposition, confirmComposition, deleteSelectedComposerComponent, moveComposerHinge, selectComposerComponent, selectComposerField } from '../visualComposerState'
import { VISUAL_COMPOSER_TEMPLATES } from '../visualComposerTemplates'
import type { ComposerItemType, VisualComposition } from '../visualComposerTypes'

interface Props { configuration: StructuredProfileConfiguration; initial: VisualComposition; onChange: (value: VisualComposition) => void; onBack: () => void }
const library: Array<{ type: ComposerItemType; label: string; group: string }> = [
  { type: 'DIVIDER_VERTICAL', label: 'Вертикален делител', group: 'Компоненти' }, { type: 'DIVIDER_HORIZONTAL', label: 'Хоризонтален делител', group: 'Компоненти' },
  { type: 'FIELD_FIXED', label: 'Фиксирано поле', group: 'Полета' }, { type: 'FIELD_OPENING', label: 'Отваряемо крило', group: 'Полета' },
  { type: 'OPEN_LEFT', label: 'Ляво', group: 'Отваряне' }, { type: 'OPEN_RIGHT', label: 'Дясно', group: 'Отваряне' }, { type: 'OPEN_TILT', label: 'Падащо', group: 'Отваряне' }, { type: 'OPEN_TILT_LEFT', label: 'Комбинирано ляво', group: 'Отваряне' }, { type: 'OPEN_TILT_RIGHT', label: 'Комбинирано дясно', group: 'Отваряне' }, { type: 'OPEN_FIXED', label: 'Фиксирано', group: 'Отваряне' },
  { type: 'HANDLE', label: 'Дръжка', group: 'Демонстрационни компоненти' }, { type: 'HINGE', label: 'Панта', group: 'Демонстрационни компоненти' },
]
export function VisualTemplateComposer({ configuration, initial, onChange, onBack }: Props) {
  const [state, setState] = useState(initial), [reviewChecked, setReviewChecked] = useState(false), [past, setPast] = useState<VisualComposition[]>([]), [future, setFuture] = useState<VisualComposition[]>([]), [libraryItem, setLibraryItem] = useState<ComposerItemType>('FIELD_OPENING')
  const commit = (next: VisualComposition) => { if (next.status !== 'HUMAN_CONFIRMED') setReviewChecked(false); if (next === state || JSON.stringify(next) === JSON.stringify(state)) { setState(next); return }; setPast((items) => [...items, state]); setFuture([]); setState(next); onChange(next) }
  const undo = () => { const previous = past.at(-1); if (!previous) return; setPast((items) => items.slice(0, -1)); setFuture((items) => [state, ...items]); setState(previous); onChange(previous) }
  const redo = () => { const next = future[0]; if (!next) return; setFuture((items) => items.slice(1)); setPast((items) => [...items, state]); setState(next); onChange(next) }
  const apply = (item = libraryItem) => commit(applyComposerItem(state, item, () => crypto.randomUUID()))
  const drop = (event: DragEvent, fieldId?: string, positionRatio = .5) => { event.preventDefault(); const templateId = event.dataTransfer.getData('application/x-facadeflow-template'), item = event.dataTransfer.getData('application/x-facadeflow-item') as ComposerItemType, hingeId = event.dataTransfer.getData('application/x-facadeflow-hinge'); if (templateId) commit(applyComposerTemplate(state, templateId)); else if (hingeId) { const hinge = state.components.find((component) => component.id === hingeId && component.type === 'HINGE'); if (hinge?.parentFieldId === fieldId) commit(moveComposerHinge(state, hingeId, positionRatio)) } else if (item) applyComposerItemToField(item, fieldId, positionRatio) }
  const applyComposerItemToField = (item: ComposerItemType, fieldId?: string, positionRatio = .5) => { const target = fieldId ? selectComposerField(state, fieldId) : state; commit(applyComposerItem(target, item, () => crypto.randomUUID(), positionRatio)) }
  const selectedField = state.fields.find(({ id }) => id === state.selectedFieldId), selectedComponent = state.components.find(({ id }) => id === state.selectedComponentId), selectedHingeNumber = selectedComponent?.type === 'HINGE' ? state.components.filter((item) => item.type === 'HINGE' && item.parentFieldId === selectedComponent.parentFieldId).findIndex((item) => item.id === selectedComponent.id) + 1 : 0
  return <main className="visual-composer"><header className="visual-composer-header"><div><nav aria-label="Път"><span>Конструктор на изделие</span><b>›</b><span>Визуален конструктор</span></nav><h3>{configuration.productName || 'Прозорец'} · {configuration.overallWidth} × {configuration.overallHeight} mm</h3></div><button type="button" onClick={onBack}>Назад към конфигурацията</button></header>
    <div className="visual-composer-warning">Концептуална 2D композиция — не е производствен чертеж.</div>
    <div className="visual-composer-toolbar"><button onClick={undo} disabled={!past.length}>Undo</button><button onClick={redo} disabled={!future.length}>Redo</button><button onClick={() => { if (window.confirm('Да се изчисти ли текущата концептуална композиция?')) commit(clearComposition()) }} disabled={!state.templateId}>Изчисти композицията</button><button disabled>3D · Предстои</button><output>Статус: {statusLabel(state.status)}</output></div>
    <div className="visual-composer-layout"><aside className="visual-library"><h4>Шаблони и компоненти</h4><h5>Демонстрационни шаблони</h5>{VISUAL_COMPOSER_TEMPLATES.map((template) => <button key={template.id} draggable onDragStart={(event) => event.dataTransfer.setData('application/x-facadeflow-template', template.id)} onClick={() => commit(applyComposerTemplate(state, template.id))}>{template.nameBg}<small>DEMO</small></button>)}<h5>Компоненти</h5>{library.map((item) => <button key={item.type} className={libraryItem === item.type ? 'selected' : ''} draggable onDragStart={(event) => event.dataTransfer.setData('application/x-facadeflow-item', item.type)} onClick={() => setLibraryItem(item.type)}>{item.label}<small>{item.group} · DEMO placeholder</small></button>)}<button className="primary-button" onClick={() => apply()} disabled={!state.selectedFieldId}>Добави към избраното поле</button></aside>
      <section className="visual-composer-stage" onDragOver={(event) => event.preventDefault()} onDrop={(event) => drop(event)}><ComposerDrawing state={state} width={Number(configuration.overallWidth)} height={Number(configuration.overallHeight)} onField={(id) => commit(selectComposerField(state, id))} onComponent={(id) => commit(selectComposerComponent(state, id))} onDrop={drop}/>{state.message && <p className="visual-composer-message" aria-live="polite">{state.message}</p>}<div className="visual-legend"><span>▰ Каса</span><span>□ Фиксирано</span><span>◇ Отваряемо</span><span>● Дръжка</span><span>▬ Панта</span></div></section>
      <aside className="visual-properties"><h4>Свойства на избрания елемент</h4>{selectedField ? <><dl><dt>Поле</dt><dd>{fieldDisplayName(state.fields, selectedField.id)}</dd><dt>Технически ID</dt><dd><small>{selectedField.id}</small></dd><dt>Тип</dt><dd>{selectedField.fieldType === 'FIXED' ? 'Фиксирано' : 'Отваряемо'}</dd><dt>Отваряне</dt><dd>{openingLabel(selectedField.openingDirection)}</dd><dt>Дръжка</dt><dd>{selectedField.attachedHandleId ? 'Демонстрационна' : 'Няма'}</dd><dt>Панти</dt><dd>{selectedField.attachedHingeIds.length}</dd></dl></> : <p>Няма избрано поле.</p>}{selectedComponent && <><p><b>Избран компонент:</b> {selectedComponent.type === 'HINGE' ? `Панта ${selectedHingeNumber}` : selectedComponent.type}</p><small>Технически ID: {selectedComponent.id}</small>{selectedComponent.type === 'HINGE' && <><label>Позиция по височината<input type="range" min="0" max="100" step="1" value={Math.round((selectedComponent.positionRatio ?? .5) * 100)} onChange={(event) => commit(moveComposerHinge(state, selectedComponent.id, Number(event.target.value) / 100))} onKeyDown={(event) => { if (event.shiftKey && (event.key === 'ArrowUp' || event.key === 'ArrowDown')) { event.preventDefault(); commit(moveComposerHinge(state, selectedComponent.id, (selectedComponent.positionRatio ?? .5) + (event.key === 'ArrowUp' ? .1 : -.1))) } }}/></label><output>{Math.round((selectedComponent.positionRatio ?? .5) * 100)}%</output><p>Концептуална позиция — не е производствен размер.</p></>}<button onClick={() => commit(deleteSelectedComposerComponent(state))} disabled={selectedComponent.role === 'DIVIDER'}>Изтрий избрания компонент</button></>}<hr/><label><input type="checkbox" checked={reviewChecked} onChange={(event) => setReviewChecked(event.target.checked)}/> Проверих концептуалната композиция.</label><button className="primary-button" onClick={() => commit(confirmComposition(state, reviewChecked))} disabled={!state.templateId || !reviewChecked}>Потвърди след проверка</button><small>Потвърждението не е производствено или машинно одобрение.</small></aside></div>
  </main>
}
function ComposerDrawing({ state, width, height, onField, onComponent, onDrop }: { state: VisualComposition; width: number; height: number; onField: (id: string) => void; onComponent: (id: string) => void; onDrop: (event: DragEvent, fieldId?: string, positionRatio?: number) => void }) {
  const x0 = 70, y0 = 55, w = 660, h = 400
  if (!state.templateId) return <div className="visual-empty-drop">Изберете или плъзнете демонстрационен шаблон тук.</div>
  return <svg viewBox="0 0 800 520" role="img" aria-label="Концептуална двумерна композиция"><rect x={x0} y={y0} width={w} height={h} className="composer-frame"/>{state.fields.map((field) => { const x = x0 + field.rect.x * w, y = y0 + field.rect.y * h, fw = field.rect.width * w, fh = field.rect.height * h, name = fieldDisplayName(state.fields, field.id); return <g key={field.id} role="button" tabIndex={0} aria-label={name} onClick={() => onField(field.id)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') onField(field.id) }} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.stopPropagation(); const svg = event.currentTarget.ownerSVGElement, box = svg?.getBoundingClientRect(), viewY = box ? (event.clientY - box.top) * 520 / box.height : y + fh / 2; onDrop(event, field.id, (viewY - y) / fh) }}><rect x={x + 8} y={y + 8} width={fw - 16} height={fh - 16} className={`composer-field ${state.selectedFieldId === field.id ? 'selected' : ''}`}/>{field.fieldType === 'OPENABLE' && field.openingDirection && <OpeningMark direction={field.openingDirection} x={x + 14} y={y + 14} width={fw - 28} height={fh - 28}/>}<text x={x + fw / 2} y={y + 28}>{name}</text>{field.fieldType === 'OPENABLE' && !field.openingDirection && <text className="composer-unassigned" x={x + fw / 2} y={y + fh / 2}>Посоката не е избрана</text>}{field.attachedHandleId && <circle cx={x + fw - 22} cy={y + fh / 2} r="6" className="composer-hardware" onClick={(event) => { event.stopPropagation(); onComponent(field.attachedHandleId!) }}/>} {field.attachedHingeIds.map((id) => { const hinge = state.components.find((item) => item.id === id); if (!hinge) return null; return <rect key={id} draggable onDragStart={(event) => { event.stopPropagation(); event.dataTransfer.setData('application/x-facadeflow-hinge', id) }} x={hinge.side === 'RIGHT' ? x + fw - 18 : x + 10} y={y + (hinge.positionRatio ?? .5) * fh - 9} width="8" height="18" className={`composer-hardware ${state.selectedComponentId === id ? 'selected' : ''}`} onClick={(event) => { event.stopPropagation(); onComponent(id) }}/>} )}</g>})}<Dimension x1={x0} y1={y0 - 20} x2={x0 + w} y2={y0 - 20} label={`${width} mm`}/><Dimension x1={x0 - 25} y1={y0} x2={x0 - 25} y2={y0 + h} label={`${height} mm`} vertical/></svg>
}
function OpeningMark({ direction, x, y, width, height }: { direction: string; x: number; y: number; width: number; height: number }) { if (direction === 'FIXED') return null; const apexX = direction.includes('RIGHT') || direction === 'RIGHT' ? x : x + width, midY = y + height / 2; return <g className="composer-opening"><path d={`M ${x} ${y} L ${apexX} ${midY} L ${x} ${y + height}`}/>{direction.includes('TILT') && <path d={`M ${x} ${y + height} L ${x + width / 2} ${y} L ${x + width} ${y + height}`}/>}</g> }
function Dimension({ x1, y1, x2, y2, label, vertical = false }: { x1: number; y1: number; x2: number; y2: number; label: string; vertical?: boolean }) { return <g className="composer-dimension"><line x1={x1} y1={y1} x2={x2} y2={y2}/><text x={vertical ? x1 - 8 : (x1 + x2) / 2} y={vertical ? (y1 + y2) / 2 : y1 - 7} transform={vertical ? `rotate(-90 ${x1 - 8} ${(y1 + y2) / 2})` : undefined}>{label}</text></g> }
const statusLabel = (status: string) => status === 'EMPTY' ? 'Празна' : status === 'DRAFT' ? 'Чернова' : status === 'NEEDS_REVIEW' ? 'Нуждае се от проверка' : 'Потвърдена от човек'
const fieldDisplayName = (fields: VisualComposition['fields'], id: string) => { const index = fields.findIndex((field) => field.id === id); if (fields.length === 2) return index === 0 ? 'Ляво поле' : 'Дясно поле'; if (fields.length === 3) return index === 0 ? 'Ляво поле' : index === 1 ? 'Средно поле' : 'Дясно поле'; return `Поле ${index + 1}` }
const openingLabel = (direction: string | null) => direction ? ({ LEFT: 'Ляво', RIGHT: 'Дясно', TILT: 'Падащо', TILT_LEFT: 'Комбинирано ляво', TILT_RIGHT: 'Комбинирано дясно', FIXED: 'Фиксирано' }[direction] ?? 'Не е избрано') : 'Не е избрано'
