import type { ConceptualBounds, ConceptualMaterial, ConceptualScene, ConceptualSceneNode, ConceptualViewState, ProjectedNode, ProjectedPoint } from './conceptual3dTypes'
import { clampConceptualZoom, projectConceptualPoint } from './conceptual3dCamera'

export const DEMO_DEPTHS = { frameDepth: .11, sashDepth: .075, glassOffset: .018, panelOffset: .028, hardwareOffset: .08 } as const
export const neutralColor = '#8a989b'
export const previewColor = (value: string) => ({ WHITE: '#f4f4ef', ANTHRACITE: '#465156', BLACK: '#20272a', BROWN: '#79533c', SILVER: '#b9c2c4' } as Record<string, string>)[value] ?? neutralColor
export function shadeConceptualColor(hex:string,factor:number){const match=/^#([0-9a-f]{6})$/i.exec(hex);if(!match)return neutralColor;const value=Number.parseInt(match[1]!,16),channel=(shift:number)=>Math.max(0,Math.min(255,Math.round(((value>>shift)&255)*factor))).toString(16).padStart(2,'0');return`#${channel(16)}${channel(8)}${channel(0)}`}
export const material = (front: string, back: string, opacity = 1, edge = '#183f46'): ConceptualMaterial => ({ front, back, opacity, edge })
export const node = (nodeId: string, semanticSourceId: string, kind: ConceptualSceneNode['kind'], bounds: ConceptualBounds, value: ConceptualMaterial, label: string, selectable = false, openingLabel?: string): ConceptualSceneNode => ({ nodeId, semanticSourceId, kind, bounds, material: value, label, selectable, openingLabel, conceptualPreviewOnly: true, productionGeometry: false })
export function scaleNodesToProductAspect(nodes: ConceptualSceneNode[], productWidth = 1, productHeight = 1) { const safeWidth=Number.isFinite(productWidth)&&productWidth>0?productWidth:1,safeHeight=Number.isFinite(productHeight)&&productHeight>0?productHeight:1,max=Math.max(safeWidth,safeHeight),sx=safeWidth/max,sy=safeHeight/max; return { nodes:nodes.map(entry=>({...entry,bounds:{...entry.bounds,x:entry.bounds.x*sx,y:entry.bounds.y*sy,width:entry.bounds.width*sx,height:entry.bounds.height*sy}})), bounds:{x:-sx/2,y:-sy/2,z:-.08,width:sx,height:sy,depth:.18} } }
export const scene = (category: ConceptualScene['category'], nodes: ConceptualSceneNode[], thresholdUnresolved = false, bounds: ConceptualBounds = { x: -.5, y: -.5, z: -.08, width: 1, height: 1, depth: .18 }, overallWidth = 1, overallHeight = 1): ConceptualScene => ({ nodes, bounds, category, overallWidth, overallHeight, thresholdUnresolved, sessionOnly: true, simulationOnly: true, machineReady: false, internalEvaluationOnly: true, productionApproved: false, sourceImmutable: true, geometryCreated: false, exportAvailable: false, dwgWriteAvailable: false, machineConnectivityAvailable: false, conceptualPreviewOnly: true, productionGeometry: false })

const face = (bounds: ConceptualBounds) => [{ x: bounds.x, y: bounds.y, z: bounds.z + bounds.depth }, { x: bounds.x + bounds.width, y: bounds.y, z: bounds.z + bounds.depth }, { x: bounds.x + bounds.width, y: bounds.y + bounds.height, z: bounds.z + bounds.depth }, { x: bounds.x, y: bounds.y + bounds.height, z: bounds.z + bounds.depth }]
export function projectBoundsFaces(bounds: ConceptualBounds, view: ConceptualViewState, width: number, height: number): ProjectedPoint[][] { const x0=bounds.x,x1=bounds.x+bounds.width,y0=bounds.y,y1=bounds.y+bounds.height,z0=bounds.z,z1=bounds.z+bounds.depth, points=[{x:x0,y:y0,z:z0},{x:x1,y:y0,z:z0},{x:x1,y:y1,z:z0},{x:x0,y:y1,z:z0},{x:x0,y:y0,z:z1},{x:x1,y:y0,z:z1},{x:x1,y:y1,z:z1},{x:x0,y:y1,z:z1}].map(point=>projectConceptualPoint(point,view,width,height)); return [[points[0]!,points[1]!,points[2]!,points[3]!],[points[4]!,points[5]!,points[6]!,points[7]!],[points[0]!,points[1]!,points[5]!,points[4]!],[points[1]!,points[2]!,points[6]!,points[5]!],[points[2]!,points[3]!,points[7]!,points[6]!],[points[3]!,points[0]!,points[4]!,points[7]!]].sort((a,b)=>a.reduce((s,p)=>s+p.depth,0)-b.reduce((s,p)=>s+p.depth,0)) }
export function projectScene(sceneValue: ConceptualScene, view: ConceptualViewState, width: number, height: number): ProjectedNode[] { return sceneValue.nodes.map((entry) => { const polygon = face(entry.bounds).map((point) => projectConceptualPoint(point, view, width, height)); return { node: entry, polygon, depth: polygon.reduce((sum, point) => sum + point.depth, 0) / polygon.length } }).sort((a, b) => a.depth - b.depth) }
export function projectedSceneExtents(sceneValue: ConceptualScene, view: ConceptualViewState, width: number, height: number) { const points=sceneValue.nodes.flatMap(entry=>projectBoundsFaces(entry.bounds,view,width,height).flat()); if(!points.length)return{x:0,y:0,width:0,height:0}; const xs=points.map(point=>point.x),ys=points.map(point=>point.y),x=Math.min(...xs),y=Math.min(...ys);return{x,y,width:Math.max(...xs)-x,height:Math.max(...ys)-y} }
export function fitSceneToViewport(sceneValue: ConceptualScene, view: ConceptualViewState, width: number, height: number, padding = 28): ConceptualViewState { const base={...view,zoom:1},extents=projectedSceneExtents(sceneValue,base,width,height),availableWidth=Math.max(1,width-padding*2),availableHeight=Math.max(1,height-padding*2),zoom=extents.width&&extents.height?Math.min(availableWidth/extents.width,availableHeight/extents.height):1;return{...view,zoom:clampConceptualZoom(zoom)} }
export function sceneFitsViewport(sceneValue: ConceptualScene, view: ConceptualViewState, width: number, height: number, padding = 20) { const extents=projectedSceneExtents(sceneValue,view,width,height);return extents.x>=padding&&extents.y>=padding&&extents.x+extents.width<=width-padding&&extents.y+extents.height<=height-padding }
export function pointInPolygon(point: { x: number; y: number }, polygon: ProjectedPoint[], tolerance = 0) { let inside = false; for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i++) { const a = polygon[i]!, b = polygon[j]!; if (((a.y > point.y) !== (b.y > point.y)) && point.x < (b.x - a.x) * (point.y - a.y) / (b.y - a.y) + a.x) inside = !inside } if (inside) return true; if (!tolerance) return false; return polygon.some((p) => Math.hypot(p.x - point.x, p.y - point.y) <= tolerance) }
export function hitTestProjected(nodes: ProjectedNode[], x: number, y: number) { return [...nodes].reverse().find((entry) => entry.node.selectable && pointInPolygon({ x, y }, entry.polygon, entry.node.kind.endsWith('MARKER') ? 12 : 3))?.node ?? null }
