import type { ConceptualScene, ConceptualViewState, ProjectedNode } from './conceptual3dTypes'
import { projectBoundsFaces, projectedSceneExtents, projectScene, shadeConceptualColor } from './conceptual3dScene'

export interface RenderResult { projected: ProjectedNode[] }
const path = (context: CanvasRenderingContext2D, polygon: ProjectedNode['polygon']) => { context.beginPath(); polygon.forEach((point, index) => index ? context.lineTo(point.x, point.y) : context.moveTo(point.x, point.y)); context.closePath() }
export const visibleConceptualColor = (material: ProjectedNode['node']['material'], view: ConceptualViewState) => Math.cos(view.yaw) < 0 ? material.back : material.front
function dimensions(context:CanvasRenderingContext2D,scene:ConceptualScene,view:ConceptualViewState,width:number,height:number){const box=projectedSceneExtents(scene,view,width,height),bottom=Math.min(height-8,box.y+box.height+16),left=Math.max(8,box.x-16);context.save();context.strokeStyle='#405e64';context.fillStyle='#29484f';context.lineWidth=1;context.font='600 11px system-ui';context.textAlign='center';context.beginPath();context.moveTo(box.x,bottom);context.lineTo(box.x+box.width,bottom);context.moveTo(box.x,bottom-4);context.lineTo(box.x,bottom+4);context.moveTo(box.x+box.width,bottom-4);context.lineTo(box.x+box.width,bottom+4);context.stroke();context.fillText(`${scene.overallWidth} mm`,box.x+box.width/2,bottom-3);context.save();context.translate(left,box.y+box.height/2);context.rotate(-Math.PI/2);context.beginPath();context.moveTo(-box.height/2,0);context.lineTo(box.height/2,0);context.stroke();context.fillText(`${scene.overallHeight} mm`,0,-3);context.restore();context.restore()}
export function renderConceptualScene(context: CanvasRenderingContext2D, scene: ConceptualScene, view: ConceptualViewState, width: number, height: number, selectedId: string | null): RenderResult {
  context.clearRect(0, 0, width, height); context.fillStyle = '#eef3f3'; context.fillRect(0, 0, width, height)
  context.strokeStyle = 'rgba(45,82,88,.12)'; context.lineWidth = 1; const grid = Math.max(24, Math.min(width, height) / 12); for (let x = width % grid; x < width; x += grid) { context.beginPath(); context.moveTo(x, 0); context.lineTo(x, height); context.stroke() } for (let y = height % grid; y < height; y += grid) { context.beginPath(); context.moveTo(0, y); context.lineTo(width, y); context.stroke() }
  const projected = projectScene(scene, view, width, height)
  for (const entry of projected) { const faces=projectBoundsFaces(entry.node.bounds,view,width,height),base=visibleConceptualColor(entry.node.material,view); faces.forEach((polygon,index)=>{path(context,polygon);context.globalAlpha=entry.node.material.opacity;context.fillStyle=shadeConceptualColor(base,.72+index*.056);context.fill();context.globalAlpha=1;context.strokeStyle=entry.node.semanticSourceId===selectedId?'#e3762d':entry.node.material.edge;context.lineWidth=entry.node.semanticSourceId===selectedId?3:1.1;context.stroke()}); if(entry.node.openingLabel){const center=entry.polygon.reduce((value,point)=>({x:value.x+point.x/4,y:value.y+point.y/4}),{x:0,y:0});context.fillStyle='#164f58';context.font='600 12px system-ui';context.textAlign='center';context.fillText(`↗ ${entry.node.openingLabel}`,center.x,center.y)} }
  dimensions(context,scene,view,width,height)
  return { projected }
}
