export interface DetailDraftViewport { scale: number; offsetX: number; offsetY: number }
export interface DetailDraftDocument { id: string; entities: readonly never[]; simulationOnly: true; machineReady: false; internalEvaluationOnly: true; productionApproved: false }
export const DETAIL_DRAFT_VIEWPORT_LIMITS = Object.freeze({ minimumScale: 0.25, maximumScale: 8, zoomStep: 1.15 })
export const DETAIL_DRAFT_SAFETY = Object.freeze({ sessionOnly: true, viewportOnly: true, mutatesDwg: false, createsGeometry: false, exportsData: false, machineReady: false, internalEvaluationOnly: true })
export const DETAIL_DRAFT_INITIAL_VIEWPORT: DetailDraftViewport = Object.freeze({ scale: 1, offsetX: 0, offsetY: 0 })
export function createDetailDraftDocument(id = 'detail-draft-session'): DetailDraftDocument { return Object.freeze({ id, entities: Object.freeze([]), simulationOnly: true, machineReady: false, internalEvaluationOnly: true, productionApproved: false }) }
export function panDetailDraftViewport(viewport: DetailDraftViewport, deltaX: number, deltaY: number): DetailDraftViewport { if (![deltaX, deltaY].every(Number.isFinite)) return viewport; return { ...viewport, offsetX: viewport.offsetX + deltaX, offsetY: viewport.offsetY + deltaY } }
export function zoomDetailDraftViewport(viewport: DetailDraftViewport, factor: number, anchorX: number, anchorY: number): DetailDraftViewport { if (![factor, anchorX, anchorY].every(Number.isFinite) || factor <= 0) return viewport; const scale = Math.min(DETAIL_DRAFT_VIEWPORT_LIMITS.maximumScale, Math.max(DETAIL_DRAFT_VIEWPORT_LIMITS.minimumScale, viewport.scale * factor)); const appliedFactor = scale / viewport.scale; return { scale, offsetX: anchorX - (anchorX - viewport.offsetX) * appliedFactor, offsetY: anchorY - (anchorY - viewport.offsetY) * appliedFactor } }
export function fitDetailDraftViewport(width: number, height: number): DetailDraftViewport { if (![width, height].every(Number.isFinite) || width <= 0 || height <= 0) return DETAIL_DRAFT_INITIAL_VIEWPORT; return { scale: 1, offsetX: width / 2, offsetY: height / 2 } }
