import { clampPositionRatio } from './visualComposerState'
import { DOOR_TEMPLATES } from './doorComposerTemplates'
import type { DoorColor, DoorComposition, DoorHingeSide, DoorSwing, DoorInfill, DoorSelectedTool } from './doorComposerTypes'
const safe={sessionOnly:true,simulationOnly:true,machineReady:false,internalEvaluationOnly:true,productionApproved:false,sourceImmutable:true,geometryCreated:false,exportAvailable:false,dwgWriteAvailable:false,machineConnectivityAvailable:false} as const
export const emptyDoorComposition=():DoorComposition=>({templateId:null,fields:[],hardware:[],selectedFieldId:null,selectedHardwareId:null,selectedTool:null,thresholdStatus:'UNRESOLVED',thresholdProfileId:null,conceptuallyReviewed:false,status:'NEEDS_REVIEW',interiorColor:'',exteriorColor:'',interiorColorCustom:'',exteriorColorCustom:'',...safe})
const edit=(s:DoorComposition,p:Partial<DoorComposition>):DoorComposition=>({...s,...p,conceptuallyReviewed:false,status:'NEEDS_REVIEW'})
export const applyDoorTemplate=(s:DoorComposition,id:string):DoorComposition=>{const t=DOOR_TEMPLATES.find(x=>x.id===id);return t?edit(s,{templateId:id,fields:t.fields.map(f=>({...f,rect:{...f.rect},hingeIds:[]})),hardware:[],selectedFieldId:t.fields[0]?.id??null,selectedHardwareId:null,selectedTool:null}):s}
export const setDoorOpening=(s:DoorComposition,id:string,hingeSide:DoorHingeSide,swing:DoorSwing):DoorComposition=>{const field=s.fields.find(f=>f.id===id);if(!field||field.role!=='DOOR_LEAF')return s;const remove=!hingeSide;return edit(s,{fields:s.fields.map(f=>f.id===id?{...f,hingeSide,swing:hingeSide?swing:null,hingeIds:remove?[]:f.hingeIds,handleId:remove?null:f.handleId}:f),hardware:remove?s.hardware.filter(h=>h.parentFieldId!==id):s.hardware.map(h=>h.parentFieldId!==id?h:{...h,side:h.kind==='HINGE'?hingeSide:hingeSide==='LEFT'?'RIGHT':'LEFT'}),selectedHardwareId:remove?null:s.selectedHardwareId})}
export const setDoorInfill=(s:DoorComposition,id:string,infill:DoorInfill,split=.55):DoorComposition=>edit(s,{fields:s.fields.map(f=>f.id===id&&f.role==='DOOR_LEAF'?{...f,infill,splitRatio:clampPositionRatio(split)}:f)})
export function suggestDoorHingePosition(s:DoorComposition,id:string){const used=s.hardware.filter(h=>h.parentFieldId===id&&h.kind==='HINGE').map(h=>h.positionRatio);if(!used.length)return .5;const candidates=[.18,.82,.34,.66,.1,.9,.26,.74];return candidates.reduce((best,candidate)=>Math.min(...used.map(value=>Math.abs(value-candidate)))>Math.min(...used.map(value=>Math.abs(value-best)))?candidate:best,candidates[0]!)}
export function addDoorHardware(s:DoorComposition,id:string,kind:'HINGE'|'HANDLE',makeId:()=>string,position?:number){const f=s.fields.find(x=>x.id===id);if(!f||f.role!=='DOOR_LEAF'||!f.hingeSide||(kind==='HANDLE'&&f.handleId))return s;const hardwareId=makeId(),side=kind==='HINGE'?f.hingeSide:f.hingeSide==='LEFT'?'RIGHT':'LEFT',initial=position??(kind==='HINGE'?suggestDoorHingePosition(s,id):.5);return edit(s,{fields:s.fields.map(x=>x.id!==id?x:kind==='HINGE'?{...x,hingeIds:[...x.hingeIds,hardwareId]}:{...x,handleId:hardwareId}),hardware:[...s.hardware,{id:hardwareId,kind,parentFieldId:id,positionRatio:clampPositionRatio(initial),side,handleStyle:kind==='HANDLE'?'STANDARD':undefined,source:'DEMO',simulationOnly:true,machineReady:false,productionApproved:false}],selectedFieldId:id,selectedHardwareId:hardwareId,selectedTool:kind})}
export const conceptuallyReviewDoor=(s:DoorComposition,checked:boolean):DoorComposition=>checked&&s.fields.filter(f=>f.role==='DOOR_LEAF').every(f=>f.hingeSide&&f.swing)?{...s,conceptuallyReviewed:true,status:'NEEDS_REVIEW'}:s
export const selectDoorField=(s:DoorComposition,id:string):DoorComposition=>s.fields.some(f=>f.id===id)?{...s,selectedFieldId:id,selectedHardwareId:null}:s
export const selectDoorHardware=(s:DoorComposition,id:string):DoorComposition=>{const hardware=s.hardware.find(h=>h.id===id);return hardware?{...s,selectedFieldId:hardware.parentFieldId,selectedHardwareId:id}:s}
export const selectDoorTool=(s:DoorComposition,tool:DoorSelectedTool):DoorComposition=>({...s,selectedTool:tool})
export const moveDoorHardware=(s:DoorComposition,id:string,ratio:number):DoorComposition=>s.hardware.some(h=>h.id===id)?edit(s,{hardware:s.hardware.map(h=>h.id===id?{...h,positionRatio:clampPositionRatio(ratio)}:h)}):s
export const deleteDoorHardware=(s:DoorComposition,id:string):DoorComposition=>{const hardware=s.hardware.find(h=>h.id===id);if(!hardware)return s;return edit(s,{hardware:s.hardware.filter(h=>h.id!==id),fields:s.fields.map(f=>f.id!==hardware.parentFieldId?f:{...f,hingeIds:f.hingeIds.filter(x=>x!==id),handleId:f.handleId===id?null:f.handleId}),selectedHardwareId:null})}
export const setDoorHandleStyle=(s:DoorComposition,id:string,handleStyle:NonNullable<DoorComposition['hardware'][number]['handleStyle']>,customDescription=''):DoorComposition=>s.hardware.some(h=>h.id===id&&h.kind==='HANDLE')?edit(s,{hardware:s.hardware.map(h=>h.id===id?{...h,handleStyle,customDescription:handleStyle==='CUSTOM'?customDescription:undefined}:h)}):s
export const setDoorColor=(s:DoorComposition,surface:'INTERIOR'|'EXTERIOR',color:DoorColor,custom=''):DoorComposition=>edit(s,surface==='INTERIOR'?{interiorColor:color,interiorColorCustom:color==='CUSTOM'?custom:''}:{exteriorColor:color,exteriorColorCustom:color==='CUSTOM'?custom:''})
export const validateDoorComposition=(s:DoorComposition):string[]=>{const errors:string[]=[];if(!s.templateId||!s.fields.length)errors.push('Изберете шаблон.');for(const f of s.fields.filter(x=>x.role==='DOOR_LEAF')){if(!f.hingeSide)errors.push(`${doorFieldDisplayName(s.fields,f.id)}: изберете страна на пантите.`);if(!f.swing)errors.push(`${doorFieldDisplayName(s.fields,f.id)}: изберете посока навътре или навън.`)}return errors}
export const canConceptuallyReviewDoor=(s:DoorComposition,acknowledged:boolean)=>acknowledged&&validateDoorComposition(s).length===0
export const canConfigureDoorOpening=(s:DoorComposition)=>s.fields.find(f=>f.id===s.selectedFieldId)?.role==='DOOR_LEAF'
export const canAddDoorHardware=(s:DoorComposition)=>Boolean(s.fields.find(f=>f.id===s.selectedFieldId&&f.role==='DOOR_LEAF'&&f.hingeSide))
export function doorOpeningWorkflowStatus(s:DoorComposition){const field=s.fields.find(f=>f.id===s.selectedFieldId);if(!field)return'Първо изберете крило';if(field.role==='FIXED_GLAZING')return'Фиксираното поле няма отваряне';if(!field.hingeSide)return'Изберете страна на пантите';if(!field.swing)return'Изберете навътре или навън. Можете да добавите панти';return'Отварянето е зададено'}
export const clearDoorComposition=()=>emptyDoorComposition()
export function doorFieldDisplayName(fields:DoorComposition['fields'],id:string){const ordered=[...fields].sort((a,b)=>a.rect.y-b.rect.y||a.rect.x-b.rect.x),index=ordered.findIndex(f=>f.id===id);if(index<0)return'Неизвестно поле';if(ordered.length===1)return ordered[0]?.role==='DOOR_LEAF'?'Крило':'Фиксирано поле';if(ordered.length===2&&ordered[0]?.rect.y===ordered[1]?.rect.y)return index===0?'Ляво поле':'Дясно поле';return `Поле ${index+1} от ${ordered.length}`}
