import type { CustomProduct } from './customGeometryTypes'
import type { ProductParameters } from './productTypes'
import { getProductTemplate } from './productTemplates'

export type StructuredWorkflowStep = 'DIMENSIONS' | 'FRAME' | 'DIVIDERS' | 'SASHES' | 'OPENING_DIRECTIONS' | 'REVIEW' | 'CONCEPTUAL_3D'
export const structuredWorkflowOrder: StructuredWorkflowStep[] = ['DIMENSIONS', 'FRAME', 'DIVIDERS', 'SASHES', 'OPENING_DIRECTIONS', 'REVIEW', 'CONCEPTUAL_3D']
export const structuredWorkflowLabels: Record<StructuredWorkflowStep, string> = { DIMENSIONS: 'Общи размери', FRAME: 'Външна каса', DIVIDERS: 'Делители', SASHES: 'Крила', OPENING_DIRECTIONS: 'Посоки на отваряне', REVIEW: 'Проверка', CONCEPTUAL_3D: 'Концептуален 3D преглед' }
export interface OrderedStructuredProduct { dimensions: { width: number; height: number }; frame: { exists: boolean; profileId?: string }; dividers: Array<{ id: string; orientation: 'VERTICAL' | 'HORIZONTAL'; sourcePath: string }>; sashes: Array<{ fieldId: string; profileId?: string }>; openingDirections: Array<{ fieldId: string; direction: 'left' | 'right' }>; humanReviewed: boolean; machineReady: false }
const validDimensions = (width: number, height: number) => Number.isFinite(width) && width > 0 && Number.isFinite(height) && height > 0
export function customWorkflowState(product: CustomProduct): Record<StructuredWorkflowStep, boolean> { const nodes = flattenCustom(product), sashes = nodes.filter((node) => node.kind === 'LEAF' && node.fieldType === 'OPENING_SASH'); return { DIMENSIONS: validDimensions(product.width, product.height), FRAME: product.frameCreated && Boolean(product.frameProfileId), DIVIDERS: product.frameCreated, SASHES: product.frameCreated && sashes.every((node) => node.kind === 'LEAF' && Boolean(node.sashProfileId)), OPENING_DIRECTIONS: sashes.every((node) => node.kind === 'LEAF' && Boolean(node.openingDirection)), REVIEW: product.status === 'VERIFIED', CONCEPTUAL_3D: product.status === 'VERIFIED' } }
function flattenCustom(product: CustomProduct) { const nodes = [product.geometry], visit = (node: CustomProduct['geometry']) => { if (node.kind === 'SPLIT') { nodes.push(node.first, node.second); visit(node.first); visit(node.second) } }; visit(product.geometry); return nodes }
export function customToOrderedModel(product: CustomProduct): OrderedStructuredProduct { const nodes = flattenCustom(product); return { dimensions: { width: product.width, height: product.height }, frame: { exists: product.frameCreated, profileId: product.frameProfileId }, dividers: nodes.flatMap((node) => node.kind === 'SPLIT' ? [{ id: node.id, orientation: node.orientation, sourcePath: node.id }] : []), sashes: nodes.flatMap((node) => node.kind === 'LEAF' && node.fieldType === 'OPENING_SASH' ? [{ fieldId: node.id, profileId: node.sashProfileId }] : []), openingDirections: nodes.flatMap((node) => node.kind === 'LEAF' && node.fieldType === 'OPENING_SASH' && node.openingDirection ? [{ fieldId: node.id, direction: node.openingDirection }] : []), humanReviewed: product.status === 'VERIFIED', machineReady: false } }
export function templateReferenceToOrderedModel(templateId: string, width: number, height: number, humanReviewed: boolean): OrderedStructuredProduct { const template = getProductTemplate(templateId); return { dimensions: { width, height }, frame: { exists: validDimensions(width, height) }, dividers: template.dividers.map((item) => ({ id: item.id, orientation: item.orientation === 'vertical' ? 'VERTICAL' : 'HORIZONTAL', sourcePath: item.id })), sashes: template.fields.flatMap((item) => item.state === 'opening' || item.state === 'sliding' ? [{ fieldId: item.id }] : []), openingDirections: template.fields.flatMap((item) => item.state === 'opening' && item.openingDirection ? [{ fieldId: item.id, direction: item.openingDirection }] : []), humanReviewed, machineReady: false } }
export function templateToOrderedModel(product: ProductParameters, humanReviewed = true): OrderedStructuredProduct { return templateReferenceToOrderedModel(product.templateId, product.width, product.height, humanReviewed) }
