export type ComposerStatus = 'EMPTY' | 'DRAFT' | 'NEEDS_REVIEW' | 'HUMAN_CONFIRMED'
export type ComposerFieldType = 'FIXED' | 'OPENABLE'
export type ComposerOpeningDirection = 'LEFT' | 'RIGHT' | 'TILT' | 'TILT_LEFT' | 'TILT_RIGHT' | 'FIXED'
export type ComposerItemType = 'DIVIDER_VERTICAL' | 'DIVIDER_HORIZONTAL' | 'FIELD_FIXED' | 'FIELD_OPENING' | 'OPEN_LEFT' | 'OPEN_RIGHT' | 'OPEN_TILT' | 'OPEN_TILT_LEFT' | 'OPEN_TILT_RIGHT' | 'OPEN_FIXED' | 'HANDLE' | 'HINGE'
export type ComposerComponentRole = 'DIVIDER' | 'HANDLE' | 'HINGE'
export type ComposerColor = '' | 'WHITE' | 'ANTHRACITE' | 'BLACK' | 'BROWN' | 'SILVER' | 'CUSTOM'
export interface ComposerRect { x: number; y: number; width: number; height: number }
export interface ComposerField { id: string; rect: ComposerRect; fieldType: ComposerFieldType; openingDirection: ComposerOpeningDirection | null; attachedHandleId: string | null; attachedHingeIds: string[]; humanReviewState: 'UNREVIEWED' | 'HUMAN_CONFIRMED' }
export interface ComposerComponent { id: string; type: 'VERTICAL_DIVIDER' | 'HORIZONTAL_DIVIDER' | 'HANDLE' | 'HINGE'; parentFieldId: string | null; role: ComposerComponentRole; placement: string; positionRatio?: number; side?: 'LEFT' | 'RIGHT'; source: 'DEMO'; simulationOnly: true; machineReady: false; productionApproved: false }
export interface ComposerTemplate { id: string; nameBg: string; fields: Array<{ id: string; rect: ComposerRect; fieldType: ComposerFieldType; openingDirection: ComposerOpeningDirection | null }>; dividers: Array<{ id: string; type: 'VERTICAL_DIVIDER' | 'HORIZONTAL_DIVIDER'; placement: string; positionRatio: number }> }
export interface VisualComposition { templateId: string | null; fields: ComposerField[]; components: ComposerComponent[]; selectedFieldId: string | null; selectedComponentId: string | null; interiorColor: ComposerColor; exteriorColor: ComposerColor; interiorColorCustom: string; exteriorColorCustom: string; status: ComposerStatus; message: string; sessionOnly: true; simulationOnly: true; machineReady: false; internalEvaluationOnly: true; productionApproved: false; sourceImmutable: true; exportAvailable: false; dwgWriteAvailable: false; machineConnectivityAvailable: false; geometryCreated: false }
