export const NADEZHDA_GOLDEN_PATTERN_FIXTURES_VERSION = 'REALDATA02.4' as const

export type NadezhdaGoldenKnownGap =
  | 'COMMON_GEOMETRY_AFTER_VARIANTS_REQUIRES_EXPLICIT_SCOPE'
  | 'MULTI_BASIS_PRICING_REMAINS_TEXT_EVIDENCE'
  | 'COMMERCIAL_SCOPE_AFTER_MULTIPLE_VARIANTS_REQUIRES_REVIEW'
  | 'BARE_PRE_MODULE_GLAZING_REQUIRES_HARDENING'

export interface NadezhdaGoldenPatternExpectation {
  moduleCount: number
  variantCount: number
  totalProductGroupCount: number
  sameGeometryGroupCount: number
  floorPlacementLabels?: string[]
  materials?: string[]
  includedItemCount?: number
  excludedItemCount?: number
  vatIncluded?: boolean | null
}

export interface NadezhdaGoldenPatternFixture {
  id: string
  patternFamily:
    | 'MIXED_PRODUCT_GROUPS'
    | 'FLOOR_HIERARCHY'
    | 'ALTERNATIVE_VARIANTS_SHARED_GEOMETRY'
    | 'MULTI_BASIS_PRICING'
    | 'MULTIPLE_OFFER_VARIANTS'
    | 'MULTI_SYSTEM_VARIANT_AND_COMMERCIAL_SECTIONS'
    | 'MIXED_GROUPS_WITH_PRE_MODULE_ATTRIBUTE'
  sourceReference: string
  sourceText: string
  expectation: NadezhdaGoldenPatternExpectation
  knownGaps: NadezhdaGoldenKnownGap[]
  provenance: {
    derivedFromPrivateReferencePattern: true
    containsOriginalPrivateDocumentText: false
    containsClientIdentity: false
    safeForTrackedRegressionFixture: true
  }
}

const trackedSafeProvenance = Object.freeze({
  derivedFromPrivateReferencePattern: true,
  containsOriginalPrivateDocumentText: false,
  containsClientIdentity: false,
  safeForTrackedRegressionFixture: true,
}) as NadezhdaGoldenPatternFixture['provenance']

export const NADEZHDA_GOLDEN_PATTERN_FIXTURES: readonly NadezhdaGoldenPatternFixture[] = [
  {
    id: 'NAD-GOLDEN-A',
    patternFamily: 'MIXED_PRODUCT_GROUPS',
    sourceReference: 'SYNTHETIC_GOLDEN_A.docx',
    sourceText: [
      'обект : SYNTHETIC-SITE-A',
      'PVC дограма',
      'Профил: SYNTH-PVC-70',
      'Цвят: RAL 9000',
      'Стъклопакет: SYNTH-GLASS-24',
      'Обков: SYNTH-HW-A',
      'Модул: 1',
      'Брой: 13',
      'L =1800 mm',
      'H =800 mm',
      'Модул: 2',
      'Брой: 12',
      'L =600 mm',
      'H =800 mm',
      'AL дограма',
      'Профил: SYNTH-AL-THERMAL',
      'Цвят: RAL 9000',
      'Стъклопакет: SYNTH-GLASS-22',
      'Обков: SYNTH-HW-A',
      'Модул: 3',
      'Брой: 4',
      'L =1800 mm',
      'H =2100 mm',
      'Модул: 4',
      'Брой: 2',
      'L =1100 mm',
      'H =2800 mm',
      'AL врати',
      'Профил: SYNTH-AL-COLD',
      'Цвят: RAL 9000',
      'Модул: 5',
      'Брой: 46',
      'L =750 mm',
      'H =2100 mm',
    ].join('\n'),
    expectation: {
      moduleCount: 5,
      variantCount: 1,
      totalProductGroupCount: 3,
      sameGeometryGroupCount: 0,
      materials: ['PVC', 'ALUMINIUM', 'ALUMINIUM'],
    },
    knownGaps: [],
    provenance: trackedSafeProvenance,
  },
  {
    id: 'NAD-GOLDEN-B',
    patternFamily: 'FLOOR_HIERARCHY',
    sourceReference: 'SYNTHETIC_GOLDEN_B.docx',
    sourceText: [
      'обект : SYNTHETIC-SITE-B',
      'AL дограма',
      'Профил: SYNTH-AL-70',
      'Цвят: RAL 7016',
      'Обков: SYNTH-HW-B',
      'Етаж 1',
      'Модул: 1',
      'Брой: 1',
      'L =1420 mm',
      'H =1420 mm',
      'Модул: 2',
      'Брой: 1',
      'L =1740 mm',
      'H =1430 mm',
      'Етаж 2',
      'Модул: 3',
      'Брой: 1',
      'L =1740 mm',
      'H =1430 mm',
      'Модул: 4',
      'Брой: 1',
      'L =2380 mm',
      'H =1900 mm',
      'Етаж 3',
      'Модул: 5',
      'Брой: 1',
      'L =1650 mm',
      'H =1650 mm',
    ].join('\n'),
    expectation: {
      moduleCount: 5,
      variantCount: 1,
      totalProductGroupCount: 1,
      sameGeometryGroupCount: 1,
      floorPlacementLabels: ['Етаж 1', 'Етаж 2', 'Етаж 3'],
      materials: ['ALUMINIUM'],
    },
    knownGaps: [],
    provenance: trackedSafeProvenance,
  },
  {
    id: 'NAD-GOLDEN-C',
    patternFamily: 'ALTERNATIVE_VARIANTS_SHARED_GEOMETRY',
    sourceReference: 'SYNTHETIC_GOLDEN_C.docx',
    sourceText: [
      'обект : SYNTHETIC-SITE-C',
      'Вариант 1: Алуминиева дограма SYNTH-AL-70',
      'Цвят: RAL 7016',
      'Обков: SYNTH-HW-C',
      'Стъклопакет: SYNTH-GLASS-44',
      'Вариант 2: PVC дограма SYNTH-PVC-80',
      'Цвят: RAL 7016',
      'Обков: SYNTH-HW-C',
      'Стъклопакет: SYNTH-GLASS-44',
      'Армировка: 2,0 мм',
      'Спецификация:',
      'Модул: 1',
      'Брой: 6',
      'L =2000 mm',
      'H =2600 mm',
      'Модул: 2',
      'Брой: 2',
      'L =900 mm',
      'H =1100 mm',
      'Модул: 3',
      'Брой: 1',
      'L =900 mm',
      'H =1100 mm',
    ].join('\n'),
    expectation: {
      moduleCount: 3,
      variantCount: 2,
      totalProductGroupCount: 2,
      sameGeometryGroupCount: 1,
      materials: ['ALUMINIUM', 'PVC'],
    },
    knownGaps: [],
    provenance: trackedSafeProvenance,
  },
  {
    id: 'NAD-GOLDEN-D',
    patternFamily: 'MULTI_BASIS_PRICING',
    sourceReference: 'SYNTHETIC_GOLDEN_D.docx',
    sourceText: [
      'обект : SYNTHETIC-SITE-D',
      'PVC дограма',
      'Профил: SYNTH-PVC-60',
      'Цвят: бял',
      'Стъклопакет: SYNTH-GLASS-24',
      'ЦЕНА: 100 лв. /м.кв.',
      'Отваряемо крило – 200 лв. / бр.',
      'Усилващ вертикален профил – 20 лв. / м.',
      'Външен перваз – 10 лв. / м.',
      'Обща цена: 9999 лв. без ДДС',
      'Модул: 1',
      'Брой: 21',
      'L =6100 mm',
      'H =1250 mm',
      'Модул: 2',
      'Брой: 6',
      'L =6100 mm',
      'H =1250 mm',
    ].join('\n'),
    expectation: {
      moduleCount: 2,
      variantCount: 1,
      totalProductGroupCount: 1,
      sameGeometryGroupCount: 1,
      materials: ['PVC'],
      vatIncluded: false,
    },
    knownGaps: ['MULTI_BASIS_PRICING_REMAINS_TEXT_EVIDENCE'],
    provenance: trackedSafeProvenance,
  },
  {
    id: 'NAD-GOLDEN-E',
    patternFamily: 'MULTIPLE_OFFER_VARIANTS',
    sourceReference: 'SYNTHETIC_GOLDEN_E.docx',
    sourceText: [
      'обект : SYNTHETIC-SITE-E',
      'Вариант 1: PVC дограма SYNTH-A',
      'Цвят: SYNTH-COLOR',
      'Стъклопакет: SYNTH-32',
      'Обков: SYNTH-HW-E',
      'Армировка: 1 мм',
      'Вариант 2: PVC дограма SYNTH-B',
      'Цвят: SYNTH-COLOR',
      'Стъклопакет: SYNTH-44',
      'Обков: SYNTH-HW-E',
      'Армировка: 1,5 мм',
      'Вариант 3: AL дограма SYNTH-C',
      'Цвят: SYNTH-COLOR',
      'Стъклопакет: SYNTH-32',
      'Обков: SYNTH-HW-E',
      'Вариант 4: AL дограма SYNTH-D',
      'Цвят: SYNTH-COLOR',
      'Стъклопакет: SYNTH-44',
      'Обков: SYNTH-HW-E',
      'Спецификация',
      'Модул: 1',
      'Брой: 2',
      'L =2000 mm',
      'H =1700 mm',
      'Модул: 2',
      'Брой: 1',
      'L =800 mm',
      'H =2100 mm',
      'Модул: 3',
      'Брой: 1',
      'L =800 mm',
      'H =2100 mm',
    ].join('\n'),
    expectation: {
      moduleCount: 3,
      variantCount: 4,
      totalProductGroupCount: 4,
      sameGeometryGroupCount: 1,
      materials: ['PVC', 'PVC', 'ALUMINIUM', 'ALUMINIUM'],
    },
    knownGaps: [],
    provenance: trackedSafeProvenance,
  },
  {
    id: 'NAD-GOLDEN-F',
    patternFamily: 'MULTI_SYSTEM_VARIANT_AND_COMMERCIAL_SECTIONS',
    sourceReference: 'SYNTHETIC_GOLDEN_F.docx',
    sourceText: [
      'обект : SYNTHETIC-SITE-F',
      'Вариант 1: Алуминиева дограма SYNTH-E75',
      'Цвят: RAL 7016',
      'Обков: SYNTH-HW-F1',
      'Стъклопакет: SYNTH-44-A',
      'Алуминиева дограма SYNTH-SLIDE-70',
      'Цвят: RAL 7016',
      'Обков: SYNTH-HW-SLIDE',
      'Стъклопакет: SYNTH-44-B',
      'Вариант 2: Алуминиева дограма SYNTH-EW70',
      'Цвят: RAL 7016',
      'Обков: SYNTH-HW-F2',
      'Стъклопакет: SYNTH-44-A',
      'Алуминиева дограма SYNTH-SLIDE-70',
      'Цвят: RAL 7016',
      'Обков: SYNTH-HW-SLIDE',
      'Стъклопакет: SYNTH-44-B',
      'В цената са включени :',
      'Синтетичен носещ профил',
      'Синтетична външна мембрана',
      '',
      'Модул: 1',
      'Брой: 1',
      'L =1700 mm',
      'H =1690 mm',
      'Модул: 2',
      'Брой: 1',
      'L =1900 mm',
      'H =2520 mm',
      'Модул: 3',
      'Брой: 1',
      'L =1900 mm',
      'H =2520 mm',
      'В посочената цена не са включени :',
      'Синтетичен вътрешен перваз',
      'Синтетичен комарник',
    ].join('\n'),
    expectation: {
      moduleCount: 3,
      variantCount: 2,
      totalProductGroupCount: 4,
      sameGeometryGroupCount: 1,
      materials: ['ALUMINIUM', 'ALUMINIUM', 'ALUMINIUM', 'ALUMINIUM'],
      includedItemCount: 2,
      excludedItemCount: 2,
    },
    knownGaps: [
      'COMMON_GEOMETRY_AFTER_VARIANTS_REQUIRES_EXPLICIT_SCOPE',
      'COMMERCIAL_SCOPE_AFTER_MULTIPLE_VARIANTS_REQUIRES_REVIEW',
    ],
    provenance: trackedSafeProvenance,
  },
  {
    id: 'NAD-GOLDEN-G',
    patternFamily: 'MIXED_GROUPS_WITH_PRE_MODULE_ATTRIBUTE',
    sourceReference: 'SYNTHETIC_GOLDEN_G.docx',
    sourceText: [
      'обект : SYNTHETIC-SITE-G',
      'PVC дограма',
      'Профил: SYNTH-PVC-70',
      'Цвят: бял',
      'Стъклопакет: SYNTH-DEFAULT-24',
      'Обков: SYNTH-HW-G',
      'Армировка: 1,5 мм',
      'Модул: 1',
      'Брой: 1',
      'L =2600 mm',
      'H =2200 mm',
      'AL дограма',
      'Профил: SYNTH-AL-60',
      'Цвят: бял',
      'Стъклопакет: SYNTH-DEFAULT-22',
      'Модул: 2',
      'Брой: 3',
      'L =3150 mm',
      'H =2400 mm',
      'SYNTH-SPECIAL-ARMORED-GLASS/24 mm',
      'Модул: 3',
      'Брой: 2',
      'L =5300 mm',
      'H =480 mm',
      'AL врати',
      'Профил: SYNTH-AL-COLD',
      'Цвят: бял',
      'Модул: 4',
      'Брой: 4',
      'L =750 mm',
      'H =2100 mm',
    ].join('\n'),
    expectation: {
      moduleCount: 4,
      variantCount: 1,
      totalProductGroupCount: 3,
      sameGeometryGroupCount: 0,
      materials: ['PVC', 'ALUMINIUM', 'ALUMINIUM'],
    },
    knownGaps: ['BARE_PRE_MODULE_GLAZING_REQUIRES_HARDENING'],
    provenance: trackedSafeProvenance,
  },
] as const
